### ISSUE TITLE
Add report after each test run

### ISSUE THREAD

**Issue by mattsse** [gakonst/foundry#1004]
### Component

Forge

### Describe the feature you would like

rn the output of a test runner is like this

```console
Running x tests for <A>.<A>
[PASS] .....

Running x tests for <B>.<B>
[PASS] .....
```

It'd be useful to wrap up each block with an overview

```console
test result: ok. X passed; Y failed; Z ignored; finished in 19.04s
```

**Comment by onbjerg** [comment]
Also, in the summary of failed tests we should consider changing it from `[FAIL. Reason: bla] testFoo()` to `[FAIL. Reason: bla] SomeTest::testFoo()` or similar so the overview makes more sense. Maybe we should even include the traces/logs etc. in this summary?

**Comment by ecmendenhall** [comment]
Any objections if I pick this one up?

**Comment by mattsse** [comment]
please do, happy to review a draft and provide helpers!
