### ISSUE TITLE
vm.expectRevert fail reason parsing custom errors as strings

### ISSUE THREAD

**Issue by DaniPopes** [gakonst/foundry#1007]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (64f779a 2022-03-20T00:11:33.074266889+00:00)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

Encountered this error while converting `require` string reverts into Solidity 0.8.4 custom errors:

![image](https://user-images.githubusercontent.com/57450786/159356752-3e0c4653-0a7b-46c9-8483-d65959c62fff.png)

It seems like forge is trying to parse the expected error (custom error's selector) in the first fail as a string and it ends up with those replacement characters.

Below is an example contract on how to reproduce this error. Using `forge-std` and `ds-test` just for the Vm interface and address.

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;

import "ds-test/test.sol";
import "forge-std/Vm.sol";

contract Contract {
    error CustomError();

    function requireStringFail() public pure {
        require(false, "Require string");
    }

    function customErrorFail() public pure {
        revert CustomError();
    }
}

contract TestContract is DSTest {
    Vm internal vm = Vm(HEVM_ADDRESS);
    Contract internal extContract;
    
    function setUp() public {
        extContract = new Contract();
    }

    function testExpectRevert_customError() public {
        // works as intended
        vm.expectRevert(Contract.CustomError.selector);
        extContract.customErrorFail();

        // reverts with a string while expecting a custom error
        // Reason: Error != expected error: 'Require string' != '   ���'
        vm.expectRevert(Contract.CustomError.selector);
        extContract.requireStringFail();
    }

    // this is ok
    function testExpectRevert_string() public {
        // works as intended
        vm.expectRevert("Require string");
        extContract.requireStringFail();

        // reverts with a custom error while expecting a string
        // Reason: Error data != expected error data: 0x09caebf3 != 0x5265717569726520737472696e67
        vm.expectRevert("Require string");
        extContract.customErrorFail();
    }
}
```

**Comment by onbjerg** [comment]
I'll look into this after REVM is merged, the fix is probably not too hard. I'll keep you posted.

**Comment by zaqk** [comment]
hey @DaniPopes you should be able to account for custom errors using something like:
```solidity
bytes customError = abi.encodeWithSignature("CustomError()");
vm.expectRevert(customError);
extContract.customErrorFail();
```

**Comment by onbjerg** [comment]
We now fallback to hex if it's not a valid UTF8 string, so in your case it would look like `'Require string' != '0x09caebf3'`

**Comment by wminshew** [comment]
> hey @DaniPopes you should be able to account for custom errors using something like:
> 
> ```solidity
> bytes customError = abi.encodeWithSignature("CustomError()");
> vm.expectRevert(customError);
> extContract.customErrorFail();
> ```

leaving a note for posterity here, if you're already importing the contract w its custom errors might as well use the selector: 
```
        VM.expectRevert(
            abi.encodeWithSelector(
                ImportedContract.CustomError.selector,
                arg1
            )
        );
        ImportedContract.customErrorFail();
```
