### ISSUE TITLE
Allow test directory to be relative

### ISSUE THREAD

**Issue by donutcrypto** [gakonst/foundry#1008]
### Component

Forge

### Describe the feature you would like

For project specific reasons, I would like to structure my codebase as follows

```
root/
| contracts/
| tests/
| | foundry/
| foundry/
| | foundry.toml
```

Currently my `foundry.toml` file looks like this:
```
[default]
src = '../contracts'
out = 'out'
libs = ['../utils/ds-test', 'node_modules']
test = '../tests/foundry'
remappings=[
    ...
]
```

It is able to build the contracts in the relative src directory, but is unable to find the relative tests folder.

Note: On further testing, it still actually checks if there is a local test directory.

Thank you!

**Comment by mattsse** [comment]
Ref #970

**Comment by donutcrypto** [comment]
> Ref #970

Appears to be different. My test directory is already outside of the source directory.
