### ISSUE TITLE
verify-contract should verify as multi-file rather than flattening

### ISSUE THREAD

**Issue by abcoathup** [gakonst/foundry#1012]
### Component

Forge

### Describe the feature you would like

`forge verify-contract` currently flattens contracts for verification.
This removes:
* License information
* Import context

`forge verify-contract` example: https://rinkeby.etherscan.io/address/0x419aacdf7b24929a95f3ed87e8269743f2eeabaf#code

Remix multi-file verification example: https://rinkeby.etherscan.io/address/0x88262f5db936d54f8a6ab2994e049dbc7b0436b9#code

## License information
Solidity only allows one SPDX License identifier per file.  Flattening removes license information from the imported files.  

Worst case scenario, this could result in a more permissive license on an imported restrictive license library being used.  
Changing licenses on open source software is a bad outcome.

## Import context
Flattened files lose import context.  

It makes it more complex to quickly identify what is imported code and what is unique to the contract.  Especially for ERC20/ERC721 using common implementations from OpenZeppelin Contracts or solmate.

Tools like https://github.com/dethcrypto/ethereum-code-viewer#readme allow verified contracts to be opened in VS Code

Compare the rich information in multi-file verification from Remix: https://rinkeby.etherscan.deth.net/address/0x88262f5db936d54f8a6ab2994e049dbc7b0436b9#code with the flattened version from Foundry: https://rinkeby.etherscan.deth.net/address/0x419aacdf7b24929a95f3ed87e8269743f2eeabaf#code

## Additional
The two arguments I have come across for flattening is:
* Make auditing easier, compare deployed contracts (I hope open in VS Code resolves this)
* Make copypasta easier (I don't think this is a benefit or something we want to encourage)

**Comment by mattsse** [comment]
Thank you so much, this is a great insight.

As I understand it, from Etherscan's pov, flattening compared to multiple files is just a different parameter.
and getting the standard json for multi-file verification is no problem.

Since there are both arguments for and against, I think the best way forward would be to simply support both?
then the question is what should we make the default method, default on etherscan is flattened.

**Comment by abcoathup** [comment]
@mattsse 
> Since there are both arguments for and against, I think the best way forward would be to simply support both?

If it is easy, then support both.  If only one can be supported, then multi-file.

> then the question is what should we make the default method, default on etherscan is flattened.

Development tools should be opinionated for best practice.
Best practice should be not removing/changing license of open source, keeping import context, discouraging easy copypasta.  

Which to me suggests that multi-file should be the default.

**Comment by gakonst** [comment]
Am open minded to the best approach here - curious what @mds1 thinks here. Personally I've preferred Etherscan single file verification because I can ctrl+f it, but could be wrong.

**Comment by gakonst** [comment]
I think we can support both..let's go with multi default and have flattened behind a flag?
