### ISSUE TITLE
forge create error message "0: Odd number of digits" is unclear

### ISSUE THREAD

**Issue by nnnnicholas** [gakonst/foundry#1013]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (77882ab 2022-03-22T00:21:29.105530+00:00)

### What command(s) is the bug in?

forge create

### Operating System

macOS (M1)

### Describe the bug

When invoked using a malformed private key, `forge create` fails with error `0: Odd number of digits`. 

### Proposed solution
The error could be revised to "Malformed private key."

### Console log
```sh
$ forge create --rpc-url $RINKEBY_RPC_URL --private-key $RINKEBY_PRIV_KEY src/Sponsor.sol:Sponsor
[⠊] Compiling...
No files changed, compilation skipped
Error: 
   0: Odd number of digits

Location:
   cli/src/opts/mod.rs:235

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: _main<unknown>
      at <unknown source file>:<unknown line>
   2: _main<unknown>
      at <unknown source file>:<unknown line>
   3: _main<unknown>
      at <unknown source file>:<unknown line>
   4: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   5: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   6: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   7: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   8: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   9: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  10: _main<unknown>
      at <unknown source file>:<unknown line>
```

**Comment by onbjerg** [comment]
My best guess is that your private key is malformed (i.e. it has an odd number of digits). Try double-checking your private key.

We should improve the error message, though

**Comment by nnnnicholas** [comment]
You were correct. Thank you. I'll rewrite the issue to focus on the error message.

**Comment by binghy** [comment]
Hi, I'm sorry, but it still gives me the same error. I tried to check the private key, but that one was correct.

cast send --rpc-url=$RPC_URL <contractAddress>  "mintTo(address)" 1 --private-key=$PRIVATE_KEY

I'm sorry, just a newbie, try to getting more experience.

**Comment by mattsse** [comment]
good point, the error message should be better here, but the reason why it's complaining is that it expects a hex address and identified `1` as number

**Comment by binghy** [comment]
> good point, the error message should be better here, but the reason why it's complaining is that it expects a hex address and identified `1` as number

sorry, some confusion on my side.

Using the command: cast send --rpc-url=$RPC_URL <contractAddress>  "mintTo(address)" <arg> --private-key=$PRIVATE_KEY
(https://book.getfoundry.sh/tutorials/solmate-nft), the parameter <arg> should not be in this case the expected return value of the function "mintTo" (hence, the tokenID set to 0,1,2 or whatever)?
