### ISSUE TITLE
Skip invalid inputs produced by fuzzer strategy

### ISSUE THREAD

**Issue by mattsse** [gakonst/foundry#1038]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### Describe the bug

We currently expect all generated tokens to be valid:

https://github.com/gakonst/foundry/blob/693cbb9668bbdb32f54583dd504c2c59d03f22e3/evm/src/fuzz/strategies/state.rs#L35

which apparently does not hold, hence if encoding the input fails we panic.

can we filter those cases?

**Comment by cruzdanilo** [comment]
apparently, any test with calldata arrays is hitting `InvalidData` error.

```solidity
function testArray(uint64[2] calldata values) external {
}
```
