### ISSUE TITLE
Forge test --watch mode is not working

### ISSUE THREAD

**Issue by karmabadger** [gakonst/foundry#1039]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (d4c615b 2022-03-24T00:49:25.208986492+00:00)

### What command(s) is the bug in?

forge test --watch ./src

### Operating System

Linux

### Describe the bug

This command only runs test once, but then when I change files in either the tests or the source sol files, nothing happens and the output does not change. am I not using this correctly?
It does not recompile, it does not watch for changes, nothing at all.

Thanks for helping.

**Comment by mattsse** [comment]
hmm, I can't reproduce this locally on Mac, with or without the `./src` arg.

Not sure about linux yet.

The "src" dir is watched by default, I suppose omitting ./src also does not solve this then?

**Comment by karmabadger** [comment]
> 

@mattsse what kind of behavior are you getting ser? does it recompile and rerun the tests everytime a watched file is saved?
also to specify, it is technically WSL2 using ubuntu on bash. Tho it is basically exactly a linux kernel on hypervisor level I think so I don't think there would be much issue there. 
If not I'll test it on a remote linux and then mac to see if it's reproduceable.

**Comment by mattsse** [comment]
> @mattsse what kind of behavior are you getting ser? does it recompile and rerun the tests everytime a watched file is saved?

yeah, `forge test --watch` recompiles and tests all test in the modified file as expected, at least on mac and latest nightly

**Comment by karmabadger** [comment]
> > @mattsse what kind of behavior are you getting ser? does it recompile and rerun the tests everytime a watched file is saved?
> 
> yeah, `forge test --watch` recompiles and tests all test in the modified file as expected, at least on mac and latest nightly

yes it does recompile and tests all test when I run the command but does it track file changes and recompile the changed file and re tests all tests every time? for me it just hangs there and stops without doing anything anymore

**Comment by dmfxyz** [comment]
@mattsse I can recreate this on my local with nightly. `forge test --watch` runs the tests in watch mode, but on subsequent file changes, only re-runs the `build` cmd and not the `test` cmd. I think it has something to do with this...? https://github.com/gakonst/foundry/blob/master/cli/src/cmd/forge/watch.rs#L127. Only build args are being passed to the watch action.

**Comment by dmfxyz** [comment]
@mattsse I'm having this same issue with nightly on linux and within the docker container. `forge test --watch` runs the tests the first time, but on file-change it only re-compiles (it does not re-test). I haven't dug too deep yet, but wondering if it's because only the build args are being passed to `watch_test`? https://github.com/gakonst/foundry/blob/master/cli/src/cmd/forge/watch.rs#L127

**Comment by mds1** [comment]
I'm also seeing this, on macOS 12.2.1 with `forge 0.2.0 (721093d 2022-04-05T00:10:42.550532+00:00)`. Example outputs of what happens below:

```sh
# Initial time running `forge test -w`
$ forge test -w
[⠆] Compiling...
No files changed, compilation skipped

Running 1 test for src/test/MyContract.t.sol:MyContractConstructor
[PASS] testConstructor() (gas: 31072)
Test result: ok. 1 passed; 0 failed; finished in 10.32ms

# Now I just re-save a test file, no changes.
# Same result if I were save a contract file that has no changes.

[⠔] Compiling...
No files changed, compilation skipped

# Now make changes to a contract a save.

[⠒] Compiling...
[⠑] Compiling 14 files with 0.8.11
[⠆] Solc finished in 23.71s
Compiler run successful (with warnings)

# Warnings from the build are shown, but tests are never re-ran
```

**Comment by mattsse** [comment]
does `forge test -w --run-all` work?
perhaps we need to tweak the default behaviour a bit.

**Comment by mds1** [comment]
@mattsse yes that syntax does fix it for me!

**Comment by dmfxyz** [comment]
thanks @mattsse! Confirming that syntax also works for me.

**Comment by karmabadger** [comment]
> forge test -w --run-all

this also works for me lol. bit strange but good work around.

**Comment by karmabadger** [comment]
does  ```forge test``` not rull all of the test no matter what? what's the default behavior? what's the difference with --run-all?

**Comment by mds1** [comment]
Hm, looks like I'm seeing this again, but only for test files. When using `-w` or `-w --run-all`, changes to my `src/` contracts are detected, but not modifications to my `test/` contracts are not detected. 

Possible factors:
- I have the `test/` folder at the repo root, not nested within `src/`
- In `foundry.toml` I have `remappings = ["test/=test/"]` so I can import test contracts using an absolute path instead of a relative path, e.g. `import "test/utils/SomeUtil.sol"`

**Comment by mattsse** [comment]
yeh by default only the source dir is being watched, but you should be able to provide multiple paths after `-w` because -w should accept multiple paths, Vec<PathBuf>

**Comment by mds1** [comment]
Ah got it. The [forge-template](https://github.com/foundry-rs/forge-template) has `test/` at the root also, so we probably should have that watched by default or I suspect this will lead to confusion about watch mode not working

**Comment by mattsse** [comment]
makes sense, will make this the default, thanks!

**Comment by mds1** [comment]
Awesome, thank you!
