### ISSUE TITLE
foundryup is broken on previous nightlies

### ISSUE THREAD

**Issue by 0xAlcibiades** [gakonst/foundry#1043]
### Component

Foundryup

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (d4c615b 2022-03-24T01:05:20.744764+00:00)

### What command(s) is the bug in?

foundryup --version 01bb28c37520640e49dd3093305e62bee7619cd3

### Operating System

macOS (M1)

### Describe the bug

```
oundryup --version 01bb28c37520640e49dd3093305e62bee7619cd3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0     37      0 --:--:-- --:--:-- --:--:--    38
tar: Error opening archive: Unrecognized archive format
```

afaict, installing recent nightly versions with foundryup is broken. Tried to do this to workaround #1042

**Comment by onbjerg** [comment]
Does it work if you do `foundryup --version nightly-01bb28c37520640e49dd3093305e62bee7619cd3`?

**Comment by onbjerg** [comment]
Fixed in https://github.com/gakonst/foundry/pull/1047, but the nightly you specified no longer exists

**Comment by 0xBeans** [comment]
@onbjerg this nightly no longer exists? Should it be taken off the tags?

<img width="1233" alt="Screen Shot 2022-05-26 at 11 37 00 PM" src="https://user-images.githubusercontent.com/103160460/170644663-3c2337b7-5872-43f7-9a2f-c4d08b6ab8c7.png">

**Comment by onbjerg** [comment]
The GH workflow should automatically prune those tags but I guess it missed one for some reason
