### ISSUE TITLE
bug: foundryup fails once a branch you're on is deleted

### ISSUE THREAD

**Issue by mds1** [gakonst/foundry#1045]
### Component

Foundryup

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e881b75 2022-03-25T00:07:41.456668+00:00)

### What command(s) is the bug in?

foundryup -b master

### Operating System

macOS (amd)

### Describe the bug

Steps to reproduce:
1. Use `foundryup` to switch to a branch, such as `foundryup -b revm` (when testing https://github.com/gakonst/foundry/pull/918)
2. That branch later gets deleted
3. Run `foundryup -b master` which fails with:

```
Your configuration specifies to merge with the ref 'refs/heads/revm'
from the remote, but no such ref was fetched.
```

I fixed this by `cd`'ing into `~/.foundry/gakonst/foundry` and manually switch to the latest master, then run `foundryup -b revm`, so presumably a similar approach can be implemented in the foundryup script

**Comment by onbjerg** [comment]
Strange, I cannot reproduce this.

1. I created a branch `onbjerg/test` with some changes
2. Ran `foundryup -b onbjerg/test`
3. Deleted the branch
4. Ran `foundryup -b master`
5. No error

Do you have some global git config set that changes this behavior, and if so, do you think doing

```
git switch $BRANCH
git fetch
git reset --hard origin/$BRANCH
```

Would work? Currently we do

```
git fetch
git reset --hard origin/$BRANCH
```

**Comment by mds1** [comment]
> Strange, I cannot reproduce this.

Huh interesting, I should be able to give this another try later—it's possible I had something funky going on and perhaps https://github.com/gakonst/foundry/pull/1047 helped

> Do you have some global git config set that changes this behavior, and if so, do you think doing

Looking now, the only thing that may be related here is that I have `defaultBranch = main` under `[init]`, but from a quick look at the foundryup script I don't think that should be related

I do think running `git switch $BRANCH` first would help since that resolved it in my case, and from googling the git error that seems to be a commonly suggested solution on stackoverflow.

As a side note (perhaps I should create a separate issue): Not sure if you use the GitHub CLI, but using `gh pr checkout <prNumber>` is super great. It works seamlessly even when the branch on that PR is from a fork. I'd love a similar feature for foundryup so you can do `foundryup -pr 1048`. Seems I can't get foundryup to checkout that branch:

```
$ foundryup --repo mattse/dapptools-rs -b matt/flush-cache
Cloning into 'dapptools-rs'...
remote: Repository not found.
fatal: repository 'https://github.com/mattse/dapptools-rs/' not found
```

**Comment by onbjerg** [comment]
I *only* use `gh` for the PR checkout feature, I agree it is very very nice. I'd create a new issue for it, noting that it obviously does not support `--repo`
