### ISSUE TITLE
REVM Tracing Followups

### ISSUE THREAD

**Issue by gakonst** [gakonst/foundry#1057]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e881b75 2022-03-25T00:06:50.568028+00:00)

### What command(s) is the bug in?

forge t -vvvv

### Operating System

macOS (M1)

### Describe the bug

Tracing doesn't seem to always decode correctly. Take for example lil-web3: https://github.com/m1guelpf/lil-web3/

## ECRECOVER doesn't get decoded

The following is a call to Ecrecover which we are not decoding. I think we should be decoding it, independently of concerns about new precompiles added in L2s etc.

```
0x0000…0001::e9435c05(aa81190ba1e7e19f6372616fa7b535045c95be4afcfe0412f0fd9158000000000000000000000000000000000000000000000000000000000000001cc86807a88242d73ca11a9cfb15f54b4ea3793429728ed741d7ca77b17820637b781fb4e20122cda8916eb6dc52e950029dc2e3f5e18c34c87e636a41b9ef7c32)

```

```bash
$ forge t -vvvv -m testRevertsWhenCallReverts 
```

Output

<img width="859" alt="image" src="https://user-images.githubusercontent.com/17802178/160212285-5104d373-596c-43a5-9989-e5410785838c.png">

## Contract ABI Functions & Events are not decoded

```
 forge t -m testCanSplitToken -vvvv --force
```
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/17802178/160212863-b98f874a-1b88-4a96-b013-a6e5dc1dc758.png">

I've confirmed this is not a caching issue by usage of the `--force` flag and by `rm -rf`'ing the cache. I tried [moving](https://github.com/m1guelpf/lil-web3/blob/main/src/test/LilFractional.t.sol#L39) the `new TestNFT()` call from `setUp()` to the constructor, and it didn't seem to change anything, so the fuzzy deploy logic seems to be OK.

I wonder if this has to do with using the ERC721 as a dependency, vs explicitly declaring it in the contract?

**Comment by brockelmore** [comment]
we should see what the delta is between the runtime code from the output and the deployed runtime code

our diff_score is quite naive so probably could use with an expansion of scope/sophistication
