### ISSUE TITLE
Debugger panics on passing test case

### ISSUE THREAD

**Issue by jmcph4** [gakonst/foundry#1058]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e881b75 2022-03-25T00:03:11.855335753+00:00)

### What command(s) is the bug in?

`RUST_BACKTRACE=full forge test -vvvv --debug testPushNormalEmpty`

### Operating System

Linux

### Describe the bug

Attempting to run the debugger on a specific test case panics `forge`.

The [test case in question](https://github.com/jmcph4/albacore/blob/80f9f23e0876875b35659d80d1b2433403c843ee/src/test/RingBuffer.t.sol#L11) is reproduced here:

```solidity
    function testPushNormalEmpty() public {
        uint256 some_len = 12; /* arbitrary */
        bytes32 some_elem = bytes32(0);
        RingBuffer.RB_RingBuffer memory init_buf = RingBuffer.init(some_len);

        RingBuffer.RB_RingBuffer memory actual_buf = RingBuffer.push(
            init_buf,
            some_elem
        );

        bytes32[] memory expected_xs = new bytes32[](1);
        expected_xs[0] = some_elem;

        RingBuffer.RB_RingBuffer memory expected_buf = RingBuffer.RB_RingBuffer(
            expected_xs,
            some_len,
            0,
            1
        );

        assertEq(actual_buf.xs[0], expected_buf.xs[0]);
        assertEq(actual_buf.n, expected_buf.n);
        assertEq(actual_buf.read, expected_buf.read);
        assertEq(actual_buf.write, expected_buf.write);
    }
```

The test case succeeds:

```
$ forge test
[⠒] Compiling...
No files changed, compilation skipped

Running 2 tests for RingBufferTest.json:RingBufferTest
[PASS] testPushNormalEmpty() (gas: 14170)
[PASS] testPushNormalFull() (gas: 8289)
```

Attempting to invoke the debugger yields:

```
$ RUST_BACKTRACE=full forge test -vvvv --debug testPushNormalEmpty
[⠒] Compiling...
No files changed, compilation skipped
[⠊] Compiling...
[⠰] Compiling 3 files with 0.8.10
Compiler run successful
The application panicked (crashed).
Message:  unknown ic for pc
Location: /home/runner/work/foundry/foundry/evm/src/executor/inspector/debugger.rs:176

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: __libc_start_main<unknown>
      at ./csu/../csu/libc-start.c:308

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Aborted
```

Some additional system information:
```
$ uname -a
Linux foobar 5.10.0-10-rt-amd64 #1 SMP PREEMPT_RT Debian 5.10.84-1 (2021-12-08) x86_64 GNU/Linux
$ rustup --version
rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.59.0 (9d1b2106e 2022-02-23)`
```

**Comment by onbjerg** [comment]
Notes on fix:

@mattsse figured out it is because it is a library and those are called using `delegatecall` which the debugger inspector does not handle correctly. We need to add a way to distinguish between delegatecall/normal call in REVM and adjust the inspector accordingly

**Comment by MerlinEgalite** [comment]
Hi everyone! 👋
Even after running `foundryup`, we are facing a similar issue.

1. Delegate call to a contract.
2. This contract uses a library and calls it.
3. The call fails inside a function for no real reason.


Logs with console logs in the lib's contract:
```
here1
prevId, 0x84d220490771467e0029e240de0505d476ffad72
nextId, 0x0000000000000000000000000000000000000000
_value, 1945575
```
 
Contract's code:
```
console.log("here1");
console.log("prevId", prevId);
console.log("nextId", nextId);
console.log("_value", _value);

 _list.accounts[_id] = Account(prevId, nextId, _value);

console.log("here2");
```

`here2` is not logged and we have these definitions:

```
struct Account {
        address prev;
        address next;
        uint256 value;
}

struct List {
        mapping(address => Account) accounts;
        address head;
        address tail;
}
```

Don't really know if it's a related issue but if yes this issue might need to be reopened... 😕

**Comment by onbjerg** [comment]
It is probably related to #1084, can you try rerunning with the version on master?

**Comment by MerlinEgalite** [comment]
Hmm `foundryup -b master` command is failing on my side 😬..

**Comment by gakonst** [comment]
@MerlinEgalite what do you mean is failing? can you share more context?

**Comment by MerlinEgalite** [comment]
Just updated my comment sorry. Perhaps I'm missing something though...

**Comment by gakonst** [comment]
This is a nightly error due to https://github.com/briansmith/ring/issues/1469. Can you set your rust toolchain to be stable by running `rustup default stable`?

**Comment by onbjerg** [comment]
Can you try the latest nightly? @MerlinEgalite

**Comment by MerlinEgalite** [comment]
Working fine @gakonst with master! 🎉

Will try with the nightly version asap @onbjerg 🙂

**Comment by MathisGD** [comment]
It works for me ! And foundry is fixed ! Thank you very much !

**Comment by onbjerg** [comment]
Awesome :smile:
