### ISSUE TITLE
Raise a warning for duplicated testcase contract name

### ISSUE THREAD

**Issue by fala13** [gakonst/foundry#1062]
### Component

Forge

### Describe the feature you would like

Currently it seems when there are testcase contracts with the same name, e.g.
`contract ContractTest is DSTest { .. }`
only one is being run with `forge test` and others are silently ignored.
Compilation warnings and errors can be seen for all testcase contracts, which adds to the confusion - they just don't run in `forge test`.

**Comment by gakonst** [comment]
i thought we had fixed this? cc @mattsse

**Comment by onbjerg** [comment]
> i thought we had fixed this? cc @mattsse

`deployable_contracts` in `MultiContractRunner` (used to figure out what contracts to deploy) is keyed by `id.slug()` which is just `{contract_name}.json:{contract_name}`. I think if we key it by `id.versioned_slug()` it should work? cc @mattsse again

**Comment by onbjerg** [comment]
Ref #392
