### ISSUE TITLE
Forge clean deletes the artifacts directory

### ISSUE THREAD

**Issue by pmdaly** [gakonst/foundry#1064]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (d4c615b 2022-03-24T01:05:20.744764+00:00)

### What command(s) is the bug in?

forge clean

### Operating System

macOS (M1)

### Describe the bug

Running forge clean should just clear the out and cache directories when default settings are used but the artifacts directory is additionally deleted.  See below
![foundry_artifact_bug](https://user-images.githubusercontent.com/8229664/160250612-91191ebe-adce-41e1-906e-08ff68db8388.jpg)

**Comment by onbjerg** [comment]
I think this is the expected behavior? cc @gakonst @mattsse
