### ISSUE TITLE
solc is reinstalled on every `forge` invokation

### ISSUE THREAD

**Issue by sblOWPCKCR** [gakonst/foundry#1069]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (b951f65 2022-03-26T00:03:59.328578+00:00)

### What command(s) is the bug in?

forge build, forge test

### Operating System

macOS (M1)

### Describe the bug

solc is reinstalled every time if >=0.8.10 is requested
Steps to reproduce:
```
/tmp ❯❯❯ mkdir 11
/tmp ❯❯❯ cd 11
/tmp/11 ❯❯❯ forge init
Initializing /private/tmp/11...
Installing ds-test in "/private/tmp/11/lib/ds-test", (url: https://github.com/dapphub/ds-test, tag: None)
    Installed ds-test
    Initialized forge project.
/tmp/11 [master|✔] ❯❯❯ forge build
[⠒] Compiling...
[⠆] Compiling 3 files with 0.8.10
Compiler run successful
/tmp/11 [master|✔] ❯❯❯ forge build
[⠒] Compiling...
No files changed, compilation skipped
```
^ so far, so good. Now, let's bump the required solc version:
```
/tmp/11 [master|✔] ❯❯❯ sed -I'' -e 's/0\.8\.10/0\.8\.11/' src/Contract.sol
/tmp/11 [master|✚1…1] ❯❯❯ forge build
[⠢] Compiling...
[⠆] installing solc version "0.8.11"
[⠔] Successfully installed solc 0.8.11
Compiler run successful
/tmp/11 [master|✚1…1] ❯❯❯ forge build
[⠢] Compiling...
[⠒] installing solc version "0.8.11"
[⠘] Successfully installed solc 0.8.11
No files changed, compilation skipped
```

Notice `installing solc version "0.8.11"` in the second `forge build`

**Comment by mattsse** [comment]
this looks like a M1 checksum error for 0.8.11 cc @roynalnaruto 
can you nuke the ~/.svm folder and try again, probably will still fail


in the meantime I think running with --offline should prevent that

**Comment by sblOWPCKCR** [comment]
> can you nuke the ~/.svm folder and try again, probably will still fail
Yup, same thing

FWIW, this is a new behavior, it worked fine ~a week ago

**Comment by mattsse** [comment]
yeah we're shipped native M1 builds now

could you please check if the installed 0.8.11 has the same sha256 checksum:

https://raw.githubusercontent.com/roynalnaruto/solc-builds/465839dcbb23fd4e60c16e8cae32513cd5627ca0/macosx/aarch64/list.json

**Comment by roynalnaruto** [comment]
@mattsse I checked the SHA256 hash of v0.8.11 uploaded to `solc-builds/macosx/aarch64` here: https://github.com/roynalnaruto/solc-builds/tree/465839dcbb23fd4e60c16e8cae32513cd5627ca0

and the hash is in fact: `5fd03cb7a9d3959ea338b8c44f14ee81151fb30b2a763b7afc30c55ad07f4fe5`

@sblOWPCKCR can you tell me the output of:
```
$ shasum -a 256 ~/.svm/0.8.11/solc-v0.8.11
```

**Comment by mattsse** [comment]
oh I have hunch what's happening, 
do we ship forge natively for aarch64 @onbjerg, don't think so? so we're embedding the wrong checksums for the static build

**Comment by roynalnaruto** [comment]
@mattsse I just initialised a new project using `forge init` with `foundryup --version nightly`.

And for solc version `0.8.11` the project does compile (with default settings)

**Comment by gakonst** [comment]
> do we ship forge natively for aarch64 @onbjerg, don't think so? so we're embedding the wrong checksums for the static build

We're using these binaries for linux aarch64 @mattsse https://github.com/nikitastupin/solc/

**Comment by gakonst** [comment]
Just tried to repro on M1 Mac after nuking ~/.svm and it worked fine..

```
➜  repro-1069 git:(master) ✗ forge b
[⠊] Compiling...
[⠒] installing solc version "0.8.10"
[⠆] Successfully installed solc 0.8.10
[⠰] Compiling 1 files with 0.8.10
Compiler run successful
➜  repro-1069 git:(master) ✗ sed -I'' -e 's/0\.8\.10/0\.8\.11/' src/Contract.sol
➜  repro-1069 git:(master) ✗ forge b
[⠊] Compiling...
[⠆] installing solc version "0.8.11"
[⠔] Successfully installed solc 0.8.11
Compiler run successful
➜  repro-1069 git:(master) ✗ forge b
[⠒] Compiling...
No files changed, compilation skipped
```

**Comment by sblOWPCKCR** [comment]
> @sblOWPCKCR can you tell me the output of:
> 
> ```
> $ shasum -a 256 ~/.svm/0.8.11/solc-v0.8.11
> ```

`~/.svm/0.8.11/solc-v0.8.11` does not exist, but there's `~/.svm/0.8.11/solc-0.8.11` (without 'v'):
```
/tmp/11 [master|✚1…1] ❯❯❯ shasum -a 256 ~/.svm/0.8.11/solc-0.8.11
5fd03cb7a9d3959ea338b8c44f14ee81151fb30b2a763b7afc30c55ad07f4fe5  /Users/owleksiy/.svm/0.8.11/solc-0.8.11
```

**Comment by gakonst** [comment]
Same here and I do not have the bug
```
shasum -a 256 ~/.svm/0.8.11/solc-0.8.11
5fd03cb7a9d3959ea338b8c44f14ee81151fb30b2a763b7afc30c55ad07f4fe5  /Users/georgios/.svm/0.8.11/solc-0.8.11
```

**Comment by benesjan** [comment]
I am experiencing the same issues on M1 mac.

The project I am working on is open source so maybe it would be useful for devs to test it on [my repository](https://github.com/benesjan/path-registry).

<img width="1064" alt="image" src="https://user-images.githubusercontent.com/13470840/160487550-bf1f11da-bac5-4138-a0d8-8043caf3f4ac.png">

**Comment by gakonst** [comment]
It works for me...

```
forge t
[⠒] Compiling...
No files changed, compilation skipped

Running 10 tests for src/test/PathRegistry.t.sol:PathRegistryTest
[PASS] testFailRegisterBrokenPathUniV2() (gas: 28678)
[PASS] testFailRegisterBrokenPathUniV3() (gas: 28613)
[FAIL. Reason: Revert] testFirstPathReplacement() (gas: 31269)
[PASS] testPathPruning() (gas: 189)
[FAIL. Reason: Revert] testRegisterPath() (gas: 28655)
[FAIL. Reason: Revert] testRegisterPathWith0Amount() (gas: 28782)
[FAIL. Reason: Revert] testSwapERC20() (gas: 28612)
[FAIL. Counterexample: calldata=0x9fd8d2920000000000000000000000000000000000000000000000000000000000000000, args=[0]] testSwapFuzz(uint96) (runs: 0)
[FAIL. Reason: Revert] testSwapMinAmountEnforced() (gas: 28679)
[FAIL. Reason: Revert] testSwapOnlyPathWithLargerAmountAvailable() (gas: 35902)
Test result: FAILED. 3 passed; 7 failed; finished in 23.55ms

Failed tests:
[FAIL. Reason: Revert] testFirstPathReplacement() (gas: 31269)
[FAIL. Reason: Revert] testRegisterPath() (gas: 28655)
[FAIL. Reason: Revert] testRegisterPathWith0Amount() (gas: 28782)
[FAIL. Reason: Revert] testSwapERC20() (gas: 28612)
[FAIL. Counterexample: calldata=0x9fd8d2920000000000000000000000000000000000000000000000000000000000000000, args=[0]] testSwapFuzz(uint96) (runs: 0)
[FAIL. Reason: Revert] testSwapMinAmountEnforced() (gas: 28679)
[FAIL. Reason: Revert] testSwapOnlyPathWithLargerAmountAvailable() (gas: 35902)

Encountered a total of 7 failing tests, 3 tests succeeded
```

**Comment by gakonst** [comment]
Just confirmed that it's present on last night's release, but not on latest master. Not sure yet which commit fixed it.

Please do `foundryup -b master` or wait for tonight's release to get the fix!

**Comment by mattsse** [comment]
if this still happens, please run with `RUST_LOG=solc`

**Comment by onbjerg** [comment]
If we believe this is fixed then let's close - feel free to ask us to reopen if the latest nightly does not fix it :smile:
