### ISSUE TITLE
forge test --debug panics with "no ABI for contract"

### ISSUE THREAD

**Issue by transmissions11** [gakonst/foundry#1084]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (865bc46 2022-03-28T00:08:15.310912+00:00)

### What command(s) is the bug in?

forge test --debug

### Operating System

macOS (M1)

### Describe the bug

running `forge test --debug` seems to panic with "no ABI for contract" for many tests i try it on

to reproduce, run `forge test --debug testWithdrawZero` in solmate

```
λ forge test --debug testWithdrawZero
[⠔] Compiling...
No files changed, compilation skipped
[⠒] Compiling...
[⠊] Compiling 12 files with 0.8.10
Compiler run successful (with warnings)
The application panicked (crashed).
Message:  no ABI for contract
Location: cli/src/cmd/forge/run.rs:96

Backtrace omitted.
Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
zsh: abort      forge test --debug testWithdrawZero
```

**Comment by onbjerg** [comment]
My bad. Think it was fixed in #1089
