### ISSUE TITLE
bug: `expectRevert` does not work for low-level calls

### ISSUE THREAD

**Issue by mds1** [gakonst/foundry#1124]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (fc85b1c 2022-03-28T17:17:55.044128+00:00)

### What command(s) is the bug in?

forge test

### Operating System

macOS (amd)

### Describe the bug

My assumption was the below behavior should work, since `expectRevert` would check the success/return data of the call, even though I'm not explicitly checking it in solidity. I'd consider this a bug, though it's possible this is the expected behavior to due how this cheat code is implemented. 

```solidity
vm.expectRevert(abi.encodeWithSelector(Unauthorized.selector));
address(contract).call(someCalldata);
```

Current workaround I'm using, suggested by @brockelmore:

```solidity
(bool ok, bytes memory ret) = address(contract).call(someCalldata);
assertTrue(!ok);
assertEq(ret, abi.encodeWithSelector(Unauthorized.selector));
```

I'm also not sure whether there's similar issues with this pattern for `expectEmit` and `expectCall`, and if there is they would not have similarly simple workarounds

**Comment by mds1** [comment]
Yea it does revert with unauthorized, let me put together a minimal example later today (sorry, will need a few hours but wanted to get the issue open)

**Comment by mds1** [comment]
@onbjerg actually was able to put this together quickly now:

```solidity
pragma solidity 0.8.13;

import "ds-test/test.sol";
import "forge-std/Vm.sol";

contract Reverter {
  error Unauthorized();

  function revertWithError() public {
    revert Unauthorized();
  }

  function dontRevert() public {
    // Do nothing.
  }
}

contract ReverterTests is DSTest {
  error Unauthorized();
  Reverter reverter;
  Vm vm = Vm(HEVM_ADDRESS);

  function setUp() public {
    reverter = new Reverter();
  }

  // Passes as expected.
  function test_expectRevert_normalCall() public {
    vm.expectRevert(abi.encodeWithSelector(Unauthorized.selector));
    reverter.revertWithError();
  }

  // Passes as expected, but this is actually a bug because we're not checking the revert condition.
  function test_expectRevert_lowLevelCall() public {
    vm.expectRevert(abi.encodeWithSelector(Unauthorized.selector));
    (bool ok, ) = address(reverter).call(abi.encode(reverter.revertWithError.selector));
    // This logs 1, indicating that forge caught the revert and changed the return value so the tests can
    // continue. If you remove the expectRevert call, the test still passes but this now logs 0 indicating
    // that expectRevert is not behaving as expected.
    emit log_named_uint("ok", ok ? 1 : 0);
  }
  
  // This passes even though I'd expect it to fail.
  function test_expectNoRevert_lowLevelCall() public {
    vm.expectRevert(abi.encodeWithSelector(Unauthorized.selector));
    address(reverter).call(abi.encode(reverter.dontRevert.selector));
  }
}
```

**Comment by onbjerg** [comment]
I'm not sure how `test_expectRevert_lowLevelCall` is a bug? The call *did* revert, checking the returned bool is up to the implementer and not generally something we can check if people did or not

**Comment by mds1** [comment]
So is the way `expectRevert` works that it hooks onto the solidity-generated checks to verify the returned bool, and that's what gets intercepted/handed?

The reason it feels like a bug is because the call did revert, whether or not we check that in solidity. And my expectation would be that the cheatcode is verifying that the next call reverted, regardless of how the return value is handled

**Comment by mds1** [comment]
> Also "If you remove the expectRevert call, the test still passes but this now logs 0 indicating that expectRevert is not behaving as expected." this indicates the opposite, no? If expectRevert did not behave as expected in this case, then it would return 0 for both cases

Yea that was confusingly worded. What I meant to convey was that the test pass/fail status is not effected by expectRevert, even though it is modifying the return value

**Comment by onbjerg** [comment]
No, we're not, but that's what I'm saying - I don't think the first one is a bug. It works as expected: you expected a revert, we caught it and altered the result so that tests can continue. If you remove `vm.expectRevert` then the call reverts, but the calling context does not, because that is how Solidity works and is not generally something we can change I think

**Comment by mds1** [comment]
> the call reverts, but the calling context does not

Got it, nice distinction here. I think this is the root of the question/issue: should expectRevert be checking that the _calling context_ reverted, or the _call itself_ reverted. My expectation as a user is that the it's the latter, but the actual behavior is the former. I can be convinced that's ok, but it does feel unintuitive and we should document that behavior in the foundry book

**Comment by onbjerg** [comment]
Essentially what you experience as a non-low-level-calling-user is:

```
vm.expectRevert()
something.call() // this reverts - ok would be 1 here normally (it does not revert), but expectRevert turns it into 0
// solidity now checks ok for you, its 0, so solidity jumps and does a revert for you
```

What you experience as a low-level-calling user is exactly the same, except the revert check is not done for you, so the calling context doesn't revert

**Comment by mds1** [comment]
Heh, yea that makes sense. I get what you mean, and maybe also am tripping up on terminology here, but either way I think we understand each other. Would adding `require(ok)` afterwards result in identical behavior between low-level calls and "normal" calls? If so, then maybe the best path forward here is leaving as-is and updating the foundry book to mention you must assert on the return status for expectRevert work as expected for low-level calls?

**Comment by onbjerg** [comment]
It would, yeah, if not that is definitely a bug. It would make sense to add some clarification in the book on this for sure

**Comment by mds1** [comment]
Just tested and that seems to be the case. Thanks for clearing up that behavior!

I'll close this and open a PR on the foundry book later, and we can continue discussing any clarifications there
