### ISSUE TITLE
Show compilation time

### ISSUE THREAD

**Issue by ecmendenhall** [gakonst/foundry#1125]
### Component

Forge

### Describe the feature you would like

Print time spent compiling, similar to test block summaries:

```
$ forge build
[⠒] Compiling...
[⠃] Compiling 35 files with 0.6.12
Compiler run successful. Finished in 782.40ms
```

### Additional context

We can add duration to [`ProjectCompileOutput`](https://github.com/gakonst/ethers-rs/blob/919a570237b0d92cfa34737d8803514caaa62612/ethers-solc/src/compile/output.rs#L17) and [`OutputDiagnostics`](https://github.com/gakonst/ethers-rs/blob/919a570237b0d92cfa34737d8803514caaa62612/ethers-solc/src/compile/output.rs#L356) in `ethers-rs`. Should we simply add this to the `ethers-rs` output message?

[TG discussion](https://t.me/foundry_rs/15349)

**Comment by onbjerg** [comment]
> (Perhaps this is a pure `ethers-rs` issue, actually)

Can be implemented by adding it to the reporter: https://github.com/gakonst/foundry/blob/master/cli/src/term.rs#L213-L258

**Comment by mattsse** [comment]
> > (Perhaps this is a pure `ethers-rs` issue, actually)
> 
> Can be implemented by adding it to the reporter: https://github.com/gakonst/foundry/blob/master/cli/src/term.rs#L213-L258 (also here https://github.com/gakonst/foundry/blob/master/cli/src/term.rs#L149-L195)

yes, best way to do this would be to create a new `std::time::Instant` before invoking solc and then including the elapsed time when calling the reporter.
the time spent in preprocessing is rather negligible and not really important so makes sense to just focus on time spent in solc

**Comment by onbjerg** [comment]
Assigned you since you seemed interested in tackling this in Telegram, let me know if I am incorrect :smile:

**Comment by mattsse** [comment]
relevant lines 

https://github.com/gakonst/ethers-rs/blob/3a653472cfb484bab7ae831ad6e3664d24b4e916/ethers-solc/src/compile/project.rs#L460-L462

https://github.com/gakonst/ethers-rs/blob/master/ethers-solc/src/compile/project.rs#L547
