### ISSUE TITLE
RPC storage cache should still be considered valid if the rpc endpoint changed

### ISSUE THREAD

**Issue by mattsse** [gakonst/foundry#1129]
### Component

Forge

### Describe the feature you would like

Rn we're invalidating the cache if the host of the rpc endpoint changes.

this can result in invalidated cache if HTTP -> WS endpoint: https://github.com/gakonst/foundry/pull/1003#issuecomment-1082471758

they should be kept in the file but not lead to invalidated cache

### Additional context

https://github.com/gakonst/foundry/blob/master/evm/src/executor/fork/cache.rs#L84

**Comment by meetmangukiya** [comment]
Maybe the cache should stay valid on the basis of chain instead of RPC

**Comment by mattsse** [comment]
> Maybe the cache should stay valid on the basis of chain instead of host. (Also, ws / http shouldn't really be considered as part of host imo)

the host is different for alchemy http/ws : 

> Aha! It's https://eth-mainnet.alchemyapi.io/v2/<...> vs wss://eth-mainnet.ws.alchemyapi.io/v2/<..>

**Comment by mattsse** [comment]
closed in #1181
