### ISSUE TITLE
foundryup: support installing specific commits

### ISSUE THREAD

**Issue by transmissions11** [gakonst/foundry#1135]
### Component

Foundryup

### Describe the feature you would like

`foundryup --commit ......` would be very useful testing out an old version of forge that is no longer kept as a nightly

would have to clone from git and build from cargo like we do for branches

### Additional context

good first issue

**Comment by dmfxyz** [comment]
Had a local solution for this. Put it up for review -- I think it addresses your need.

**Comment by transmissions11** [comment]
awesome thanks @dmfxyz!
