### ISSUE TITLE
"etch" is not working.

### ISSUE THREAD

**Issue by Nipol** [gakonst/foundry#1146]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (9ed6b88 2022-03-30T00:34:46.574409410+00:00)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

Sample.t.sol
```solidity
pragma solidity ^0.8.0;

import "ds-test/test.sol";

interface CheatCodes {
    function etch(address who, bytes calldata code) external;
}

contract SampleTest is DSTest {
    CheatCodes cheats = CheatCodes(HEVM_ADDRESS);

    function setUp() public {
        cheats.etch(address(1), abi.encode(0x600001));
    }

    function testExtCodelength() public {
        assertTrue(address(1).code.length > 0);
    }
}
```

run
```shell
forge test -vvvv -m testExtCodelength

[⠒] Compiling...
[⠘] installing solc version "0.8.13"
[⠑] Successfully installed solc 0.8.13
No files changed, compilation skipped

Running 1 test for contracts/test/Sample.t.sol:SampleTest
[FAIL] testExtCodelength() (gas: 6951)
Logs:
  Error: Assertion Failed

Traces:
  [5439] SampleTest::setUp() 
    ├─ [0] VM::etch(0x0000000000000000000000000000000000000001, 0x0000000000000000000000000000000000000000000000000000000000600001) 
    │   └─ ← ()
    └─ ← ()

  [6951] SampleTest::testExtCodelength() 
    ├─ emit log(: "Error: Assertion Failed")
    └─ ← ()

Test result: FAILED. 0 passed; 1 failed; finished in 142.88µs

Failed tests:
[FAIL] testExtCodelength() (gas: 6951)
```

When I debugged the test case that broken, the extcode was not actually positioned.
this report reason because it worked in the past 0.1 version.

**Comment by onbjerg** [comment]
Is this also the case for `address(n)` where `n > 9`? The first 9 addresses are occupied by precompiles, which I suspect is the issue

**Comment by Nipol** [comment]
> Is this also the case for `address(n)` where `n > 9`? The first 9 addresses are occupied by precompiles, which I suspect is the issue

I updated the example and tried to run it again.
```solidity
    function testExtCodelength() public {
        emit log_bytes(address(1).code);
        assertTrue(address(1).code.length > 9);
    }
```

```shell
$ forge test -vvvv -m testExtCodelength
[⠒] Compiling...
[⠘] installing solc version "0.8.13"
[⠆] Successfully installed solc 0.8.13
[⠒] Compiling 1 files with 0.8.13
Compiler run successful

Running 1 test for contracts/test/Sample.t.sol:SampleTest
[FAIL] testExtCodelength() (gas: 8721)
Logs:
  0x
  Error: Assertion Failed

Traces:
  [5479] SampleTest::setUp() 
    ├─ [0] VM::etch(0x0000000000000000000000000000000000000001, 0x0000000000000000000000000000000000000000000000000000000000600001) 
    │   └─ ← ()
    └─ ← ()

  [8721] SampleTest::testExtCodelength() 
    ├─ emit log_bytes(: 0x)
    ├─ emit log(: "Error: Assertion Failed")
    └─ ← ()

Test result: FAILED. 0 passed; 1 failed; finished in 147.08µs

Failed tests:
[FAIL] testExtCodelength() (gas: 8721)

Encountered a total of 1 failing tests, 0 tests succeeded
```

**Comment by Nipol** [comment]
> I meant e.g. `address(10)` and so on 😄

haha!! That's Right!

```solidity
    function setUp() public {
        cheats.etch(address(12), abi.encode(0x600001));
    }

    function testExtCodelength() public {
        emit log_bytes(address(12).code);
        assertTrue(address(12).code.length > 0);
    }
```

```shell
$ forge test -vvvv -m testExtCodelength
[⠊] Compiling...
[⠒] installing solc version "0.8.13"
[⠒] Successfully installed solc 0.8.13
[⠔] Compiling 1 files with 0.8.13
Compiler run successful

Running 1 test for contracts/test/Sample.t.sol:SampleTest
[PASS] testExtCodelength() (gas: 4919)
Logs:
  0x0000000000000000000000000000000000000000000000000000000000600001

Traces:
  [4919] SampleTest::testExtCodelength() 
    ├─ emit log_bytes(: 0x0000000000000000000000000000000000000000000000000000000000600001)
    └─ ← ()

Test result: ok. 1 passed; 0 failed; finished in 156.50µs
```

What should I do about this issue?
Would it be better to print a more friendly message than a call `bug`?`

**Comment by onbjerg** [comment]
For now just use addresses `address(n)` where `n > 9`, although I wonder what direction we should go here.

@gakonst It seems that REVM overwrites precompile accounts every time we call `EVM::transact`, which makes sense in the real world, but I think a lot of people use `address(n)` where `0 < n < 10` for testing. We could either disallow that (may break things) or we could figure out how to best handle this in REVM

**Comment by gakonst** [comment]
I think we should disallow `vm.etch` for addresses 0 < n < 10, and throw an error about using an address >10.

I prefer breaking these early and getting "correct" behavior vs hacking something on Revm.

**Comment by mds1** [comment]
Worth considering disallowing other cheatcodes for those addresses. It's not realistic to `prank` that address or `mockCall` with it, and you also don't want to `save` or `load` slots from there, for example.

As for what addresses to block off, to be safe we might also want to:
- Disallow a larger range, such as 0 < n < 99 to account for precompiles being added or other EVM chains that have additional precompiles
- Prevent `etch`ing at addresses that other chains have predeployed contracts at. For example Optimism has [predeployed contracts](https://github.com/ethereum-optimism/optimism/blob/0ac233e73040b372464a9f59a325217254fe8e15/packages/contracts/contracts/libraries/constants/Lib_PredeployAddresses.sol) at `0x420...000` < n < `0x420...013`, not sure about other networks offhand

**Comment by onbjerg** [comment]
Closing this in favor of #1159 since `cheats.etch` is not actually broken :smile: Thanks for the report @Nipol!
