### ISSUE TITLE
forge will install solc everytime

### ISSUE THREAD

**Issue by 0xildefonso** [gakonst/foundry#1150]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What command(s) is the bug in?

forge build

### Operating System

macOS (M1)

### Describe the bug

following [the tutorial](https://book.getfoundry.sh/projects/working-on-an-existing-project.html), however not matter how many times I've built the project, `forge` will still take time to install `solc`:

```
➜  forge-std git:(master) ✗ forge build
[⠒] Compiling...
[⠢] installing solc version "0.8.10"
[⠔] Successfully installed solc 0.8.10
No files changed, compilation skipped
➜  forge-std git:(master) ✗ forge build
[⠊] Compiling...
[⠰] installing solc version "0.8.10"
[⠑] Successfully installed solc 0.8.10
No files changed, compilation skipped
```

from my understanding `solc` should only be installed once, am I correct?

**Comment by mattsse** [comment]
thanks,
this was indeed an issue on M1 builds that has been fixed but hasn't made it in last nights nightly, should be resolved by this https://github.com/gakonst/foundry/pull/1151

In the meantime, you should be able to deactivate this by supplying the `--offline` flag

**Comment by onbjerg** [comment]
I wonder if we should close given that it will be fixed in the next nightly? :thinking:

**Comment by 0xildefonso** [comment]
> I wonder if we should close given that it will be fixed in the next nightly? 🤔

would prefer closing the issue once the nightly is out and fix is confirmed, so that other users encountering the same problem can have a better idea on the progress.

**Comment by onbjerg** [comment]
@0xildefonso It should be out now - can you check if this was fixed?

**Comment by 0xildefonso** [comment]
> @0xildefonso It should be out now - can you check if this was fixed?

yup I can confirm the issue has been fixed

```
➜  forge-std git:(master) ✗ foundryup
foundryup: installing foundry (version nightly, tag nightly-7b61e81a679e808fbe1f213486ea5051c874fba6)
...

➜  forge-std git:(master) ✗ forge build
[⠒] Compiling...
No files changed, compilation skipped
➜  forge-std git:(master) ✗ forge build
[⠒] Compiling...
No files changed, compilation skipped
```
