### ISSUE TITLE
Allow setting --rpc-url and --private-key via global config for forge and cast

### ISSUE THREAD

**Issue by daedlock** [gakonst/foundry#1160]
### Component

Forge, Cast

### Describe the feature you would like

Foundry is the missing piece in proper, high quality & productive solidity development. However, if I understand correctly. Every command that interacts with a chain requires the `--rpc-url` flag. Also, every deployment requires `--private-key`. 

## Suggestion
- Allow setting --rpc-url and --private-key globally and locally via toml profiles
  - global foundry.toml (`~/.foundry/foundry.toml`)
  - local foundry.toml 
- forge & cast to read from the first `foundry.toml` in the directory tree, fallback to global `foundry.toml` if no local config was resolved
 

### Additional context

The mentioned should allow more convinient access to forge and cast capabilities. 

eg:

```
forge create Stake.sol:Stake --profile polygon
```

Notice how the command is much shorter than it's counter-version with **--rpc-url**  and **--private-key**.

**Comment by onbjerg** [comment]
This is already possible for the RPC, but cast does not have config support yet. See https://github.com/gakonst/foundry/issues/689

**Comment by daedlock** [comment]
> Whoops, fat-fingered 😅 Do you think this issue is closeable given that it is encompassed by https://github.com/gakonst/foundry/issues/689?

Yes ser, thanks for clarifying. Closing for now
