### ISSUE TITLE
Multiline import statements are not sanitized in `forge flatten`

### ISSUE THREAD

**Issue by 0xtao** [gakonst/foundry#1164]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (233ab70 2022-04-01T00:51:18.292928+00:00)

### What command(s) is the bug in?

forge flatten

### Operating System

Windows

### Describe the bug

When I was flattening a contract, I ran into an issue where a multiline import was not removed. For example:

```
import {
    IllegalArgument,
    IllegalState,
    Unauthorized,
    UnsupportedOperation
} from "../../base/Errors.sol";
```

Is expected to be:

```
```

This issue subsequently caused a silent error when verifying the contract because the flattened code would not compile on Etherscan.

**Comment by mattsse** [comment]
thanks, this is indeed a bug.
will get this resolved

**Comment by mattsse** [comment]
@0xtao can you provide me with a minimal setup that results in this error because I couldn't reproduce it 
https://github.com/gakonst/ethers-rs/pull/1101

**Comment by mattsse** [comment]
Oh any chance you're using reverts with custom errors in that file @0xtao ?
this was just added to the solidity parser flattening relies on, this should land on master with this PR https://github.com/gakonst/foundry/pull/1180 and will then probably be resolved.

**Comment by 0xtao** [comment]
> Oh any chance you're using reverts with custom errors in that file @0xtao ? this was just added to the solidity parser flattening relies on, this should land on master with this PR #1180 and will then probably be resolved.

I am! Okay, sounds good.

**Comment by onbjerg** [comment]
Hi @0xtao, is this fixed on the latest nightly?

**Comment by 0xtao** [comment]
> Hi @0xtao, is this fixed on the latest nightly?

Yep! Closing now.
