### ISSUE TITLE
No proper interpolation with hardhat console.log

### ISSUE THREAD

**Issue by bmikaili** [gakonst/foundry#1166]
### Component

Forge

### Describe the feature you would like

Currently, when using hardhat's `console.log` within a test or a method the test calls, the output string is not properly interpolated:  ![image](https://user-images.githubusercontent.com/17531789/161266335-7c332049-7a52-4c13-9dfa-e01ad7b013b9.png)

The `%s`s should be replaced with the numerical values on the right of the log.  Someone in the support telegram mentioned it just tries to convert the `console.log` to ds-test's `log_string` event.

**Comment by onbjerg** [comment]
I don't think we've ever supported this - is it documented anywhere? I wasn't aware that `console.log` had this ability.

The conversion to `log_string` events is safe in every other case, and simplifies the code internally as well :)

**Comment by gakonst** [comment]
Yeah this wasn't supported by us before and neither does hardhat have it AFAIK.

**Comment by onbjerg** [comment]
@bmikaili Since this is not supported by Hardhat (as far as we can tell) I am going to close this issue - please ping me to have it reopened if this is something that Hardhat does in fact support :smile:

**Comment by fvictorio** [comment]
Hi folks, just letting you know that we indeed support this (documented [here](https://hardhat.org/hardhat-network/reference/#console-log), although admittedly kind of hidden):

> console.log implements the same formatting options that can be found in Node.js' [console.log (opens new window)](https://nodejs.org/dist/latest-v12.x/docs/api/console.html#console_console_log_data_args), which in turn uses util.format
