### ISSUE TITLE
`foundryup` instructions on macOS (amd) missing note to install required dependency `libusb`

### ISSUE THREAD

**Issue by jakinyele** [gakonst/foundry#1169]
### Component

Foundryup

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0

### Operating System

macOS (amd)

### Describe the bug

Got this error when installing `foundryup` via `curl -L https://foundry.paradigm.xyz | bash`:

> foundryup: downloading latest forge and cast
> ######################################################################## 100.0%
> foundryup: downloading manpages
> ######################################################################## 100.0%
> dyld: Library not loaded: /usr/local/opt/libusb/lib/libusb-1.0.0.dylib
>   Referenced from: /Users/ayo/.foundry/bin/forge
>   Reason: image not found
> foundryup: installed - 

For older versions of macOS, please consider adding required dependencies to the docs: `brew install libusb` (if Homebrew is default package manager)

**Comment by onbjerg** [comment]
It is documented here: https://github.com/gakonst/foundry#libusb-error-when-running-forgecast

Do you have any suggestions for how to improve this?

**Comment by appleseed-iii** [comment]
#1170 is a potential fix
