### ISSUE TITLE
In `testFail...`, matching failure reason is of significance.

### ISSUE THREAD

**Issue by TimDaub** [gakonst/foundry#1178]
### Component

Forge

### Describe the feature you would like

When I mark a test case as `testFail...`, I don't want it to pass on any failure. I only want it to pass if it fails on the expected e.g. `require` or with a particular message.

This is as `testFail...` test cases could in the future pass as I broke something else and so they're not making sure a formerly tested function fails upon a certain `require`.

**Comment by gakonst** [comment]
Please check the `vm.expectRevert('...')` cheatcode, this is already supported :) https://book.getfoundry.sh/reference/cheatcodes.html#expectrevert

**Comment by TimDaub** [comment]
> Please check the `vm.expectRevert('...')` cheatcode, this is already supported :) https://book.getfoundry.sh/reference/cheatcodes.html#expectrevert

FYI @gakonst this link is now ded

**Comment by mattsse** [comment]
> > Please check the `vm.expectRevert('...')` cheatcode, this is already supported :) https://book.getfoundry.sh/reference/cheatcodes.html#expectrevert
> 
> FYI @gakonst this link is now ded

it has its own dedicated page now https://book.getfoundry.sh/cheatcodes/expect-revert.html
