### ISSUE TITLE
No ABI contracts / function names shown in stacktrace

### ISSUE THREAD

**Issue by 0xmikko** [gakonst/foundry#1185]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (a279d2e 2022-04-04T00:03:20.128570951+00:00)

### What command(s) is the bug in?

forge test -vvv

### Operating System

Linux

### Describe the bug

Test package doesn't link ABI with test, so stack trace looks impossible to understand - no functions neither contracts are recognized!

![Screenshot from 2022-04-04 12-38-19](https://user-images.githubusercontent.com/26343374/161527252-03e1ab92-35f6-4210-86ee-5b0cbcd177b5.png)

**Comment by onbjerg** [comment]
I noticed you didn't check that you had updated to the latest foundry - can you try to do that? Also, do you have a reproducible example?

**Comment by 0xmikko** [comment]
The bug came after foundry update. I was on 0.1X version, then run `foundryup`, it recompile whole codebase, and then all ABI names disappeared.

**Comment by 0xmikko** [comment]
Another bug, that key `-vvv` doesn;t show stacktrace if bug happened in setup:
![Screenshot from 2022-04-04 12-55-23](https://user-images.githubusercontent.com/26343374/161529721-75425917-cb6b-45f1-8c6f-fafdb5f81cea.png)

**Comment by 0xmikko** [comment]
One thing could help you to find the bug. I cleaned `/out/` and run `forge t`, it compiled test files only, however, I could not find prohect files there. Could be an issue?

**Comment by onbjerg** [comment]
Oh. Can you try to run these:

```
curl -L https://foundry.paradigm.xyz | bash
foundryup -C 4e84ebec2f9a318fea3df3821914fe3b0bbb789d
```

(Note: Requires that you have `cargo` installed)

I suspect #978 might be at fault

**Comment by onbjerg** [comment]
> Another bug, that key `-vvv` doesn;t show stacktrace if bug happened in setup: ![Screenshot from 2022-04-04 12-55-23](https://user-images.githubusercontent.com/26343374/161529721-75425917-cb6b-45f1-8c6f-fafdb5f81cea.png)

That's not a bug - for setUp traces you need to pass `-vvvv`

**Comment by 0xmikko** [comment]
Just upgraded on my mac, have the same issue.

**Comment by onbjerg** [comment]
Can you try what I posted in https://github.com/gakonst/foundry/issues/1185#issuecomment-1087418481?

**Comment by 0xmikko** [comment]
Got:
```
Cloning into 'foundry'...
remote: Enumerating objects: 6198, done.
remote: Counting objects: 100% (1768/1768), done.
remote: Compressing objects: 100% (562/562), done.
remote: Total 6198 (delta 1345), reused 1462 (delta 1198), pack-reused 4430
Receiving objects: 100% (6198/6198), 2.99 MiB | 1.94 MiB/s, done.
Resolving deltas: 100% (3748/3748), done.
Note: switching to 'origin/master'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at a78b9a3 feat(cheatCodes): set/getNonce for an account (#1139)
foundryup: installing at commit 4e84ebec2f9a318fea3df3821914fe3b0bbb789d
Previous HEAD position was a78b9a3 feat(cheatCodes): set/getNonce for an account (#1139)
HEAD is now at 4e84ebe chore(evm): remove redundant checks (#1176)
error: failed to parse manifest at `/Users/mikhail/.foundry/gakonst/foundry/Cargo.toml`

Caused by:
  feature `strip` is required

  The package requires the Cargo feature called `strip`, but that feature is not stabilized in this version of Cargo (1.56.0 (4ed5d137b 2021-10-04)).
  Consider trying a newer version of Cargo (this may require the nightly release).
  See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#profile-strip-option for more information about the status of this feature.
foundryup: command failed: cargo install --path ./cli --bins --locked --force --root /Users/mikhail/.foundry
```

**Comment by 0xmikko** [comment]
Its on mac machine

**Comment by 0xmikko** [comment]
The same on Linux. Does it mean that 'strip' feature is missed in `Cargo.toml` located  in original repo or problem exists with my local settings?

**Comment by onbjerg** [comment]
You need to update rust, it's a new-ish feature: `rustup update`

**Comment by 0xmikko** [comment]
Thanks, @onbjerg , it solves problem with ABI, however, bug that `forge t -vvv` doesn't show stacktrace for error in setUp() is still in place. Should I open new issue?

**Comment by onbjerg** [comment]
No, as I said in https://github.com/gakonst/foundry/issues/1185#issuecomment-1087418890 it is not a bug - setUp traces are verbosity 4 and above

**Comment by onbjerg** [comment]
Hi, @0xmikko, is this issue still present on the latest nightly (run `foundryup`)?

**Comment by 0xmikko** [comment]
No, thanks. Everything works fine
