### ISSUE TITLE
Type casting on an unit256 array

### ISSUE THREAD

**Issue by bitcoinbrisbane** [gakonst/foundry#1209]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (77882ab 2022-03-22T00:12:56.848059114+00:00)

### What command(s) is the bug in?

forge build

### Operating System

Linux

## Breaks

```solidty
    function testBatchCall() public {
        // arrange
        uint256[2] memory values = [0, 0];
    }
```

Seems to try optimise and cast `0` to a `unit8`

## Works
```solidty
    function testBatchCall() public {
        // arrange
        uint256[2] memory values = [uint256(0), uint256(0)];
    }
```

**Comment by strawberry-fury** [comment]
This has nothing to do with foundry; It's a "feature" of solidity. You can put the following code in Remix:
```
pragma solidity 0.8.10;
contract Test {
    function testBatchCall() public {
        uint256[2] memory values = [0, 0];
    }
}
```
and it won't compile.

**Comment by onbjerg** [comment]
As mentioned above, not a Foundry bug :)

**Comment by bitcoinbrisbane** [comment]
@onbjerg oops!  Sorry for that and the tip!
