### ISSUE TITLE
SNAP & forge collapse

### ISSUE THREAD

**Issue by ngmisl** [gakonst/foundry#1213]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

-

### Operating System

Linux

### Describe the bug

Got SNAP installed, forge is being occupied used by `FORGE - training program for SNAP (version 2006-07-28)`

which means I basically can not run forge init

**Comment by onbjerg** [comment]
What is your proposed solution? We can't really rename our binaries

**Comment by ngmisl** [comment]
no idea, perhaps anyone has a workaround?

**Comment by onbjerg** [comment]
You could uninstall SNAP assuming you don't use it, or move the snap `forge` binary out of your path and create an alias for it, but in general this is not really a Foundry issue, so I would recommend searching around for the answer instead :) Alternatively you can ask if someone has a solution in https://t.me/foundry_support
