### ISSUE TITLE
Ability to pass "name=hexvalue" pairs on the forge command line that can then be accessed through a cheatcode

### ISSUE THREAD

**Issue by mmhh1910** [gakonst/foundry#1216]
### Component

Forge

### Describe the feature you would like

I would like to use foundry for simulation of transactions that I create in my golang backend. Currently, I use ganache for that, so I start ganache from my go code, deploy my contracts, set everything up and run the tx that I want to simulate, all through RPC.

It would be much easier to use forge for this and also, with ganache you are kind of blindfolded, while with foundry you get a nice trace and log output.
This would need the ability to parameterize a forge test run and one way would be to able to pass "name=hexvalue" on the forge command line that can then be accessed through a cheatcode.

**Comment by onbjerg** [comment]
You can use `forge run` for that, e.g. `forge run path/to/Contract.sol --sig "someFunc(uint256,uint256)" 1 2` would run `someFunc(uint256,uint256)` in `path/to/Contract.sol` with parameters 1 and 2.
