### ISSUE TITLE
`getCode` does not work

### ISSUE THREAD

**Issue by nicolasgarcia214** [gakonst/foundry#1219]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (6130af7 2022-04-07T00:03:16.450116078+00:00)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

I'm trying to replicate the `getCode.t.sol` test in a blank project initialized with forge init but it always throws the same "Reason: No such file or directory" error when running the test.

The path is fine and the file is exactly the same as the foundry [repo](https://github.com/gakonst/foundry/blob/master/testdata/fixtures/GetCode/WorkingContract.json).

![image](https://user-images.githubusercontent.com/37629288/162131345-206de71d-0e14-49e8-8171-37bbc1cf38dd.png)

```solidity
// SPDX-License-Identifier: Unlicense
pragma solidity >=0.8.0;

import "ds-test/test.sol";
import "../Cheats.sol";

contract GetCodeTest is DSTest {
    Cheats constant cheats = Cheats(HEVM_ADDRESS);

    function testGetCode() public {
        bytes memory fullPath = cheats.getCode("../WorkingContract.json");
        //bytes memory fileOnly = cheats.getCode("WorkingContract.sol");
        //bytes memory fileAndContractName = cheats.getCode("WorkingContract.sol:WorkingContract");

        string memory expected = string(bytes(hex"6080604052348015600f57600080fd5b50607c8061001e6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063d1efd30d14602d575b600080fd5b6034602a81565b60405190815260200160405180910390f3fea26469706673582212206740fcc626175d58a151da7fbfca1775ea4d3ababf7f3168347dab89488f6a4264736f6c634300080a0033"));
        assertEq(
            string(fullPath),
            expected,
            "code for full path was incorrect"
        );
    }

    function testFailGetUnlinked() public {
        cheats.getCode("UnlinkedContract.sol");
    }
}
```

**Comment by onbjerg** [comment]
I'm fairly confident that the path is supposed to be relative to the root of your project, so the path should be `./src/WorkingContract.json`

**Comment by nicolasgarcia214** [comment]
Indeed, thank u @onbjerg
