### ISSUE TITLE
Timeout on fetching solc too short

### ISSUE THREAD

**Issue by benesjan** [gakonst/foundry#1223]
### Component

Forge

### Describe the feature you would like

It would be useful to increase the timeout when downloading solc. When I am working on mobile data I am struggling with this.

<img width="680" alt="image" src="https://user-images.githubusercontent.com/13470840/162237794-3c796308-aff7-4e90-80c2-8e0c25ac01db.png">

**Comment by mattsse** [comment]
@roynalnaruto let's bump this on svm?
