### ISSUE TITLE
Wen dapptools-rs-template?

### ISSUE THREAD

**Issue by byterose** [gakonst/foundry#123]
I would love to see a [dapptools-template](https://github.com/gakonst/dapptools-template) port using dapptools-rs after the first release.

**Comment by stevennevins** [comment]
@byterose i just made a repo based on the solmate repo from rari capital.  Let me know if you get a chance to check it out https://github.com/stevennevins/dapptools.foundry

**Comment by byterose** [comment]
@stevennevins looks good, ty :)

**Comment by gakonst** [comment]
made it here https://github.com/gakonst/forge-template
