### ISSUE TITLE
`forge verify-contract` is no longer working due too metadata bytecodeHash is not set to none

### ISSUE THREAD

**Issue by pyk** [gakonst/foundry#1236]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (d513291 2022-04-07T18:27:22.910788+00:00)

### What command(s) is the bug in?

forge verify-contract

### Operating System

macOS (M1)

### Describe the bug

With recent introduction to use `bytcodeHash` as `None` by default https://github.com/gakonst/foundry/pull/1180, it breaks the `forge verify-contract`.

Etherscan uses `"bytecodeHash": "ipfs"` by default to verify the smart contract but foundry doesn't set the metadata bytecode hash to none when submitting contract verification

**Comment by onbjerg** [comment]
cc @mattsse why did we disable it in the first place? I forgot

**Comment by mattsse** [comment]
because that causes non deterministic code, see also https://github.com/Uniswap/v3-core/blob/ed88be38ab2032d82bf10ac6f8d03aa631889d48/hardhat.config.ts#L57-L62


but this is not really a verify issue since that's not included in the verify request we're sending to etherscan, right?

sounds more like we should consider making ipfs the default?

and you can adjust this in the foundry.toml

**Comment by onbjerg** [comment]
I think it is a verify issue because the metadata hash is added to the end of the bytecode

**Comment by mattsse** [comment]
but the bytecode is not part of the verify payload
 
https://docs.etherscan.io/api-endpoints/contracts#source-code-submission-gist

**Comment by pyk** [comment]
> I think it is a verify issue because the metadata hash is added to the end of the bytecode, unsure though

@onbjerg @mattsse Yes the metadata hash is appended to the bytecode, hence the contract verification is failed when `forge` submit the verification using flattened file format instead of standard-input-json. 

We can only override the metadata setting when using the `standard-input-json` format.

I have submitted PR on ethers and foundry to solve this problem https://github.com/gakonst/ethers-rs/pull/1126 https://github.com/gakonst/foundry/pull/1242

**Comment by mattsse** [comment]
ok, thanks for trying again!
I think I've found the last issue here #1278

with that fix I was able to successfully verify via cli on goerli: https://goerli.etherscan.io/address/0x2e7a3b5a0346b2b390a125c0ac8181236d19ca3c#code

sorry about all of this, working with the etherscan API is a bit hard
