### ISSUE TITLE
Support json output for forge create

### ISSUE THREAD

**Issue by dmfxyz** [gakonst/foundry#1255]
### Component

Forge

### Describe the feature you would like

I would like to be able to pass a `--json` flag to `forge create` so that the output is printed as valid json.

### Additional context

cast already has this for commands like `cast block latest` etc. It's useful for bash scripting as you can pipe the output into `jq` or the like and carry on your merry way.

If we agree this is a helpful feature, you can assign the issue to me.

**Comment by mattsse** [comment]
closed by #1256
