### ISSUE TITLE
solc corruption

### ISSUE THREAD

**Issue by odyslam** [gakonst/foundry#129]
If I disrupt solc download (e.g ctrl + c), then the installation is corrupted and no tests can run. I have to remove `~/.svm` with `rm -rf` and try again. 

It should fail gracefully, or detect the corruption on start and download again.

![image](https://user-images.githubusercontent.com/13405632/139578257-897f2d25-c523-42db-b47a-d6c91a458d27.png)

**Comment by gakonst** [comment]
Yep this is due to how SVM works under the hood, cc @roynalnaruto

**Comment by odyslam** [comment]
Fixed with https://github.com/roynalnaruto/svm-rs/pull/5
