### ISSUE TITLE
Add --watch flag to `forge test`

### ISSUE THREAD

**Issue by iainnash** [gakonst/foundry#1292]
### Component

Forge

### Describe the feature you would like

Add `--watch` flag to `forge test` and (possibly) `forge compile` to auto-rerun when files change.

This is useful since tests run quite fast and when you're working on tests they can be rerun on any save.

`https://docs.rs/inotify/latest/inotify/` exists, or perhaps there would be an integration using another command to make a simpler dependency tree. The benefit of including this within forge is mainly convenience and forge should already know all the target .sol files to watch.

This can be accomplished currently using the `entr` tool with: `find contracts -name "*.sol" | entr forge test`

**Comment by mds1** [comment]
This is already present with `forge test --watch` and `forge build --watch` (with `-w` as the shorthand) 🙂

**Comment by iainnash** [comment]
Ahh my bad, I think I need to update.
