### ISSUE TITLE
Forge create should have the option to output json

### ISSUE THREAD

**Issue by ludns** [gakonst/foundry#1296]
### Component

Forge

### Describe the feature you would like

Parsing `forge create` output is annoying when running it in a CI or in an automated way, and the format changes quite often. Having the option to output json one can parse with `jq` would be really helpful.

**Comment by tynes** [comment]
Have you seen this recent commit? https://github.com/gakonst/foundry/commit/95857c98ec26f5f1763d14548c1d041ee44b25ac

**Comment by onbjerg** [comment]
Oh right, this was fixed. Let me know if you feel like something is missing!

The format is:

```json
{
  "deployer": "0x...",
  "deployedTo": "0x...",
  "transactionHash": "0x..."
}
```
