### ISSUE TITLE
`evmodin::Message.destination` no longer exists

### ISSUE THREAD

**Issue by brockelmore** [gakonst/foundry#152]
"`evmodin::Message` does not have this field"

Since we depend on the github repo, `evmodin::Message` changed out from under us. If you update your registry you'll see the error.

Relevant link: https://github.com/vorot93/evmodin/blob/767c310aba2e9f8e303af852915ae7a3afc010a2/src/common.rs#L170-L200

**Comment by brockelmore** [comment]
Wait this is weird. `cargo install --path ./dapptools --all-features` reports this error but `cargo build --all-features --all` does not

**Comment by gakonst** [comment]
closed in #163
