### ISSUE TITLE
good auto config options

### ISSUE THREAD

**Issue by gakonst** [gakonst/foundry#155]
look for
* [x] requirements.txt (https://github.com/gakonst/foundry/pull/181)
* [ ] .dapprc
* [ ] .forgerc

under:
* the current directory
* `$HOME/`
* `$HOME/.foundry`
* `$HOME/.config/foundry`

**Comment by odyslam** [comment]
Coming back to this, after banging my head against the wall for a few hours, I think its impossible to export the env variables, as `source` et al. work for the subshell. 

How about we use the `dotenv` crate, or simply parse the files?

**Comment by gakonst** [comment]
Parsing the files is a no-go because if there's any bash inside (eg an if/else) we wouldn't be able to process it.

Is there no way to export the vars to the parent shell?

**Comment by odyslam** [comment]
@gakonst this was posted before our 1-1. Will explore https://github.com/sagiegurari/run_script and report back

**Comment by sambacha** [comment]
why not use something like [direnv](https://github.com/direnv/direnv)

direnv is not loading the `.envrc` into the current shell. It's creating a new bash sub-process to load the stdlib (, direnvrc and .envrc, and only exports the environment diff back to the original shell. This allows direnv to record the environment changes accurately and also work with all sorts of shells and load whatever configuration 

another alternative maybe using something like [Justfile](https://github.com/casey/just#dotenv-integration).

**Comment by odyslam** [comment]
@sambacha -- thanks for the ideas! Actually, that's what we ended up doing, but it became messier than we wanted, so we might not do it altogether and focus on:
- better opinionated zero-config approach
- deploy scripts with a new declarative language
- a native forge.toml

You can take a look at my pr in #190

**Comment by mattsse** [comment]
Closed #297 
`foundry.toml` with .dapprc env var support
