### ISSUE TITLE
native solc bindings

### ISSUE THREAD

**Issue by gakonst** [gakonst/foundry#18]
right now we use https://github.com/roynalnaruto/svm-rs/ and call out to the binary: https://github.com/gakonst/dapptools-rs/blob/f9cde71d7eaf115f624974d533bd347b8e959d59/dapp/src/solc.rs#L62

prelim benchmarks are promising:
https://forum.openzeppelin.com/t/a-faster-solidity-compiler-cli-in-rust/2546

https://github.com/axic/solc-rust
https://github.com/spalladino/solc-rs

![image](https://user-images.githubusercontent.com/17802178/134079214-bae2fdf6-a2e6-45a7-a02b-2aed8c052e5a.png)

**Comment by SamWilsn** [comment]
I pointed this out in the chat, but would like to repeat it here just in case.

Solidity and its library are released under the GPL, so if we link against it directly, we'd also need to be GPL'd.

https://github.com/ethereum/solidity/blob/develop/LICENSE.txt

**Comment by gakonst** [comment]
closing as i doubt we'll go for this anytime soon, calling solc is fast enough already
