### ISSUE TITLE
Tests aren't recompiled when one of their imports changes

### ISSUE THREAD

**Issue by jparklev** [gakonst/foundry#188]
# The Problem

When running tests using `forge test`, an update to the contracts imported by the tests doesn't trigger recompilations for the tests. For example, if we have a test file `test.t.sol`:

```solidity
import { Lad } from "../Lad.sol";
...
function testLad() public { assertEq(lad.flip(), 123); }
...
```

Then we update the implementation of `lad.flip()` to return `321` rather than `123`, the tests still pass on the next `forge test` since the `test.t.sol` didn't recompile. Changing anything in the test file triggers a recompilation and then the tests fail as expected.

# Possible Solution

My understanding is that this has to do with the way `ethers-rs` is caching and deciding when a file needs to be recompiled. A solution might be invalidate cached files if a) their source has changed, or b) the source of any of their imports has changed. I could be missing something about what ethers is doing atm, though. Haven't gotten into that src much yet.

Also lemme know if you'd like to push this issue over the the ethers repo for better tracking.

**Comment by mattsse** [comment]
this is definitely an ethers-solc issue, and you're probably right with your diagnosis.
I assume the following is happening, during compilation we're mostly concerned with src contracts and not necessarily test contracts so that test files aren't properly checked for changes if the src contract is unchanged when we construct the dependency tree from the src contract's pov.

**Comment by mattsse** [comment]
there were some ethers-solc changes yesterday that are already included on foundry master, so just to clarify this happens with the current master as well @jparklev ?

**Comment by jparklev** [comment]
Actually I think i'm behind by a day or two, let me try with the latest @mattsse

**Comment by jparklev** [comment]
> there were some ethers-solc changes yesterday that are already included on foundry master, so just to clarify this happens with the current master as well @jparklev ?

Confirmed on the current master 👍

**Comment by gakonst** [comment]
fixed in https://github.com/gakonst/foundry/commit/0527eb95ce9c17101b434a0626ba3861836c0a9e / https://github.com/gakonst/ethers-rs/pull/634, closing optimistically, please re-open if still a problem
