### ISSUE TITLE
benchmarks against other clients

### ISSUE THREAD

**Issue by gakonst** [gakonst/foundry#19]
alternatives:
* hardhat
* truffle
* upstream dapptools

metrics:
* compilation time
* unit tests time
* symbolic tests time & memory usage

**Comment by transmissions11** [comment]
rpc testing time would be an important one too (hevm is much worse than hardhat atm)

**Comment by gakonst** [comment]
benchmark here https://github.com/mds1/convex-shutdown-simulation
