### ISSUE TITLE
Solidity Error keyword not compatible with Foundry.

### ISSUE THREAD

**Issue by 0xrebased** [gakonst/foundry#214]
Dec 11 18:10:36.087 ERROR forge: error=unknown variant `error`, expected one of `constructor`, `function`, `event`, `fallback`, `receive` at line 1 column 246
Error: unknown variant `error`, expected one of `constructor`, `function`, `event`, `fallback`, `receive` at line 1 column 246

Location:
    /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/result.rs:1915:27
    
    
    
![image](https://user-images.githubusercontent.com/93690142/145697770-6e383381-a51e-4f0b-913d-8acf4097ee0e.png)

**Comment by 0xrebased** [comment]
Note aside: Error message stating what solidity file the issue is in would be nice!

Cheers
-b

**Comment by 0xrebased** [comment]
Edit: Appears that the error keyword is completely incompatible with foundry.

**Comment by mattsse** [comment]
error support was in ethabi was merged yesterday https://github.com/rust-ethereum/ethabi/pull/251
I think we can perhaps patch that for the time being

**Comment by gakonst** [comment]
Pinged the maintainers to release https://github.com/rust-ethereum/ethabi/issues/252

**Comment by 0xrebased** [comment]
Awesome, thanks to both of you!

**Comment by mattsse** [comment]
this should be fixed now, since #238 
vot close

**Comment by 0xrebased** [comment]
thanks @mattsse
