### ISSUE TITLE
Improve node-modules auto-detection

### ISSUE THREAD

**Issue by gakonst** [gakonst/foundry#221]
As found by @reem https://github.com/reem/forge-node-modules-repro, we currently do not nicely auto-detect the node modules folder or the remappings. It could make sense for us to "guide" the searcher in some way, because otherwise scanning through the node_modules/ directory takes too long.

**Comment by mattsse** [comment]
currently, if node_modules is set as library location we recursively check all lib folders for remappings in `Remapping::findmany`, 
we could either put some restrictions in place for `find_many` (depth 2 for example would look for `node_modules/<depth 1>/remappings.txt`) or blacklist node_modules entirely by default

**Comment by mattsse** [comment]
vote close, 

@reem take a look at #263, should work now and much! faster
