### ISSUE TITLE
Support library linking 

### ISSUE THREAD

**Issue by gakonst** [gakonst/foundry#222]
If we want to support dss' [spells-mainnet](https://github.com/makerdao/spells-mainnet), we'll need to support lib linking.

# Problem
1. We call into_inner here: https://github.com/gakonst/foundry/blob/master/forge/src/multi_runner.rs#L61
2. Then we call `into_bytes`: and then https://github.com/gakonst/ethers-rs/blob/4c677933ce4407fb1307f9077aefc31b9e811cdb/ethers-solc/src/config.rs#L260
3. But `into_bytes` returns `None` for unlinked objects
4. So we'll need to somehow call [`link`](https://github.com/gakonst/ethers-rs/blob/master/ethers-solc/src/artifacts.rs#L778) before doing the deployment step.

# Suggested Solution

1. We should provide a manual way for somebody to link to an already deployed library
2. We should auto-detect if there's library dependencies, deploy all the libraries first, get their addresses, and then link them in all the bytecodes necessary.

**Comment by lucas-manuel** [comment]
Can be closed I believe now @gakonst

**Comment by gakonst** [comment]
Re-opening as we still do not support
> We should auto-detect if there's library dependencies, deploy all the libraries first, get their addresses, and then link them in all the bytecodes necessary.

**Comment by dcposch** [comment]
as a short term fix, i wouldn't have been stuck on #487 if there was a good error message

if the error said 

> library Endian has public functions, specify deployed address

i would've figured out the issue.

more importantly, though: `forge test` **succeeded** for me -- appeared to finish successfully -- even though no tests were actually run. this is a scary failure mode. git commit to reproduce linked in #487

**Comment by gakonst** [comment]
Both points are spot on, 1) if we don't support it for a while we should have a warning. Not sure if we can detect that a contract is a library just by having the ABI? cc @mattsse on this. 2) Yeah agreed on it being a scary failure mode.
