### ISSUE TITLE
State doesn't reset correctly in between test contracts

### ISSUE THREAD

**Issue by brockelmore** [gakonst/foundry#225]
run multiple contract tests: https://github.com/gakonst/foundry/blob/e0d6fff9bd51b4bf769d001f854b19805c150c00/forge/src/multi_runner.rs#L136-L144

set init_state: https://github.com/gakonst/foundry/blob/e0d6fff9bd51b4bf769d001f854b19805c150c00/forge/src/runner.rs#L111

reset state before each test: https://github.com/gakonst/foundry/blob/e0d6fff9bd51b4bf769d001f854b19805c150c00/forge/src/runner.rs#L119

The issue arises between test contract 0 -> test contract 1.

contract 0:
  set init_state as correct init state
  run tests with good init state
  NO reset state

contract 1:
  set new init state *WHICH IS POST test contract 0 state
  run tests with bad init state
  No reset state

So the last call of each test contract will affect the next test contract's state

**Comment by gakonst** [comment]
Closing cautiously since #226 got merged, let's re-open with a test case if we find this to persist
