### ISSUE TITLE
Make Regex pattern optional for tests

### ISSUE THREAD

**Issue by mattsse** [gakonst/foundry#227]
Currently the `pattern` argument is by default an all matching regex 

https://github.com/gakonst/foundry/blob/e1b44087fa4dc2ad74371eb5b217d83b55608c47/cli/src/cmd/test.rs#L34-L40

this gets passed down to the test runners who use it filter test by names, this could be made an option instead.

perhaps the testrunner could instead accept something like `impl Into<Filter>`

```rust
struct Filter {
   pattern: Option<Regex>
   // --snip maybe there is a future use case to add additional attributes?
}

impl Filter {
  fn matches(&self, test_name: &str) -> bool;
}
```

**Comment by jparklev** [comment]
Not sure how idiosyncratic it is, but i'd also find it helpful to set a regex that filters tests _out_. My use case is filtering mainnet fork test out when running local-only tests (rn i'm prefixing those tests with `testMainnet**`, which I can negative match already, but it's not the nicest)

**Comment by gakonst** [comment]
I'd be supportive of making the regex more expressive, another idea would be to regex on contract names as well (instead of just function names).

**Comment by gakonst** [comment]
I'd be supportive of making the regex more expressive, another idea would be to regex on contract names as well (instead of just function names).

**Comment by lattejed** [comment]
I'm going to tackle this if no one else is on it

I'll look at including @jparklev & @gakonst 's suggestions.

**Comment by gakonst** [comment]
Sounds great! I don't think anyone else is working on it.

**Comment by lattejed** [comment]
Looking at how to extend the interface to handle the proposed changes. Some thoughts:

Rust regexes don't have negative lookaheads, so there's no (easy?) way to use part of a name as an inverse match, which means inverse filters have to be explicit.

Also, filtering both contract names and test fn names with the same pattern seems problematic, so `--match` should likely be split into a set of new flags.

From the Rust eco, `cargo test` has `--bin`, `--test` flags, etc. They don't really match up to what's being done here (no patterns, no inverse), but I guess it can be argued that a set of flags is Rusty.

MochaJS, which is arguably the most used framework in the most used language, uses sth like `--filter` along with `--inverse`, e.g., `--filter foo --inverse` to exclude `foo` tests. Personally I don't like it.

Probably the way to go is:

`--match-test`
`--match-contract`

Could then alias and deprecate `--match` to `--match-test` so there are no breaking changes. 

But filters need to be explicitly negated, so probably:

`--match-test`
`--no-match-test`
`--match-contract`
`--no-match-contract`

Or

`--include-test`
`--exclude-test`
`--include-contract`
`--exclude-contract`

The impl would effectively AND these together so using `--include-contract Foo --exclude-contract FooBaz --include-test bar` would run the `bar` fns for `Foo` but not `FooBaz`. 

The only alternative I can think of to keep a single `--match` flag would be to have some sort of custom annotated regex as input, but I can't imagine a scenario where that wouldn't be awful. 

I'm a little *cough* rusty after an extended break so I might be overlooking sth obvious here. Feedback / input is appreciated.

**Comment by lattejed** [comment]
@gakonst Just wanted to make sure you saw this -- though happy to get input from anyone

**Comment by gakonst** [comment]
+1 on match-test / match-contract, and no disagreement on the negative regex matching.

**Comment by lattejed** [comment]
This is now PR #388 

Any / all input welcome

**Comment by jparklev** [comment]
This is perfect and immediately useful. ty @lattejed

**Comment by gakonst** [comment]
Indeed, very high ROI PR
