### ISSUE TITLE
leave git alone in forge init

### ISSUE THREAD

**Issue by moodysalem** [gakonst/foundry#231]
don't like that it messes with my commits in an existing repo

**Comment by mattsse** [comment]
I guess we should 
- [ ] check instead if the target path is already inside a git,
- [ ] consider removing the auto "init commit" here and leave the files untracked instead
https://github.com/gakonst/foundry/blob/0bd43bcbdf54d3ff8b05bd051e7a29fab906b019/cli/src/forge.rs#L114-L120

**Comment by gakonst** [comment]
Can maybe add a `--no-git` or `--no-commit` flag (open to ideas) so that it can be disabled? Or we disable it by default? I was just copying over the logic from dapptools.

**Comment by moodysalem** [comment]
imo disable by default, `npm init`, `create-react-app`, [`mvn archetype:generate`](https://maven.apache.org/guides/getting-started/maven-in-five-minutes.html#creating-a-project), etc. do not usually do stuff with commit history, although it seems like submodules are part of the dependency management strategy for this tool

you might want to be unopinionated on dependency management instead?

**Comment by gakonst** [comment]
@transmissions11 over DMs:
> I like Matt's idea. still do dapp init sty;e by default but if already in git try to be as hands off as possible

**Comment by jerry-best** [comment]
I'm generally in favor of defaulting to no git interaction, at least when inside an existing repo. I'm using forge inside a larger git repo, and at the moment I've resorted to deleting `.git` and `.gitmodules` after doing `forge init`, but then I have to `touch .git` just to get `forge test` to work when I want to run it.

I'm also subverting the use of submodules for the contents of `lib` and just directly committed the contents of `lib` to the larger containing git repo, but that's not a principled stance, just me lazily dealing with the fact that `forge install` didn't play nice with my containing repo when creating submodules, and I don't really care if the upstream changes in this case. Also, I'd just as soon not deal with git submodules unless I need them.

**Comment by mattsse** [comment]
I'd also lean in favor of not committing in `forge init` since it's not necessary because you can also recreate that state with forge init again.

**Comment by gakonst** [comment]
closed in #252
