### ISSUE TITLE
import node_modules path error

### ISSUE THREAD

**Issue by 0xinugami** [gakonst/foundry#232]
Command ran
`RUST_LOG=ethers=trace forge test --hardhat`

Code
`import { SafeMath } from "@openzeppelin/contracts/math/SafeMath.sol";`

Error
```
ParserError: Source "/users/inugami/dev/project/node_modules/@openzeppelin/contracts/contracts/math/SafeMath.sol" not found: File not found.
      import { SafeMath } from "@openzeppelin/contracts/math/SafeMath.sol";
```

Seems like the path is not being parsed correctly. Should be `@openzeppelin/contracts/math/SafeMath.sol` and not `@openzeppelin/contracts/contracts/math/SafeMath.sol`. 

Can I get some help please?

**Comment by gakonst** [comment]
I believe the right way to import is `import { SafeMath } from "@openzeppelin/math/SafeMath.sol";`?

**Comment by 0xinugami** [comment]
`@openzeppelin/math/SafeMath.sol` works for me. Thanks for helping. Going to require quite a few changes to migrate from hardhat and jest testing.

**Comment by gakonst** [comment]
You can also declare remappings manually like so: openzeppelin/=lib/openzeppelin-contracts/

That way you won't need to change anything. Closing as the question is  answered.
