### ISSUE TITLE
`forge run`

### ISSUE THREAD

**Issue by odyslam** [gakonst/foundry#234]
`forge run` would run a solidity file without having to set up a project for it. It would prob need work on the packaged libraries front, where a number of libraries are natively offered by forge (e.g ds-test, vm.sol, console.sol).

**Comment by gakonst** [comment]
Could see this being `forge run Foo.sol` and it'd default to calling `run()` on the specified contract, or you'd do `forge run Foo.sol myFunction(uint256) 2` and it'd call `myFunction` with `2` as the argument.

**Comment by transmissions11** [comment]
i like option #2 @gakonst, maybe with a default of run()?

**Comment by gakonst** [comment]
Yeah sorry that's what I meant, it'd be the latter with default to the former.

**Comment by gakonst** [comment]
ref [#234](https://github.com/gakonst/foundry/issues/165) since it'd benefit from stdlib

**Comment by wilsoncusack** [comment]
Working on this. @gakonst trying to figure out best way to load the file. Ideally cli just takes a `--path` argument, but the analogous code I can find only takes a `root`. https://github.com/gakonst/foundry/blob/master/cli/src/cmd/build.rs#L212-L213

**Comment by gakonst** [comment]
Yeah doing it the same way as `--root` but calling it `--path` sounds good to me.

**Comment by gakonst** [comment]
Right, we might need to hack on `ethers-solc` a bit to have both auto-detection of solidity version and the ability to provide single files. Take a look at ethers-solc `Solc` struct (instead of `Project`), maybe it makes your life easier.

**Comment by wilsoncusack** [comment]
ok cool yeah, was just pulling up https://docs.rs/ethers/latest/ethers/solc/struct.ProjectPathsConfig.html, checking out Project as well

**Comment by wilsoncusack** [comment]
looks like compile_with_version could help us, https://docs.rs/ethers-solc/0.1.2/src/ethers_solc/lib.rs.html#251-255, but then do we need to read the pragma from the file, or pass as an arg?

**Comment by wilsoncusack** [comment]
@gakonst wondering how much we can/should rely on remapping. The idea is that this should be able to be run outside a forge project, right? Maybe first pass just has hard settings for EVMVersion etc.

**Comment by gakonst** [comment]
I think let's go with no remappings initially, just assume everything is self contained in a single file? And we can augment this feature when we have progress on the #165

**Comment by odyslam** [comment]
Should we close this issue @gakonst
