### ISSUE TITLE
structured stack & call traces

### ISSUE THREAD

**Issue by gakonst** [gakonst/foundry#24]
dapptools / hardhat-style tracing are extremely good. [evmodin](https://github.com/vorot93/evmodin) has utilities for that natively with its interrupts API and there's open PRs to do that in [sputnik ](https://github.com/rust-blockchain/evm/pull/25)

dapptools trace is just too good to not have:
![image](https://user-images.githubusercontent.com/17802178/134082047-d903e161-c0a8-47c7-a157-c582e1795493.png)

**Comment by transmissions11** [comment]
brownie traces are also pretty insane:

![image](https://user-images.githubusercontent.com/26209401/134089793-4aebd89b-5e5d-4bbb-a224-05a50edce34d.png)

**Comment by lucas-manuel** [comment]
I like that gas tracking in the brownie logs 👀

**Comment by brockelmore** [comment]
Addressing in call tracing pr #192

**Comment by lucas-manuel** [comment]
I think this can be closed now since @brockelmore's PR right @gakonst?
