### ISSUE TITLE
feat: `foundry update` to easily switch between versions

### ISSUE THREAD

**Issue by mds1** [gakonst/foundry#241]
Behavior would be analogous to [duppgrade](https://github.com/Rari-Capital/duppgrade), such as:

- `foundry update` to install latest main in this repo
- `foundry update <tag/branch/commit>` to install specified commit in this repo
- `foundry update <repo-path>` to install latest main in specified repo
 `foundry update <repo-path>  <tag/branch/commit>` to install specified commit in specified repo

**Comment by transmissions11** [comment]
made an intermediate solution: https://github.com/transmissions11/forgeup

**Comment by gakonst** [comment]
Forgeup now in the readme https://github.com/gakonst/foundry/commit/57733a4906bd7edd7f8469cd0ed890dcf7a14680

**Comment by onbjerg** [comment]
Should close this now that we upstreamed `foundryup`

**Comment by gakonst** [comment]
Yep good call. Godmode work @transmissions11, now in https://github.com/gakonst/foundry/tree/master/foundryup
