### ISSUE TITLE
feat(prank): startPrank/stopPrank

### ISSUE THREAD

**Issue by transmissions11** [gakonst/foundry#247]
would be dope to have a start and stop prank cheatcode that would allow impersonating an account over multiple txs so users won't have to repeat themselves before each

**Comment by brockelmore** [comment]
The only difficult part here is making it such that internal calls of the first call don't inherit the wrong msg.sender as well. Should the test contract basically *always* be that new address? i.e. Test::test -> other::something -> Test::otherFunc -> other::something2

should the Test::otherFunc -> other::something2 call also be pranked?

**Comment by gakonst** [comment]
I'd only go for the first call's level, and not for every subsequent internal call
