### ISSUE TITLE
`forge`'s `DAPP_TEST_ADDRESS` == `dapp`'s `DAPP_TEST_CALLER` 

### ISSUE THREAD

**Issue by brockelmore** [gakonst/foundry#253]
Related to #249, `forge`'s `DAPP_TEST_ADDRESS` is really `dapp`'s `DAPP_TEST_ORIGIN`/`DAPP_TEST_CALLER`. `dapp`'s `DAPP_TEST_ADDRESS` is the address of the *test contract* not the caller.

Likely the fix for #249 should include this fix as well

**Comment by gakonst** [comment]
@onbjerg confirming that this is correct to be closed right?

**Comment by onbjerg** [comment]
Yes, this is correct
