### ISSUE TITLE
Consider adding features to support deploying several contracts from a file

### ISSUE THREAD

**Issue by wilsoncusack** [gakonst/foundry#259]
A common hardhat workflow of mine is to have a deploy script, which can be quite complex. Sometimes I am working on a project that requires deploying several contracts, with the deployed address of one being an input to another. Other times, it is not just deploying, but making calls to these contracts after deploying them, to seed a certain state for some client testing I might be doing. 

Currently Foundry has no way to support this workflow, aside from maybe a bash script using `cli/create`.

However, I am not sure how interested Foundry is in trying to solve this problem.

**Comment by wilsoncusack** [comment]
The solution here might just be a Rust lib for convenience methods for deploying / making contract calls? I assuming that is already covered in what Foundry has right now, so maybe just a matter of putting an example together?

**Comment by gakonst** [comment]
You could use ethers' [`ContractFactory`](https://docs.rs/ethers/latest/ethers/contract/struct.ContractFactory.html)!

**Comment by wilsoncusack** [comment]
> You could use ethers' [`ContractFactory`](https://docs.rs/ethers/latest/ethers/contract/struct.ContractFactory.html)! [Here's](https://github.com/gakonst/ethers-rs/blob/master/examples/contract_with_abi.rs#L37-L41) an example

nice! this looks great.
