### ISSUE TITLE
Default to use SOLC_PATH, then SVM, then solc

### ISSUE THREAD

**Issue by wilsoncusack** [gakonst/foundry#267]
Re discussion in Telegram <img width="459" alt="Screen Shot 2021-12-19 at 8 22 42 PM" src="https://user-images.githubusercontent.com/6678357/146702764-1f537375-a6ab-488b-98d6-0ff4384f5b03.png">

Currently in order to run offline, passing `--no-auto-detect`, you have to have solc installed. Forge should probably prefer to use svm, which is installed with Forge, or else use SOLC_PATH as a first resort.

**Comment by mattsse** [comment]
thanks,
this has been merged already https://github.com/gakonst/ethers-rs/pull/709
