### ISSUE TITLE
Improve error messages if you forget `setup` function in test contract

### ISSUE THREAD

**Issue by wilsoncusack** [gakonst/foundry#268]
```
contract Foo {

    function bar() public returns (uint256) {

    }
}


contract FooTest {
    Foo foo;
    
    function testBar() public {
        foo.bar();
    }    
}
```
This code produces this error message.
<img width="683" alt="Screen Shot 2021-12-19 at 8 49 41 PM" src="https://user-images.githubusercontent.com/6678357/146704826-fb1ce48b-54ff-4294-bb10-60f398d79545.png">

Possibly could have a special parsing for test contracts to make sure they implement `setup`

**Comment by wilsoncusack** [comment]
Or maybe some error if a contract is at address(0)? Not actually sure how the compiler sees it, without the setup

**Comment by brockelmore** [comment]
This is failing because you never create the foo contract, not that there isn't a setup call

**Comment by wilsoncusack** [comment]
> This is failing because you never create the foo contract, not that there isn't a setup call

Hi, thanks yes I understand why it's happening 😀. Sorry if that wasn't clear. 

Just thought, given how key `setup` is to the way the testing works, and that I expect this to be a somewhat common error for n00bs, it might be worth a better error message. But maybe not worth deviating from standard Solidity behavior/errors.

**Comment by gakonst** [comment]
@brockelmore I guess one option is that we could throw an error if there's no constructor and `setUp` function present?

Alternatively, this is basic enough that we can solve it with a note in our documentation?

**Comment by wilsoncusack** [comment]
Also, just got bitten that it has to be `setUp` not `setup` 😀

**Comment by wilsoncusack** [comment]
@gakonst should I close or is there a useful TODO here?

**Comment by gakonst** [comment]
Yeah I think that's fine, and we can add in the docs if more ppl stumble in this.
