### ISSUE TITLE
Print revert message for fuzzed tests

### ISSUE THREAD

**Issue by wilsoncusack** [gakonst/foundry#269]
Currently, non-fuzzed tests correctly print the revert message, but fuzzed tests do not.

```
contract Foo {
    function bar() public returns (uint256) {
        require(false, "hey");
    }
}


contract FooTest {
    Foo foo;
    
    function setUp() public {
        foo = new Foo();
    }

    function testBar() public {
        foo.bar();
    }   

    function testBarFuzzed(uint256 x) public {
        foo.bar();
    }   
}
```
<img width="783" alt="Screen Shot 2021-12-19 at 8 53 19 PM" src="https://user-images.githubusercontent.com/6678357/146705120-357ca0a7-045b-4ec6-b10c-c90812fe211a.png">

**Comment by wilsoncusack** [comment]
@gakonst ideas on where to start poking here? Would be nice if I could first write a test case showing this fails.

**Comment by rajivpo** [comment]
It looks like [`call_raw`](https://github.com/gakonst/foundry/blob/045fc35751d84591c79c453d8a76f3fd41aaf96a/evm-adapters/src/evmodin.rs#L124) returns the status code which is getting passed as the [`return_reason`](https://github.com/gakonst/foundry/blob/045fc35751d84591c79c453d8a76f3fd41aaf96a/evm-adapters/src/fuzz.rs#L80-L89).  In [`call`](https://github.com/gakonst/foundry/blob/045fc35751d84591c79c453d8a76f3fd41aaf96a/evm-adapters/src/lib.rs#L76-L93), there is an explicit check for a failure status which if satisfied, decodes the revert message. 

A quick fix could be to employ a similar scheme inside of https://github.com/gakonst/foundry/blob/045fc35751d84591c79c453d8a76f3fd41aaf96a/evm-adapters/src/fuzz.rs#L80-L109 for cases when `success` is `false`

**Comment by gakonst** [comment]
I'm on this^
