### ISSUE TITLE
expectRevert does not fail test if no contract call is made

### ISSUE THREAD

**Issue by wilsoncusack** [gakonst/foundry#270]
If no contract call is made after calling `expectRevert`, the test passes, which does not seem like correct expected behavior. 

```
interface Vm {
    function expectRevert(bytes calldata) external;
}

contract Foo {
}

contract FooTest {
    Vm vm = Vm(0x7109709ECfa91a80626fF3989D68f67F5b1DD12D);
    Foo foo;
    
    function setUp() public {
        foo = new Foo();
    }

    function testBar() public {
        vm.expectRevert("message");
    }
}
```

**Comment by brockelmore** [comment]
Nice catch. Easiest fix is probably in `run_test` in `runner.rs` is to check after calling the test if there is a remaining `expected_revert` in `self.evm.state()` I believe.

**Comment by gakonst** [comment]
Yeah check `if self.evm.state().expected_revert.is_some()` after the test has ended, and return error if it's `Some`.

**Comment by transmissions11** [comment]
lemme give fixing this a shot

**Comment by wilsoncusack** [comment]
wanted to give a try as well, just to learn, put an attempt up here - https://github.com/gakonst/foundry/pull/274.

**Comment by gakonst** [comment]
Shipped - ideally let's avoid duplication of work across issues! Thanks both!

**Comment by wilsoncusack** [comment]
My bad! Sorry @transmissions11 just wanted to see if I could figure out, then kept getting fixes to make :)
