### ISSUE TITLE
Release on crates.io missing

### ISSUE THREAD

**Issue by quambene** [gakonst/foundry#272]
Is there a specific reason that foundry is not published on crates.io yet (https://doc.rust-lang.org/cargo/reference/publishing.html)? Would be great for visibility.

**Comment by mattsse** [comment]
rn foundry relies on the latest master of [ether-rs](https://github.com/gakonst/ethers-rs) especially for all solc related features, since there are quite a few changes.
expect this to be available on crates, once ethers-solc is more stabilized and battle tested.

**Comment by quambene** [comment]
Thanks for clarifying. Feel free to close this issue or keep it open.

**Comment by gakonst** [comment]
Closing to keep things clean, we're still rapidly iterating so not worth publishing yet, but it's in our plans.
