### ISSUE TITLE
Inconsistent remapping detection

### ISSUE THREAD

**Issue by alcibiadeseth** [gakonst/foundry#283]
```
➜ forge remappings --lib-paths lib/
ds-test/=lib/ds-test/src/
standards/=lib/standards/src/
src/=lib/openzeppelin/src/
➜  ls lib
ds-test/src      openzeppelin/src standards/src    uniswapv2/src
```

Given multiple folders structured as dapptools libraries in lib/, `forge` only detects some, and of those, names some incorrectly.

**Comment by mattsse** [comment]
just to confirm, this happens with `master`?

**Comment by alcibiadeseth** [comment]
I just pulled a fresh install with `cargo install --git https://github.com/gakonst/foundry --bin forge --locked` and can reproduce.

**Comment by mattsse** [comment]
I see, could you attach `ls lib/**/*.sol`?

**Comment by alcibiadeseth** [comment]
Sure, any openzeppelin interface works `lib/openzeppelin/interfaces/IERC1155.sol` for example.

**Comment by alcibiadeseth** [comment]
Here are the [libraries](https://gateway.pinata.cloud/ipfs/QmUZ2cJWgMPrx1MQbX9BEbnWw5XUn5KJ4yaXPZdM5wXdS1).

**Comment by mattsse** [comment]
Thanks,

oh ofc, I forgot to account for `interfaces` folders, guess I'll rewrite the remappings detection again. This turned out to be quite tricky actually, because we're trying to make this work with dapptools and node_modules deps a like.
By now I should have a better picture of possible edge cases to make this robust.

**Comment by gakonst** [comment]
good catch - thank you @alcibiadeseth. 

remappings detection that's robust across dir structures has indeed been tricky, hopefully we'll get to something robust soon..

**Comment by alcibiadeseth** [comment]
Thanks, as always, guys. I'm always mind blown how quickly you guys respond to my QA issues :) cheers!

**Comment by alcibiadeseth** [comment]
I am going to close this given the new readme and ability to detect remappings installed in that way.
