### ISSUE TITLE
add foundry.toml configuration

### ISSUE THREAD

**Issue by mattsse** [gakonst/foundry#291]
rn some settings can be configured via env vars (see dapp tools env vars, .dapprc)

to make migrating as painless as possible, there should be a `forge config {init, migrate}` command to create the default toml file or migrate from .dapprc (as much as possible, since .dapprc is a script, focus is on all key-value settings)

This will not be limited to critical settings, like endpoint etc, but should also provide a way to configure something like color output eventually.
Some settings, therefore are intended to apply globally. To support that we could support a global config file at `~/foundry.toml` and one in a project as well, which "inherits" from that global one

This requires clear priorities for determining the final "Config":

global vars > repository config > global config

**Comment by onbjerg** [comment]
How do you envision the migrate command should work/what are constraints on the migrator since `.dapprc` is essentially just a shell script?

**Comment by mattsse** [comment]
have a look at https://github.com/gakonst/foundry/pull/297 README.md

the easiest would be to use already set env vars when populating the `Config` type.
so after `source .dapprc` we can merge the vars:
https://github.com/gakonst/foundry/blob/aee88f9451c2c66c3b1e50b08976295e32bb2c8b/config/src/lib.rs#L229-L233

if we add `.merge(Env::prefixed("DAPP_").global())`

but this only works for vars, there's no alternative solution to .dapprc functions.

**Comment by gakonst** [comment]
Minor point that `source .dapprc` would need to happen outside of the migrate command, since it proved to be quite hard to run a shell script and get its outputs https://github.com/gakonst/foundry/pull/190
