### ISSUE TITLE
Forge Test cache

### ISSUE THREAD

**Issue by crisgarner** [gakonst/foundry#299]
If a test passes and the code of the contract is changed, the test keeps using a cache version not reflecting the changes. Current small fix is doing small changes to the test code to refresh the cache.

Seems like an issue related to ethers-solc

**Comment by dimitri0101** [comment]
Hello, I have seen too. Any idea for fix @gakonst ?

**Comment by mattsse** [comment]
thanks @crisgarner @dimitri0101 for this, can you link me to a repo where I can reproduce this.

> If a test passes and the code of the contract is changed, the test keeps using a cache version not reflecting the changes.

Is this a test contract that is stored outside of the `./contracts` or `./src` directory, in `./tests` maybe?

> Current small fix is doing small changes to the test code to refresh the cache.

This is a contract in  `./contracts` or `./src`, right?

**Comment by onbjerg** [comment]
Do we still have this bug @mattsse? I can't seem to repro

**Comment by mattsse** [comment]
that's very outdated and no longer an issue, closing
