### ISSUE TITLE
Gas from traces does not match test gas 

### ISSUE THREAD

**Issue by wilsoncusack** [gakonst/foundry#300]
<img width="280" alt="Screen Shot 2021-12-23 at 7 03 20 PM" src="https://user-images.githubusercontent.com/6678357/147303489-96f37491-0a48-4770-a2f0-ab420d6df050.png">
<img width="265" alt="Screen Shot 2021-12-23 at 7 03 29 PM" src="https://user-images.githubusercontent.com/6678357/147303497-fd578481-d304-4db1-93f2-a3a63f87a7df.png">

**Comment by wilsoncusack** [comment]
<img width="506" alt="Screen Shot 2021-12-23 at 7 19 07 PM" src="https://user-images.githubusercontent.com/6678357/147304213-4a9de89b-b4a7-41c1-9921-3f4f507a238d.png">
FWIW this function shows as ~10k more expensive using hardhat-gas-reporter. Should maybe open a separate issue for this.

**Comment by transmissions11** [comment]
think the hardhat gas counter stuff is cuz of initial call gas and refund accounting?

**Comment by wilsoncusack** [comment]
>  think the hardhat gas counter stuff is cuz of initial call gas and refund accounting? 

Ah ok. Have heard this a couple times but don't totally understand. Are you suggesting the hardhat gas is too high, compared to what you'd see on chain, and the forge is correct?

**Comment by onbjerg** [comment]
I think they match. If you count up the gas cost of some subtraces and add them up, and then compare it to the parent trace's gas cost, there might be a small-ish discrepancy. This discrepancy is most likely the `CALL` opcode itself + some other logic in that function that is not captured by a subtrace (i.e. ifs, arithmetic etc.).

Not sure how else we can verify other than literally just deploying something I suppose and check the gas cost. Any insight on this @transmissions11? If you have deployed something with Foundry, do the gas costs line up?

**Comment by brockelmore** [comment]
Closing, this was fixed in #524
