### ISSUE TITLE
forge: error=missing field `bytecode`

### ISSUE THREAD

**Issue by odd-amphora** [gakonst/foundry#301]
We are trying to setup foundry to implement integration tests for the [juicebox](https://juicebox.money) v2 protocol ([repo](https://github.com/jbx-protocol/juice-contracts-v2)) – if you are curious, I am currently working off of the `infra/foundry` branch. After setting up the CLI and trying to build the contracts, I am left with this error. Any idea what could be causing this? Running with:

 ```
 forge build --contracts ./contracts --remappings @chainlink/=node_modules/@chainlink/ --remappings @openzeppelin/=node_modules/@openzeppelin/ --remappings @paulrberg/=node_modules/@paulrberg/ --remappings prb-math/=node_modules/prb-math/
 ```

**Comment by odyslam** [comment]
I encountered the same error but I was unable to isolate it. Very interesting.

**Comment by odyslam** [comment]
@odd-amphora Can you please verify with another tool that you are not encountering a "stack too deep" error?

**Comment by mattsse** [comment]
I tracked this down to this function `JBETHPaymentTerminalStore.recordPaymentFrom`:

https://github.com/jbx-protocol/juice-contracts-v2/blob/f83ccef5d09fa541d49455e5bbe66d5323815812/contracts/JBETHPaymentTerminalStore.sol#L224

If you add the `--optimize` flag it should compile successfully:

`forge build --contracts ./contracts --remappings @chainlink/=node_modules/@chainlink/ @openzeppelin/=node_modules/@openzeppelin/ @paulrberg/=node_modules/@paulrberg/ prb-math/=node_modules/prb-math/ --optimize`

Interestingly solc does not provide an error in via the standard json interface in this case...
hardhat seems to catch this error if the optimizer is disabled:

```console
CompilerError: Stack too deep, try removing local variables.
   --> contracts/JBETHPaymentTerminalStore.sol:243:10:
    |
243 |         (_preferClaimedTokensAndBeneficiary & 1) == 0,
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


Error HH600: Compilation failed
```

**Comment by drgorillamd** [comment]
> I tracked this down to this function `JBETHPaymentTerminalStore.recordPaymentFrom`:
> 
> https://github.com/jbx-protocol/juice-contracts-v2/blob/f83ccef5d09fa541d49455e5bbe66d5323815812/contracts/JBETHPaymentTerminalStore.sol#L224
> 
> If you add the `--optimize` flag it should compile successfully:
> 
> `forge build --contracts ./contracts --remappings @chainlink/=node_modules/@chainlink/ @openzeppelin/=node_modules/@openzeppelin/ @paulrberg/=node_modules/@paulrberg/ prb-math/=node_modules/prb-math/ --optimize`
> 
> Interestingly solc does not provide an error in via the standard json interface in this case... hardhat seems to catch this error if the optimizer is disabled:
> 
> ```
> CompilerError: Stack too deep, try removing local variables.
>    --> contracts/JBETHPaymentTerminalStore.sol:243:10:
>     |
> 243 |         (_preferClaimedTokensAndBeneficiary & 1) == 0,
>     |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> 
> Error HH600: Compilation failed
> ```

the `--optimize` flag didn't fix it on my end (but I could successfully compile by saving one variable declaration / hardhat without optimization isn't complaining of the stack depth anymore).
Is it perhaps an unexpected result from optimize ? Should I open a new issue for this ?
