### ISSUE TITLE
`forge build` suppresses solc suggestion

### ISSUE THREAD

**Issue by odyslam** [gakonst/foundry#304]
version: latest as of today

![telegram-cloud-photo-size-4-5922373204259747940-y](https://user-images.githubusercontent.com/13405632/147366566-395e9f2f-1ff8-43ef-9983-e29f21fa25ff.jpg)

**Comment by odyslam** [comment]
Another example:
![image](https://user-images.githubusercontent.com/13405632/147557379-439b28a1-3be4-4330-b8f9-6f0e28e917fe.png)

**Comment by onbjerg** [comment]
Needs additional checks here 

https://github.com/gakonst/foundry/blob/cb279a21b562df7f57b5880584c722d77b93018c/cli/src/cmd/mod.rs#L45-L56

when https://github.com/gakonst/ethers-rs/pull/772 is merged. Alternatively we can just spit out `output` directly and bail if compilation fails with an error. Thoughts @gakonst?

**Comment by gakonst** [comment]
The PR is merged. I'd Err towards keeping control of the compiler output as much as possible, as we want to also do error code filtering in the future so we silence certain warnings.
