### ISSUE TITLE
expect emit 

### ISSUE THREAD

**Issue by wilsoncusack** [gakonst/foundry#310]
In tests, be able to expect that an event is emitted with particular parameter values.

**Comment by brockelmore** [comment]
```solidity
//    check matching topic0,topic1,topic2,topic3,data
vm.expectEmit(true, false, false, false, true); 
emit Transfer(0, 1337, 1337);
erc20.transfer(to, 1337);
```

Where we do an expectEmit, passing in whether we check matching for the topics and data we want (i.e. in the above we check topic0 (event sig), and the data (1337), but not topic 1 (the from address) or topic 2 (the to address)).
