### ISSUE TITLE
`forge clean` does not remove out folder

### ISSUE THREAD

**Issue by ncitron** [gakonst/foundry#322]
It appears that `forge clean` only deletes the contents of the cache folder but not the out folder.

**Comment by gakonst** [comment]
ACK, I have reproduced this - investigating

**Comment by mattsse** [comment]
The issue is that 

https://github.com/gakonst/foundry/blob/e70361c470cac8518943d1c1516295c895a2b402/cli/src/forge.rs#L127

falls back to hardhat style layout so it checks for `artifacts`.

I guess this should autodetect, same the `build` command currently does.

**Comment by gakonst** [comment]
The `out` folder seems to get deleted now properly, but the `cache` is still left around.

**Comment by mattsse** [comment]
@onbjerg the tests indicate that clean works as expected

https://github.com/gakonst/foundry/blob/940c9421bb6d62e0e8974bf4ce01addc26e95b76/cli/tests/cmd.rs#L14-L37

or is this still an issue?

**Comment by onbjerg** [comment]
It did not remove the `cache` folder as per https://github.com/gakonst/foundry/issues/322#issuecomment-1007390750 but it should next time we bump ethers

**Comment by mattsse** [comment]
ah I see, 
ref https://github.com/gakonst/ethers-rs/pull/820#issuecomment-1017506699

I wonder if the ideal behavior would be to delete the actual cache folder if the cache file is the only file?

**Comment by onbjerg** [comment]
Yeah, I guess it would be. I was unaware that the cache was a single file :smile:

**Comment by gakonst** [comment]
Yeah let's go with that suggestion @mattsse
