### ISSUE TITLE
feat(forge): `expectEmit` support for multiple logs

### ISSUE THREAD

**Issue by mds1** [gakonst/foundry#327]
In #310 a cheat code will be added for testing that a single event is emitted. To keep the first iteration simple it'll work as described in that issue and only test for one instance of the specified event.

It would be useful to add a second definition of `expectEmit` with one additional argument which specifies the number of expected logs emitted. This is useful for cases where:
1. you have identical logs emitted within the same transaction, e.g. batch token transfers, and
2. you just want to check a log was emitted `n` times but don't need to test the actual values emitted

**Comment by wilsoncusack** [comment]
Also makes me wonder how the expect emit will behave when  multiple _different_ events are emitted from the same call. I guess might have to test them in separate tests? Which is OK. Even with hardhat you can't expect two different events to be emitted.

**Comment by brockelmore** [comment]
We do support multiple logs but not an arbitrary `n` of the same type. For now you could do:
```solidity
for (uint256 i = 0; i < n; i++) {
    vm.expectEmit(false, false, false, false);
    emit Transfer(address(this), address(this), 0);
}
batch.doTransfers();
```

**Comment by mds1** [comment]
Ah nice workaround! And of course you could extend that by defining some arrays and indexing into them if you need to test more specific parameters in each loop iteration. That's arguably a good enough workaround to backlog or even close this issue

**Comment by brockelmore** [comment]
closing as this keeps the api of the cheatcodes cleaner
