### ISSUE TITLE
feat: `cast wallet`

### ISSUE THREAD

**Issue by gakonst** [gakonst/foundry#333]
We should add some wallet management commands:
1. `cast wallet new`: Creates a new random keypair, outputs it in some format (maybe directly to stdout, maybe encrypted json keystore)
2. `cast wallet address`: Given a private key it converts it to an address
3. `cast wallet sign`: Given a private key and a message it signs the message (or its hash maybe prefixed with eth signed message?)
4. `cast wallet verify`: Given an address/pubkey, a message and a signature it verifies the signature on the message is indeed by the provided address

What else?

All of the tools required for this are in the ethers-signers package, and it's mostly about exposing them over the CLI: https://github.com/gakonst/ethers-rs/tree/master/ethers-signers.

**Comment by wilsoncusack** [comment]
Vanity? :) 

Thinking if I add we should do multi threaded, but not sure exactly how we want to do it. Re just picking a number of threads or having it passed or something else

**Comment by gakonst** [comment]
Yep also that `cast wallet new --vanity` could be a param

**Comment by rkrasiuk** [comment]
@gakonst is anybody currently working on this feature? if not, I'd be glad to pick it up

**Comment by gakonst** [comment]
I don't think so! Go for it!

**Comment by wilsoncusack** [comment]
Nice work! should we close @rkrasiuk ?

**Comment by rkrasiuk** [comment]
@wilsoncusack thanks. you can close it, i've got another PR incoming, hopefully, tomorrow with vanity address generation

**Comment by wilsoncusack** [comment]
@rkrasiuk great! Here's a gist, incase it's helpful https://gist.github.com/wilsoncusack/9a818806572170f973208b97c7cf9236

**Comment by rkrasiuk** [comment]
great, thanks! will take a look shortly

**Comment by wilsoncusack** [comment]
is p simple, was mainly using as an excuse to get familiar with rust. But maybe useful!
