### ISSUE TITLE
feat: `cast` erc20 / erc721 aliases

### ISSUE THREAD

**Issue by gakonst** [gakonst/foundry#334]
Right now, to transfer tokens you need to do `cast send "transfer(address,uint256)" ...`.

This is a bit unhandy, when we could have aliases to these commands for easier access.

**Comment by joshieDo** [comment]
We could expand it by using the primitives from https://github.com/gakonst/foundry/issues/331.

`cast send transfer 0x123...123 12 CONTRACT_ADDRESS`

1. Gets the contract ABI from etherscan:
    1. Find the function signature with the name `transfer`.
    2. Match cli arguments to the function arguments
2. If the contract is not verified, then try to build the function signature from the name + the data types given by `into_tokens()`. Or even taking a few reasonable guesses (`uint` is more used than `int`, and so on). (Could even bruteforce the function signature given the names and arguments lol)

`cast send transfer(address,uint256) 0x123...123 12 CONTRACT_ADDRESS`

Current behaviour. Could be distinguished just by the presence of `(` in the first argument.

**Comment by ncitron** [comment]
I'd like to give this a shot using @joshieDo's method.

I think the flow would end up looking like this:
1. Fetch ABI from etherscan
2. Match provided function name to a function from the ABI
        i. If there are multiple overloaded functions with the same name, attempt to match using number of arguments and implied argument types. If multiple functions still match, enter into an "interactive" mode that allows the user to select from a list of function signatures.
3. Generate signature from the ABI for the matched function and send the tx just like `cast send`

**Comment by gakonst** [comment]
#390 I think satisfies this well enough, the biggest pain was the full signature, writing the name should be sufficient. Closing, unless anybody feels like we should alias more aggressively.
