### ISSUE TITLE
Dapp debug

### ISSUE THREAD

**Issue by odyslam** [gakonst/foundry#34]
Implement a debug feature where the user can go through the smart contract, Opcode by Opcode. 

- OG HEVM debugger: https://github.com/dapphub/dapptools/blob/master/src/hevm/README.md
- Remix debugger: https://remix-ide.readthedocs.io/en/latest/debugger.html

**Comment by guanqun** [comment]
Do we prefer TUI or GUI?

**Comment by onbjerg** [comment]
We should be able to close this? I *think* we have the same caps as the HEVM debugger, but there is room for improvement 😄

**Comment by gakonst** [comment]
Yep - closing since #920 and #356
