### ISSUE TITLE
Fuzzing with uints smaller than `uint256` includes max-value + 1 as fuzzed value

### ISSUE THREAD

**Issue by LHerskind** [gakonst/foundry#341]
When fuzzing with a `uint` smaller than `uint256`, the fuzzer seems to also include the `2**size` value, meaning that tests as below will return a counter-example with `type(uint40).max + 1 = 2**40 = 1099511627776` as input. The same test in DappTools runs as expected, with no counter examples. Similar is the case for `uint248` etc.

```solidity
function test_limits(uint40 a) public {
    assertLe(a, type(uint40).max);
}
```

**Comment by gakonst** [comment]
Ah this seems to be happening because of [this](https://github.com/gakonst/foundry/blob/master/evm-adapters/src/fuzz.rs#L244-L266):

```
3..=4 => any::<u32>().prop_map(|x| x.into_token()).boxed(),
            5..=8 => any::<u64>().prop_map(|x| x.into_token()).boxed(),
            9..=16 => any::<u128>().prop_map(|x| x.into_token()).boxed(),
            17..=32 => any::<[u8; 32]>().prop_map(|x| U256::from(&x).into_token()).boxed(),
```

So `uint40` falls in the `5..=8` branch but uses `u64` as its values, which may result in a larger raw value than 2**40.

Should we be doing `5 => any::<u64>().prop_map(|x| (x % 2 ** 40).into_token()).boxed()` instead?

I would've expected that Solidity generates code that masks out any hex data that maps to >=2**40 here?

**Comment by mds1** [comment]
> I would've expected that Solidity generates code that masks out any hex data that maps to >=2**40 here?

Yea, I'm surprised this failure case happens, I'd expect it to wrap the number to the correct range or revert with an out of bounds error. Maybe a bug somewhere? Probably worth investigating this

> Should we be doing `5 => any::<u64>().prop_map(|x| (x % 2 ** 40).into_token()).boxed()` instead?

This will introduce a modulo bias where values of `0–2e29` are twice as likely to occur than values from `2e29–type(uint40).max` (the severity of the bias will of course changes as the values change). There's two better approaches you could use here:
- The simplest approach—which minimizes, but doesn't remove, modulo bias—is to always generate the random number from the largest available range (uint256) and wrap it to the provided uint size with `x % 2 ** n`.
- To remove all bias you'd want to use rejection sampling and re-sample when out of range. Good article [here](https://research.kudelskisecurity.com/2020/07/28/the-definitive-guide-to-modulo-bias-and-how-to-avoid-it/) with sample code and info on how to minimize the number of rejections
