### ISSUE TITLE
cast --from-wei and --to-wei should assume unit is eth

### ISSUE THREAD

**Issue by danrobinson** [gakonst/foundry#346]
`cast --from-wei` assumes the user wants the result in wei, which is an unintuitive default target unit (and contradicts the description in the usage message ("convert wei into an ETH amount").

`seth` (despite [saying otherwise in its documentation](https://github.com/dapphub/dapptools/tree/master/src/seth#seth---from-wei)) defaults to eth as the target unit, which is more intuitive.

```
> seth --from-wei 10
.000000000000000010
> cast --from-wei 10
10
```

`--to-wei` assumes the source unit is wei, which is also unintuitive and contradicts the usage message ("convert an ETH amount into wei"), although it is consistent with how `seth --to-wei` behaves.

**Comment by gakonst** [comment]
For context, I thought that it was OK to diverge from seth / default to `wei` in the PR which introduced this, https://github.com/gakonst/foundry/pull/261, but seems like it might've been more unintuitive.
