### ISSUE TITLE
ParserError: Source .. not found: File outside of allowed directories (Windows)

### ISSUE THREAD

**Issue by zerosnacks** [gakonst/foundry#360]
When I `forge build` or `forge test` on a clean `forge init` I am faced with the following error:

```sh
$ forge build
compiling...
Error:
   0:
      ParserError: Source "//?/C:/Users/foo Bar/Projects/zerosnacks/vault/lib/ds-test/src/test.sol" not found: File outside of allowed directories.
       --> \\?\C:\Users\foo Bar\Projects\zerosnacks\vault\src\test\Contract.t.sol:4:1:
        |
      4 | import "ds-test/test.sol";
        | ^^^^^^^^^^^^^^^^^^^^^^^^^^


   0:

Location:
   cli\src\cmd\mod.rs:49

Backtrace omitted.
Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

`foo Bar` being a replacement of my actual username which has a space in it.

I suspect this being an issue with `solc` as the `File outside allowed directories` has been reported there too.

To my knowledge this happens to me on Windows ~and Mac~.

**Comment by gakonst** [comment]
Can you do `forge test --root .`?

**Comment by zerosnacks** [comment]
I've just re-tested in on Mac and it works 👍 

On Windows I do have the issue, even when running with `forge test --root .`

In `.gitmodules` it registers the submodule as `lib\\ds-test`. From the error it appears that it can find the file but it is not allowed to access it for some reason.

**Comment by gakonst** [comment]
Hmm this is a weird [submodule bug](https://www.deployhq.com/support/common-repository-errors/no-url-found-for-submodule#:~:text=This%20occurs%20when%20the%20repository,the%20repository%20you%20are%20using.), not exactly sure what's causing it.

We're literally running Git commands [here](https://github.com/gakonst/foundry/blob/master/cli/src/forge.rs#L142-L175) so i'd have expected this to work cross-platform

**Comment by mattsse** [comment]
this is again a canon path issue:

> Initializing \\?\C:\Users\foo Bar\Projects\zerosnacks\vault...

need to replace all `.canonicalize` calls with `dunce::canonicalize`

**Comment by zerosnacks** [comment]
> this is again a canon path issue:
> 
> > Initializing \?\C:\Users\foo Bar\Projects\zerosnacks\vault...
> 
> need to replace all `.canonicalize` calls with `dunce::canonicalize`

Hi @mattsse, in an attempt to narrow down the cause I implemented this in https://github.com/zerosnacks/foundry/tree/zerosnacks/windows-path-bug

On its own it does not appear to solve the issue. I think the root cause is the something in the path construction of the automatic remapping.

When manually overriding the remapping all works great (build and test). This is both with the latest version on `master` as well as my fork.

```make
# include .env file and export its env vars
# (-include to ignore error if it does not exist)
-include .env

# Tasks
build:; forge build --optimize-runs 99999 --remappings $(call remappings)
test:; forge test --remappings $(call remappings)

# Remappings
define remappings
ds-test/=lib/ds-test/src/
endef
```

The result of running `forge remappings` outputs:

```sh
$ forge remappings
ds-test/=\\?\C:\Users\foo Bar\Projects\zerosnacks\foobar\lib\ds-test\src/
```

Which is incorrect.

**Comment by mattsse** [comment]
thanks for looking into this

I believe it is this line
https://github.com/gakonst/foundry/blob/f48e76ed4e1406ac25ac8eec0e87feab505e6f2f/cli/src/forge.rs#L57

there is some funny business going on with canonicalize on windows that's why the `dunce` crate exists
https://crates.io/crates/dunce

so if you'd like to submit a fix then we need
* `cargo add dunce` in the `cli` folder
* replace `let root = std::fs::canonicalize(root)?;` with `let root = dunce::canonicalize(root)?;`

while you're at it you could check for more usages of `std::fs::canonicalize` cc #378
