### ISSUE TITLE
Add `--flashbots` flag for frontrunning protection to `cast send`

### ISSUE THREAD

**Issue by gakonst** [gakonst/foundry#368]
Submit transactions as bundles using https://github.com/onbjerg/ethers-flashbots/ and a `--flashbots` flag. 

Here's an example of how I used this in the past: 
* https://github.com/gakonst/opensea-rs/blob/master/opensea-cli/src/contracts.rs#L131-L135
* https://github.com/gakonst/opensea-rs/blob/master/opensea-cli/src/contracts.rs#L299-L320

Alternatively we could use the Flashbots RPC: https://docs.flashbots.net/flashbots-protect/rpc/quick-start/

**Comment by odyslam** [comment]
There is also the rpc endpoint with bundle support that is being shipped as we speak: https://github.com/flashbots/docs/pull/230/files
