### ISSUE TITLE
[Bug] Hardhat console not logging Ints

### ISSUE THREAD

**Issue by FrankieIsLost** [gakonst/foundry#373]
There is an issue with calls to `console.logInt()` not logging. You can find a failing test case at https://github.com/gakonst/foundry/pull/372

**Comment by gakonst** [comment]
@mattsse did we miss a function selector in the patching logic?

**Comment by mattsse** [comment]
> @mattsse did we miss a function selector in the patching logic?

yeah I used selector(logInt(int)) as patch, but it should be just `log(int)`
fixed in #372 already

**Comment by mattsse** [comment]
vote close @gakonst

**Comment by gakonst** [comment]
yessir
