### ISSUE TITLE
Checksum not found error

### ISSUE THREAD

**Issue by hexLancel** [gakonst/foundry#379]
I've recently started getting this error when trying to use Forge to test my contracts

Not sure if something changed.

I'm currenly using a mac with an apple silicon

I've tried using cargo 1.57 and a nightly 1.59 build

```
forge test --root contracts/
compiling...
The application panicked (crashed).
Message:  checksum not found
Location: /Users/myUser/.cargo/git/checkouts/ethers-rs-c3a7c0a0ae0fe6be/c6b51e3/ethers-solc/src/compile.rs:289


  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 7 frames hidden ⋮                               
   8: core::panicking::panic_display::h7ac310de566c1365
      at <unknown source file>:<unknown line>
   9: core::option::expect_failed::h3fe074af6280676a
      at <unknown source file>:<unknown line>
  10: ethers_solc::Project<Artifacts>::svm_compile::hca9f861ffa250a02
      at <unknown source file>:<unknown line>
  11: ethers_solc::Project<Artifacts>::compile::h0cd8936986bbeff8
      at <unknown source file>:<unknown line>
  12: forge::cmd::test::test::hf4811bab9c73c9b9
      at <unknown source file>:<unknown line>
  13: <forge::cmd::test::TestArgs as forge::cmd::Cmd>::run::he81e44062c1fddb2
      at <unknown source file>:<unknown line>
  14: forge::main::h852c0a21b9755528
      at <unknown source file>:<unknown line>
  15: std::sys_common::backtrace::__rust_begin_short_backtrace::h819037cb2e1f4c28
      at <unknown source file>:<unknown line>
  16: _main<unknown>
      at <unknown source file>:<unknown line>
```

**Comment by mattsse** [comment]
This is addressed here, https://github.com/gakonst/ethers-rs/pull/759
basically what happened is `https://binaries.soliditylang.org` went down and this is a side effect from that, however once the domain is reachable again this should be resolved automatically

**Comment by hexLancel** [comment]
That worked to run the tests I have already compiled. 

Thanks

**Comment by gakonst** [comment]
Should be fixed on latest master now that the above PR is merged and ethers-rs is updated! Thanks for reporting, this was a bit unfortunate of a bug.

**Comment by PatrickAlphaC** [comment]
I'm getting this too. Running with `forge build --no-auto-detect` worked for me.

Looks like the https://binaries.soliditylang.org/ site is up, though.
