### ISSUE TITLE
bug: tests doesn't run when a test file imports a solidity library

### ISSUE THREAD

**Issue by alephao** [gakonst/foundry#384]
Hello I've been trying to run tests for a solidity library but it seems like all tests in a file are ignored if a library is imported in that file.

Here is a repo reproducing the issue: https://github.com/alephao/forgery-lib-test-issue

1. Clone
2. Run `forge test`

Expected: Tests on `MyLib.t.sol` would run
Actual: Tests doesn't run

**Comment by gakonst** [comment]
Try changing the library function from public to internal!

**Comment by alephao** [comment]
Oh, missed that, works ok using `internal` thanks!
