### ISSUE TITLE
forge: storage slot retrieval errors

### ISSUE THREAD

**Issue by naszam** [gakonst/foundry#385]
Hi @gakonst,

I was running `forge` against https://github.com/makerdao/spells-mainnet/pull/213 via:
`make test-forge`
using:
- hardhat mainnet fork pinned at block n. `13779177` (deployed spell block)

and I'm getting the following failures:
```haskell
./test-dssspell-forge.sh 
compiling...
success.
Running 13 tests for DssSpellTest
[FAIL. Reason: ] testCastCost() (gas: 73435)
[PASS] testFailTooEarly() (gas: 3580)
[PASS] testFailTooLate() (gas: 3591)
[PASS] testFailWrongDay() (gas: 3614)
[PASS] testFail_notScheduled() (gas: 7225)
[FAIL. Reason: ] testOnTime() (gas: 73392)
[FAIL. Reason: ] testSpellIsCast_GENERAL() (gas: 2859664)
[FAIL. Reason: ] testVestTransfer() (gas: 92795)
[FAIL. Reason: ] test_auth() (gas: 73454)
[FAIL. Reason: ] test_auth_in_sources() (gas: 73455)
[PASS] test_bytecode_matches() (gas: 2783386)
[FAIL. Reason: ] test_nextCastTime() (gas: 73955)
[FAIL. Reason: ] test_use_eta() (gas: 73956)

Failure: testCastCost()


[20770927] DssSpellTest::setUp()
  ├─ → new DssExec@0x6898…e52f
  │   ├─ → new DssSpellAction@0x000a…d9b9
  │   │   └─ ← 9851 bytes of code
  │   ├─ [2569] 0xda0a…740f::21f8a721(4d43445f50415553450000000000000000000000000000000000000000000000)
  │   │   └─ ← 0x000000000000000000000000be286431454714f511008713973d3b053a2d38f3
  │   └─ ← 3543 bytes of code
  └─ ← ()
  ```
  also, noticed the following errors in the hardhat trace as well:
  ```haskell
  eth_getTransactionCount
eth_getCode
eth_getStorageAt

  Errors encountered in param 1: Invalid value "0x000000000000000000000000000000000000000000000000000000000000001a" supplied to : QUANTITY

eth_getBalance
eth_getTransactionCount
eth_getCode
eth_getStorageAt
```

I've tried to reproduce via `dapp` and the tests pass via:
`make test`
- opts off (commenting `test-dssspell.sh` L6-L7)

```haskell
dapp-test: rpc block: latest
Running 13 tests for src/DssSpell.t.sol:DssSpellTest
[PASS] testFail_notScheduled() (gas: 7161)
[PASS] test_auth_in_sources() (gas: 281473904699493)
[PASS] test_use_eta() (gas: 326798)
[PASS] testOnTime() (gas: 2688502)
[PASS] testVestTransfer() (gas: 4063768)
[PASS] test_nextCastTime() (gas: 327693)
[PASS] testFailTooEarly() (gas: 3528)
[PASS] test_bytecode_matches() (gas: 2783322)
[PASS] test_auth() (gas: 281473910475780)
[PASS] testSpellIsCast_GENERAL() (gas: 11536781)
[PASS] testFailWrongDay() (gas: 3550)
[PASS] testCastCost() (gas: 2690091)
[PASS] testFailTooLate() (gas: 3527)
```

Forge: `forgeup` to master branch
Dapp: 0.35.0
Hevm: 0.49.0

Any idea?
Thanks!

**Comment by gakonst** [comment]
Can you re-run the same test with `RUST_LOG=ethers=trace`? This should log all ethers requests/responses, and then we should grep through them to understand what request is being generated that causes this error.

**Comment by naszam** [comment]
I've just run `forgeup` again and put the logs here:
https://gist.github.com/naszam/fd2d22db9f31a3ed7ce422792192af2c

**Comment by naszam** [comment]
If I run:
`make test-forge | grep 0x000000000000000000000000000000000000000000000000000000000000001a`
I get:
```haskell
Jan 05 22:37:08.281 TRACE rpc{method="eth_getStorageAt" params="[\"0xbd770416a3345f91e4b34576cb804a576fa48eb1\",\"0x000000000000000000000000000000000000000000000000000000000000001a\",\"latest\"]"}: ethers_providers::provider: tx
Error: 
   0: Encountered a total of 8 failing tests, 5 tests succeeded

Location:
   cli/src/cmd/test.rs:150

Backtrace omitted.
Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
make: *** [Makefile:7: test-forge] Error 1
```

**Comment by brockelmore** [comment]
Could this be a hardhat bug? Seems like hardhat just refused to hand back a value from it's forked state. The input parameters seems valid for the eth_getStorageAt. Is there a reason you can't use built-in forking capability (i.e. cumbersome to increment blocks)?

**Comment by gakonst** [comment]
Good point @brockelmore, I wonder if this bug still persists if @naszam used a remote node directly.

I believe Dapptools users use hardhat's forking mode to leverage the caching, to improve the forking speed.

**Comment by brockelmore** [comment]
i can try to reproduce it without hardhat

**Comment by brockelmore** [comment]
```bash
forge test --fork-url "$ETH_RPC_URL" --fork-block-number 13779177 --libraries "src/DssSpell.sol:DssExecLib:0xfD88CeE74f7D78697775aBDAE53f9Da1559728E4" -vvv --force --match "$1"
```

produces this output:
```
Running 13 tests for DssSpellTest
[PASS] testCastCost() (gas: 2864655)
[PASS] testFailTooEarly() (gas: 3580)
[PASS] testFailTooLate() (gas: 3591)
[PASS] testFailWrongDay() (gas: 3614)
[PASS] testFail_notScheduled() (gas: 7225)
[PASS] testOnTime() (gas: 2863066)
[PASS] testSpellIsCast_GENERAL() (gas: 11711549)
[PASS] testVestTransfer() (gas: 4238332)
[PASS] test_auth() (gas: 18446673704903691408)
[PASS] test_auth_in_sources() (gas: 18446673704895359685)
[PASS] test_bytecode_matches() (gas: 2783386)
[PASS] test_nextCastTime() (gas: 340057)
[PASS] test_use_eta() (gas: 338962)
```

**Comment by naszam** [comment]
Hi @brockelmore,

I've just run:
```
forge test --fork-url "$ETH_RPC_URL" --fork-block-number 13779177 --libraries "src/DssSpell.sol:DssExecLib:0xfD88CeE74f7D78697775aBDAE53f9Da1559728E4" -vvv --force
```
using Rivet, as you suggested in chat, and Test PASS :tada:

```haskell
compiling...
success.
Running 13 tests for DssSpellTest
[PASS] testCastCost() (gas: 2864655)
[PASS] testFailTooEarly() (gas: 3580)
[PASS] testFailTooLate() (gas: 3591)
[PASS] testFailWrongDay() (gas: 3614)
[PASS] testFail_notScheduled() (gas: 7225)
[PASS] testOnTime() (gas: 2863066)
[PASS] testSpellIsCast_GENERAL() (gas: 11711345)
[PASS] testVestTransfer() (gas: 4238332)
[PASS] test_auth() (gas: 18446673704902181312)
[PASS] test_auth_in_sources() (gas: 18446673704896405025)
[PASS] test_bytecode_matches() (gas: 2783386)
[PASS] test_nextCastTime() (gas: 340057)
[PASS] test_use_eta() (gas: 338962)
```

Thanks!

**Comment by brockelmore** [comment]
closing for now as it appears to be an issue with hardhat

**Comment by fvictorio** [comment]
Hi, someone mentioned this issue in our discord server, but AFAIK no one has opened an issue about it in our repo. Can someone help me understand the issue so I can create a minimal reproduction example (or, if someone can create the minimal example, even better).

**Comment by brockelmore** [comment]
hi @fvictorio! I believe the reproduction is just a hardhat mainnet fork (using cached state? @naszam can confirm) and calling this method rpc method: `rpc{method="eth_getStorageAt" params="[\"0xbd770416a3345f91e4b34576cb804a576fa48eb1\",\"0x000000000000000000000000000000000000000000000000000000000000001a\",\"latest\"]"}`

I may have gotten some things wrong here but ultimately something weird happened in the rpc call as you see above

**Comment by fvictorio** [comment]
Oh, thank you. @alcuadrado found out that we are probably implementing the spec wrong: we are expecting the storage slot to be a quantity (so no leading zeros), when in reality it seems like you _have_ to pass a 32 bytes hex. We'll open an issue about this. Thanks again!
