### ISSUE TITLE
forge: Reusable Test Suites

### ISSUE THREAD

**Issue by leeren** [gakonst/foundry#407]
Often it is helpful to run the same suite of tests across multiple contracts or fixtures. One primary example of this is testing public functions across multiple contracts sharing the same interface. 

With tools like HardHat, this is easy to do using Mocha by plugging our fixture as a reusable input to our test suites:

```typescript
// EXAMPLE: Testing two contracts sharing the same interface `TestInterface`
function shouldBehaveLikeTestInterface(): void {
  describe("TestInterface functionality", () => {  
     // Testing expected TestInterface behavior
  });
}

describe("ContractA", () => {
   this.contract = await loadFixture(contractAFixture);
   shouldBehaveLikeTestInterface();
});

describe("ContractB", () => {
   this.contract = await loadFixture(contractBFixture);
   shouldBehaveLikeTestInterface();
});
```

How should Foundry be used for similar invocations of reusable test suites?

**Comment by gakonst** [comment]
Can the behavior you're describing be achieved with this pattern?

```solidity
// your interface
interface IContract { function foo() { ... } }

// your 2 implementations
contract A is IContract { function foo() { ... } }
contract B is IContract { function foo() { ... } }

// the shared test suite
contract Tests {
          IContract contract;
          function testFoo() public { contract.foo(); }
}

contract ATests is Tests {
         function setUp() {
                  contract = IContract(address(new A()));
         }
}

contract BTests is Tests {
         function setUp() {
                  contract = IContract(address(new A()));
         }
}
```

**Comment by leeren** [comment]
@gakonst this works perfectly! Thank you. Can test output be constrained to that of implementing contracts under this inheritance-style testing approach? Running Forge with the above structure yields the following:

```
Running 2 tests for "ATest.json":ATest
[PASS] testX() (gas: 9453)
[PASS] testY() (gas: 5500)

Running 2 tests for "BTest.json":BTest
[PASS] testX() (gas: 9453)
[PASS] testY() (gas: 5500)

Running 2 tests for "Test.json":Test
[PASS] testX() (gas: 64)
[PASS] testY() (gas: 64)
```

Ideally I'd like to constrain output to just the first two contracts, especially since `Test` is an abstract contract here (so `PASS` is sort of misleading too).

**Comment by gakonst** [comment]
Have you marked it as `abstract contract` in your tests? If not, then it seems like we should filter abstract contracts out

**Comment by leeren** [comment]
@gakonst Yes, I did. Seems like that's the right solution! Unfortunately I'm not familiar with Rust - hopefully it's an easy fix?

**Comment by gakonst** [comment]
I think we probably should skip deployment if the contract's bytecode is empty? Try adding a check on bytecode .is_empty / len!=0 [here](https://github.com/gakonst/foundry/blob/master/forge/src/multi_runner.rs#L67-L73)

**Comment by leeren** [comment]
That sounds right to me. Hopefully another maintainer can chime in.

**Comment by wilsoncusack** [comment]
> I think we probably should skip deployment if the contract's bytecode is empty? Try adding a check on bytecode .is_empty / len!=0 [here](https://github.com/gakonst/foundry/blob/master/forge/src/multi_runner.rs#L67-L73)

Seems like kinda a blunt way to do this? I have created dummy empty contracts for test before. Can we not detect if it is marked abstract?

**Comment by gakonst** [comment]
I think the dummy empty contracts still have non-empty bytecode, whereas an abstract contract actually has 0 bytecode? So it should be fine?

**Comment by wilsoncusack** [comment]
ah ok, my lack of understanding

**Comment by gakonst** [comment]
@leeren should be fixed now in master

**Comment by leeren** [comment]
Amazing, thank you!
