### ISSUE TITLE
forge: Print custom errors for revert reasons on failing tests

### ISSUE THREAD

**Issue by leeren** [gakonst/foundry#409]
Currently, when a test function fails and the culprit is a custom error being thrown, the custom error message is not printed out:

```solidity
function X() public {
  revert CustomError();
}

function testX() public {
  X();
}
```
Expected output:
```bash
[FAIL. Reason: CustomError() ] testX() ...
```

Actual output:
```bash
[FAIL. Reason: ] testX() ...
```

**Comment by leeren** [comment]
I was on an old version of Foundry. Although the custom error human-readable string is not printed, the encoded error data is shown, which is good enough!

**Comment by onbjerg** [comment]
If you check docs.rs for ethers it is not, but it is in ethabi upstream. Not sure if we just haven't published in a while.
