### ISSUE TITLE
Debugger: prev/next op not working properly

### ISSUE THREAD

**Issue by nicolasgarcia214** [gakonst/foundry#411]
the opcode highlighter is lost as I go through the debugger. The program counter and the gas consumed keeps changing but the opcodes screen remains static for a couple of steps forward until it changes again but the highlight is no longer visible.

![Animation](https://user-images.githubusercontent.com/37629288/148811818-d52c5162-a685-45a7-a65a-5407a7fc711d.gif)

**Comment by brockelmore** [comment]
this is a formatting issue - if youre able to use a larger terminal, it should print correctly, but this should be fixed regardless

**Comment by nicolasgarcia214** [comment]
Another temporary solution is to decrease the font size of the terminal.
PS: Not the best solution in terms of UX and accessibility.

**Comment by evantancy** [comment]
hi just wanted to ask how do we access the debugger? is the command `forge test --debug`?

**Comment by gakonst** [comment]
```
 forge run /path/to/your/contract.sol --debug -t "testFoo()"
```

@brockelmore will eventually add an interactive dialogue for making it work with `forge test`, but we haven't had the time yet
