### ISSUE TITLE
forge test panic when logging negative numbers

### ISSUE THREAD

**Issue by dcposch** [gakonst/foundry#418]
## summary

`forge test` panics with following error:

```
$ forge test
compiling...
success.
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: FromDecStrError(InvalidCharacter)
Location: evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs:90

Backtrace omitted.
Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Abort trap: 6
```

## steps to reproduce

**minimal reproduction**, excerpted from https://github.com/dapphub/ds-test/blob/master/demo/demo.sol

```solidity
pragma solidity 0.8.11;

import "ds-test/test.sol";

contract DemoTest is DSTest {
    function test_logs() public {
        emit log("-- log_named_decimal_int(string, int, uint)");
        emit log_named_decimal_int("decimal int", -1.0e18, 18);
    }
}
```

**Comment by gakonst** [comment]
This happens [here](https://github.com/gakonst/foundry/blob/master/evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs#L119)

**Comment by lattejed** [comment]
This is happening because the value is being passed through `U256::from_dec_str` from [here](https://github.com/paritytech/parity-common) which doesn't expect a `-`

So -- are negative values here valid? 

Would be easy enough to work around if so. If not, maybe this just needs a better error message.

**Comment by lattejed** [comment]
Looks like [this](https://github.com/gakonst/foundry/pull/361) is related. @mds1 are you still working on this?

**Comment by lattejed** [comment]
Workaround here: #441 

If I256 support gets added upstream, this should be removed
