### ISSUE TITLE
Correct formatting of decimals in ds-test logs

### ISSUE THREAD

**Issue by lattejed** [gakonst/foundry#443]
This is related to #361 which seems to have caused a regression [here](https://github.com/gakonst/foundry/blob/53984da48d2f03e9b777cec92fde860bf7361729/evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs#L131).

The test was updated [here](https://github.com/gakonst/foundry/blob/53984da48d2f03e9b777cec92fde860bf7361729/evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs#L1711) to pass.

Reverting these changes fixes the issue.

However, the outstanding issue remains. Assuming the output should match dapptools, then:

dapptools:
```
  -- log_named_decimal_int("decimal int", -1.0e18, 18)
  decimal int: -1.000000000000000000
```

forge:
```
  -- log_named_decimal_int("decimal int", -1.0e18, 18)
  decimal int: -1000000000000000000000000000000000000
```

I guess the # of trailing zeros for dapptools is arbitrary. @gakonst do you want to match dapptools exactly? I don't see any reason to have 18 trailing zeros.

Happy to take care of this

**Comment by gakonst** [comment]
Yes, for anything logging like this I believe we should match dapptools. If you can go for it it'd be great.

**Comment by lattejed** [comment]
Looks like I reversed this:

The changes made to `LogNamedDecimalUintFilter` were actually correct and brought it in line with dapptools.

`LogNamedDecimalIntFilter` for some reason was not fixed at the same time and was never correct, regardless of negative value handling.

@gakonst the inconsistency you saw was from the incorrect `LogNamedDecimalIntFilter`. 

I'll get it cleaned up

**Comment by lattejed** [comment]
This should be ready to go. 

The new version of `LogNamedDecimalIntFilter` uses `I256` from ethers-rs and probably doesn't need upstream support as I mentioned in  #441

**Comment by lattejed** [comment]
I'll look at it. @transmissions11 what are you seeing exactly?

**Comment by transmissions11** [comment]
oh nvm haha i misinterpreted things

was looking just at the trace

<img width="704" alt="Screen Shot 2022-03-22 at 7 08 53 PM" src="https://user-images.githubusercontent.com/26209401/159609285-2ce936b8-30c8-4a12-8505-0c96b566f8c0.png">

duh the formatting is in the logs

<img width="290" alt="Screen Shot 2022-03-22 at 7 09 12 PM" src="https://user-images.githubusercontent.com/26209401/159609377-cdf60c96-f7f2-4a58-9be3-9d001f767bdd.png">

**Comment by lattejed** [comment]
Ah, gotcha 🤝
