### ISSUE TITLE
forge: contract JSON ABI incorrectly specifies "constant": false

### ISSUE THREAD

**Issue by dcposch** [gakonst/foundry#457]
## summary

forge outputs JSON ABIs like the following:

```json
{
  "type": "function",
  "name": "blockHeightToHash",
  "inputs":[{"internalType":"uint256","name":"","type":"uint256"}],
  "outputs":[{"internalType":"bytes32","name":"","type":"bytes32"}],
  "constant": false,
  "stateMutability": "pure"
}
```

when loading in ethers.js, this gives the following (slightly misleading) error:

```
Error: cannot have constant function with mutability view (argument="value", value={"type":"function","name":"blockHeightToHash","inputs":[{"internalType":"uint256","name":"","type":"uint256"}],"outputs":[{"internalType":"bytes32","name":"","type":"bytes32"}],"constant":false,"stateMutability":"view"}, code=INVALID_ARGUMENT, version=abi/5.5.0)
```

looking deeper, it appears that ethers.js expects `"constant"` to be true if and only if `"stateMutability"` is `"view"` or `"pure"`:

https://github.com/ethers-io/ethers.js/blob/73a46efea32c3f9a4833ed77896a216e3d3752a0/packages/abi/src.ts/fragments.ts#L661-L663

### version

```
foundry-cli 0.1.0
ethers 5.5.3
```

**Comment by dcposch** [comment]
### specification confirms this is a bug

the Ethereum JSON ABI spec agrees with `ethers`.

```
constant: true if function is either pure or view, false otherwise.
```
https://docs.soliditylang.org/en/v0.5.3/abi-spec.html#json

**Comment by dcposch** [comment]
### steps to reproduce

run forge build on following contract:

https://ropsten.etherscan.io/address/0x69ee459ca98cbdecf9156b041ee1621513aef0c6#code

inspect output JSON ABI

**Comment by mattsse** [comment]
I think this is a serde issue, which emits `constant: false` even if we set it to `None`

https://github.com/rust-ethereum/ethabi/blob/199e307462ea6ad17c3ff48dcba8aa42b23cb2c3/ethabi/src/function.rs#L31-L35

instead of `serde(default)` in should be `#[serde(default, skip_serializing_if = "Option::is_none")]`

I think we can ignore `constant` entirely at this point @brockelmore ?

**Comment by brockelmore** [comment]
Older compiler versions still output it but i think outright ignoring is fine as it's not needed

**Comment by brockelmore** [comment]
This is no longer true: now it outputs `null` if its None. Have an open PR to skip serialization upstream. Closing
