### ISSUE TITLE
Fuzz sends wrong value for ints

### ISSUE THREAD

**Issue by crisgarner** [gakonst/foundry#458]
Doing fuzz with int8 throws an exception. In the following example, the error happens as the _num variable in the fuzz receives the 128 value and can't be parsed to an int8.

```solidity
// myContract function    
function setNum(int8 _num) external onlyOwner {
        num = _num;
    }

// myContract test
  function testSetNum(int8 num) public {
        myContract.setNum(num);
        ...
    }
```

manually taking the value of the fuzz revert and trying to cast it throws this error:

```bash
TypeError: Explicit type conversion not allowed from "int_const 129" to "int8".
```

**Comment by brockelmore** [comment]
likely an off-by-one here: https://github.com/gakonst/foundry/blob/4d3c8d5194d7ff5c821e07059b9f04104ac059d8/evm-adapters/src/fuzz.rs#L262-L266

h/t @mds1

**Comment by brockelmore** [comment]
solution: dont use sign as a prop, it allows for a +128 which is impossible
