### ISSUE TITLE
Apple M1 tracking issue

### ISSUE THREAD

**Issue by onbjerg** [gakonst/foundry#466]
We can't compile for Apple M1 in CI currently because some packages break even when we try to cross-compile.

Will try to gather relevant issues here for tracking

- https://github.com/rust-bitcoin/rust-secp256k1/issues/283
- https://github.com/rust-lang/rust/issues/73908

**Comment by brockelmore** [comment]
I am not sure if we are able to, but adding this to cargo config has fixed issues in the past for M1 stuff. May be worth a shot trying

```
[target.x86_64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]

[target.aarch64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]
```

ref: https://stackoverflow.com/questions/28124221/error-linking-with-cc-failed-exit-code-1

**Comment by brockelmore** [comment]
better solution: remove the need of secp256k1 crate all together by refactoring this: https://github.com/bluealloy/revm/blob/main/crates/revm_precompiles/src/secp256k1.rs
