### ISSUE TITLE
Remove `Clone` trait bound from EVM

### ISSUE THREAD

**Issue by gakonst** [gakonst/foundry#47]
# The Problem

In #44 we made required EVM to be `Clone` with the following rationale:
> A requirement of fuzzing was to make the EVM cloneable, since the TestRunner only accepts Fns which cannot mutate their environment, meaning that we had to add a Clone restriction on it in the fuzzing-related code.

..and also noted:
> if we can remove the Clone requirement by using a factory, and splitting the fuzz tests to a separate function so we can run fuzz tests w/o tracing even when the EVM uses a tracer in non-fuzz tests

We worked around this requirement by patching our dependencies and making  the EVMs clone-able. This probably won't scale well given that EVMs may own or reference state or tracers that cannot be cloned or is too expensive to clone, so we'll need to fix this ASAP.

# Possible Solution

@vorot93 suggested that instead of `Clone`'ing, we could use a factory function like so:

```rust
let evm_factory = || {
    EvmOdin::new(...)
};
let factory_fn = || {
    let mut evm = (evm_factory)()
    evm.setup();
    evm
};
```

**Comment by gakonst** [comment]
Temporarily non-threadsafe solution by @mattsse in #50

**Comment by brockelmore** [comment]
is this still relevant?

**Comment by mattsse** [comment]
think we can close that @gakonst

**Comment by gakonst** [comment]
Yeah not needed anymore
