### ISSUE TITLE
Issue with arguments using forge create

### ISSUE THREAD

**Issue by crisgarner** [gakonst/foundry#473]
Currently deploying a contract with multiple arguments require `forge create` command to use multiple times the param `--constructor-args`

```bash
forge create Token --constructor-args "My token" --constructor-args "TKN" --constructor-args 18 --mnemonic-path XXX --rpc-url XXX
```

Suggestion, change it to only require one argument call

```bash
forge create Token --constructor-args "My token" "TKN" 18 --mnemonic-path XXX --rpc-url XXX
```
Fix might be around here: https://github.com/gakonst/foundry/blob/master/cli/src/cmd/create.rs#L54-L55

**Comment by gakonst** [comment]
Could also be clap related? https://github.com/gakonst/foundry/blob/master/cli/src/cmd/create.rs#L22-L23

**Comment by fmhall** [comment]
Can we add a `--verify` flag to `forge create`? Does that make sense?

**Comment by gakonst** [comment]
@fmhall this is tracked in #287 #354

**Comment by gakonst** [comment]
Hmm reading through the warnings, it seems like it should be fine? I don't think we'd ever have any positional arguments for `--constructor-args`, only named args? We can enable this with `raw` in clap derive if I'm not mistaken - I'd be supportive of doing that.

**Comment by onbjerg** [comment]
Yeah I think in this case it is fine

**Comment by calldata** [comment]
Anyone take this issue ?
