### ISSUE TITLE
`expectRevert` ergonomics

### ISSUE THREAD

**Issue by onbjerg** [gakonst/foundry#479]
We should have two more `expectRevert` signatures:

- `expectRevert(bytes4)` so you can do e.g. `expectRevert(Contract.CustomError.selector)`
- `expectRevert(string)` so you can do e.g. `expectRevert("foo")`

Currently you can achieve both of these but it requires casting and/or `abi.encodeWithSelector`

**Comment by gakonst** [comment]
FYI @brockelmore

**Comment by onbjerg** [comment]
Not sure what the plan is for `forge-std` but this could technically be implemented in "userland" as a wrapper around the already existing `expectRevert`

**Comment by brockelmore** [comment]
Errors dont have selectors i dont believe. They are second class functions :(

**Comment by brockelmore** [comment]
i literally tried this when i was implementing expectRevert lmao i must have messed it up

**Comment by onbjerg** [comment]
:thinking: weird it works now at least. i haven't been able to get it to work with _some_ parameters to the errors though, like strings. seems like they are encoded slightly differently even though the solidity docs say errors are encoded in exactly the same way as a function with some calldata
