### ISSUE TITLE
Allow dependency-less projects

### ISSUE THREAD

**Issue by onbjerg** [gakonst/foundry#482]
Currently if you create a directory with just a contract and issue `forge build --contracts Contract.sol` then `forge` will fail:

```
Error:
   0: "/home/oliver/Projects/hello_foundry/lib": No such file or directory (os error 2)

Location:
   /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/core/src/result.rs:1911

Backtrace omitted.
Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

If you create an empty `lib/` directory this works fine.

**Comment by mattsse** [comment]
yeah I discovered that myself, this already fixed in the config branch ref #291 , but I haven't submitted a separate fix

**Comment by gakonst** [comment]
@mattsse whcih part of the code in that branch addresses the issue? i seem to not be seeing it

**Comment by mattsse** [comment]
I believe it was just this

https://github.com/gakonst/foundry/pull/297/files#diff-ef70820a1a4c9a088e76cd9627077144e3bbb14b255ad298c2762be58f13f09bR47

**Comment by gakonst** [comment]
Ah right but this will create a lib dir, was wondering if we could make a ethers-solc work if only a src dir was provided and no lib dir exists
