### ISSUE TITLE
panic on deploy, "no bytecode found in bin object"

### ISSUE THREAD

**Issue by dcposch** [gakonst/foundry#487]
## summary

see log below.
- `forge build` completes successfully. compiled JSONs *are* written to `out/`, including bytecode.
- `forge test` returns successfully, but does not actually run any tests (!)
- `forge create` panics, "no bytecode found in bin object"

## version

`foundry-cli 0.1.0`

(as an aside... it might be good to print the git commit as part of `cast --version`. i think 0.1.0 may have been reused across multiple releases)

## details

```
$ ETH_RPC_URL=https://ropsten.infura.io/v3/[REDACTED] forge create src/BtcMirror.sol:BtcMirror --private-key [REDACTED] | tee out/deploy-ropsten
compiling...
no files changed, compilation skipped.
The application panicked (crashed).
Message:  no bytecode found in bin object for BtcMirror
Location: cli/src/cmd/create.rs:94

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 7 frames hidden ⋮                               
   8: forge::cmd::create::CreateArgs::deploy::{{closure}}::{{closure}}::h38baea11675a01ee
      at <unknown source file>:<unknown line>
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h6494ceaa2f751726
      at <unknown source file>:<unknown line>
  10: <forge::cmd::create::CreateArgs as forge::cmd::Cmd>::run::h3c967ff4f229f6e7
      at <unknown source file>:<unknown line>
  11: forge::main::hfb244ae5dd462a62
      at <unknown source file>:<unknown line>
  12: std::sys_common::backtrace::__rust_begin_short_backtrace::h48f332c6dd91a89d
      at <unknown source file>:<unknown line>
  13: _main<unknown>
      at <unknown source file>:<unknown line>
```

i've attached both BtcMirror.sol and the output BtcMirror.json. panic message notwithstanding, the output JSON does seem to contain bytecode.

[BtcMirror.zip](https://github.com/gakonst/foundry/files/7885351/Archive.zip)

**Comment by dcposch** [comment]
## steps to reproduce

i reproduced on nightly.

i also bisected by removing code from the contract.

1. clone https://github.com/dcposch/btcmirror
2. check out `forge-bug-487` branch
3. run `forge test`. this will **appear to succeed but not actually run any tests.**
4. `git checkout HEAD^ && forge test`. on the previous commit, the tests run (and fail) as expected.

**the only difference between the working and non-working commit is a single method changed from `public` to `private`.** in this stripped down reproduction example, that method is not called anywhere.

**Comment by dcposch** [comment]
i doubt it matters, but i'm using macOS 11.4

**Comment by onbjerg** [comment]
Hey, just want to let you know that I am looking into it. It's a strange one for sure. Will get back to you

**Comment by onbjerg** [comment]
Ok I think I figured it out. You're using a library and apparently we are not linking them here for some reason? The `bin` and `bin-runtime` values in the output contain the placeholders at least (cc @mattsse)

It does work as @dcposch said if you go up one commit on the branch and there is no change to the library, just a visibility change. It's really strange

**Comment by odyslam** [comment]
I have encountered this in the past. 

Could it be that some dependency files (e.g some library) have different pragma requirements and thus forge can't sompile the whole project using a single version of solc. 

I remember that forge had the restriction

**Comment by onbjerg** [comment]
No they use the same pragma (the library in question is in `src/Endian.sol`)

**Comment by onbjerg** [comment]
Ah, that makes sense. So this was a linker issue after all

**Comment by gakonst** [comment]
Closing and let's consolidate to #222

**Comment by gakonst** [comment]
> ## steps to reproduce
> i reproduced on nightly.
> 
> i also bisected by removing code from the contract.
> 
> 1. clone https://github.com/dcposch/btcmirror
> 2. check out `forge-bug-487` branch
> 3. run `forge test`. this will **appear to succeed but not actually run any tests.**
> 4. `git checkout HEAD^ && forge test`. on the previous commit, the tests run (and fail) as expected.
> 
> **the only difference between the working and non-working commit is a single method changed from `public` to `private`.** in this stripped down reproduction example, that method is not called anywhere.

I'm getting stack too deep when I run `forge test` at step 3 or 4.

**Comment by dcposch** [comment]
@gakonst sorry, just saw this.

i tried again and get the following error. i *have* seen the "stack too deep" error before, but not on this particular commit. here, the tests appear to pass while not actually running:

![image](https://user-images.githubusercontent.com/169280/150660467-d2d20ef9-c856-4543-81bd-7a66db7c293e.png)
