### ISSUE TITLE
fix(foundryup): warn users if libusb is not installed

### ISSUE THREAD

**Issue by transmissions11** [gakonst/foundry#498]
https://github.com/gakonst/foundry/discussions/481#discussion-3805656

**Comment by onbjerg** [comment]
For Linux:

```sh
pkg-config --libs usb
```

If exit code 0 then it exists (it outputs `-lusb`), exit code 1 it doesn't.

**Comment by transmissions11** [comment]
hmm forge and cast binaries run fine for me and this exits with 1

**Comment by transmissions11** [comment]
i guess we just make it a warning

**Comment by onbjerg** [comment]
mby its diff on macos? no clue

**Comment by gakonst** [comment]
Yea warning SGTM and we follow up if needed
