### ISSUE TITLE
forge create is confusing

### ISSUE THREAD

**Issue by sorenrood** [gakonst/foundry#503]
Deploying a contract with forge create is not very intuitive (to me). Consider this contract:

```solidity
// SPDX-License-Identifier: Unlicense
pragma solidity 0.8.10;

contract HelloWorld {
    string private greeting;
    uint public version = 0;

    constructor (string memory _greeting) {
        greeting = _greeting;
    }

    function greet() public view returns(string memory) {
        return greeting;
    }

    function updateGreeting(string memory _greeting) public {
        version += 1;
        greeting = _greeting;
    }
}
```

My first thought was to do `forge create -h`. From here I read that I must include the "artifact". I could not find any information on what "artifacts" are. I ended up figuring out that if you type the name of the contract (in this case "HelloWorld"), it would work.

After I added the rpc-url and my private-key, I'm now getting a new error:

`Error: 0:  Invalid Data`.

I'm really not sure how to use `forge create` at this point. I can't find any tutorials or docs.

**Comment by gakonst** [comment]
You need to provide a constructor argument, since your contract takes a string you need to do 'forge create HelloWorld "hello"'

**Comment by sorenrood** [comment]
If I do:

`forge create HelloWorld "hello world" --rpc-url <my url> --private-key <my-private-key>`

I still get the error:

![Screen Shot 2022-01-19 at 3 34 11 PM](https://user-images.githubusercontent.com/49735495/150235285-4c793788-81a7-4749-9862-5e39f6b9be36.png)

(my contract is `HelloWorld.sol`)

**Comment by onbjerg** [comment]
```
forge create HelloWorld --constructor-args "Hello" --rpc-url <url> --private-key <key>
```

Better ergonomics are being discussed in https://github.com/gakonst/foundry/issues/473

**Comment by sorenrood** [comment]
Ah okay -- thank you!
