### ISSUE TITLE
feature request: Constant mining in fuzzer

### ISSUE THREAD

**Issue by transmissions11** [gakonst/foundry#51]
Echidna has a feature called ["constant mining"](https://github.com/crytic/echidna/pull/262) where it scrapes return values and adds those values to its dictionary to retry as inputs later. 

Without this feature, Echidna would (and did) miss the Dappsys DSChief bug.

**Comment by gakonst** [comment]
More info on it / the motivation in this thread https://forum.openzeppelin.com/t/using-automatic-analysis-tools-with-makerdao-contracts/1021/2, h/t @mds1

**Comment by transmissions11** [comment]
clsoing in favor of aggregated #387
