### ISSUE TITLE
Unexpected behavior with imports that don't start with the '@' character

### ISSUE THREAD

**Issue by ruvaag** [gakonst/foundry#513]
### Summary
Noticed some unexpected behavior with remappings and imports when migrating from hardhat. Most npm package dependencies start with the '@' character which are handled perfectly, however this is not the case for all of them. In this case the library is [prb-math](https://github.com/paulrberg/prb-math). A typical solidity import for this library looks like `import "prb-math/contracts..."` instead of the usual `import "@uniswap/v3-periphery.."` with the '@' character which might be the key to the error.

### Reproduce the issue
1. `mkdir forge-example`
2. `forge init`
3. `forge build` (This should work)
4. `forge install paulrberg/prb-math`
5.  Add `import "prb-math/contracts/PRBMathUD60x18.sol";` to `src/Contract.sol`
6. `touch remappings.txt`
7. Add `prb-math/=lib/prb-math/` to `remappings.txt`
8. `forge build` -- This fails with `Error 0: .../forge-example/lib/prb-math/contracts/contracts/PRBMathUD60x18.sol": No such file or directory (os error 2)`

### Current Fix
I was able to fix this by manually changing the import to `import "@prb-math/contracts/PRBMathUD60x18.sol";` in `Contract.sol` and the corresponding remapping to `@prb-math/=lib/prb-math/`, but this might be an issue when dealing with multiple imports across different libraries. This led me to believe that foundry might have a hard-coded dependency on the import statements starting with the '@' character.

### System specs
I'm running a 2017 MBP with macOS 11.6 and an Intel processor

**Comment by onbjerg** [comment]
Can you also provide the output of `forge remappings`? That would help us determine how forge currently sees your dependencies.

**Comment by ruvaag** [comment]
Output from `forge remappings`:
```
prb-math/=/Users/ruvaag/work/forge-example/lib/prb-math/contracts/
ds-test/=/Users/ruvaag/work/forge-example/lib/ds-test/src/
```

**Comment by onbjerg** [comment]
I haven't tested it yet, but I will later. It does kind of seem like a bug though, the remappings you configure yourself should take precedent
