### ISSUE TITLE
Feature: Testing as an EOA

### ISSUE THREAD

**Issue by alcibiadeseth** [gakonst/foundry#517]
I am presently working with @captnseagraves on a project which uses EOA signatures to authorize operations. Is there presently a way to produce these signatures within foundry tests? If not, would be a useful feature.

**Comment by onbjerg** [comment]
Yes! Check out the cheatcodes listed in [here](https://github.com/gakonst/foundry/tree/master/forge) particularly this one:

```solidity
// Signs data, (privateKey, digest) => (v, r, s)
function sign(uint256,bytes32) external returns (uint8,bytes32,bytes32);
```

**Comment by gakonst** [comment]
Yep as bjerg said that's the way.

**Comment by 5hanth** [comment]
is there a way to generate RLP encoding from (v, r, s) in tests to pass it to contracts that expects Ethereum signed message?

**Comment by gakonst** [comment]
Yes, `vm.sign` cheatcode! https://book.getfoundry.sh/tutorials/testing-eip712?highlight=vm.sign#diving-in

**Comment by 5hanth** [comment]
@gakonst `vm.sign` is giving `(v,r,s)`, doing `bytes signature = abi.encodePacked(r, s, v)` is not a valid RLP notation correct? https://ethereum.org/en/developers/docs/data-structures-and-encoding/rlp/

**Comment by 5hanth** [comment]
@gakonst I guess we don't have support to generate RLP from (v,r,s) yet. https://github.com/foundry-rs/foundry/issues/517#issuecomment-1252982917 `vm.sign` only providers (v,r,s) and not RLP encoded hex string https://ethereum.stackexchange.com/a/107498/18370
