### ISSUE TITLE
Forge Build is not working

### ISSUE THREAD

**Issue by ChinmayGopal931** [gakonst/foundry#518]
I'm on Ubuntu and have cargo 1.58.0 (7f08ace4f 2021-11-24)  and  rustc 1.58.0 (02072b482 2022-01-11). 
For some reason forge doesn't want to build. Even after I added new tests and changes the contract. 
 It says no files changed, compilation skipped.

When I run forge test it just returns the generic default test which I removed.

For reference I am following this tutorial exactly https://mirror.xyz/sha.eth/6Mn3HjrqKLhHzu2balLPv4SqE5a-oEESl4ycpRkWFsc

**Comment by onbjerg** [comment]
Try running with `--force` or running `forge clean` before building. Would also be helpful if we got at least the structure of your project as we have been having some issues with cache invalidation

**Comment by ChinmayGopal931** [comment]
> Try running with `--force` or running `forge clean` before building. Would also be helpful if we got at least the structure of your project as we have been having some issues with cache invalidation

Doesn't seem to work. I've updated the main issue to show the tutorial i am following. 
But here is the structure. 
->lib
->src
        ->test
                 ->HelloWorld.t.sol
        ->HelloWorld.sol

**Comment by onbjerg** [comment]
Just to be clear, is `test` inside of `src`? And do you have any contracts in `src`?

**Comment by ChinmayGopal931** [comment]
> Just to be clear, is `test` inside of `src`? And do you have any contracts in `src`?

Yes, test is inside of src and src has the contract helloWorld.sol. The test folder has HelloWorld.t.sol. Sorry Idk how to change the formatting here.

**Comment by onbjerg** [comment]
Pretty weird, following that tutorial I get the output I expect:

```
$ forge test
compiling...
no files changed, compilation skipped.
Running 2 tests for HelloWorldTest.json:HelloWorldTest
[PASS] test1() (gas: 4220)
[PASS] test2() (gas: 31425)
```

```
$ tree .
.
├── cache
│   └── solidity-files-cache.json
├── lib
│   └── ds-test
│       ├── default.nix
│       ├── demo
│       │   └── demo.sol
│       ├── LICENSE
│       ├── Makefile
│       └── src
│           └── test.sol
├── out
│   ├── Contract.t.sol
│   │   └── ContractTest.json
│   ├── HelloWorld.sol
│   │   └── HelloWorld.json
│   ├── HelloWorld.t.sol
│   │   └── HelloWorldTest.json
│   └── test.sol
│       └── DSTest.json
└── src
    ├── HelloWorld.sol
    └── test
        └── HelloWorld.t.sol

12 directories, 12 files
```

Could you run the `tree .` command for me? Put the output into quotes like so to keep the indentation:

\```
foo bar
\```

**Comment by onbjerg** [comment]
> Does it matter what is inside of lib?

For that tutorial you *should* have a `ds-test` folder with some files, specifically a `src/test.sol` file (so `lib/ds-test/src/test.sol` should exist).

**Comment by ChinmayGopal931** [comment]
> Pretty weird, following that tutorial I get the output I expect:
> 
> ```
> $ forge test
> compiling...
> no files changed, compilation skipped.
> Running 2 tests for HelloWorldTest.json:HelloWorldTest
> [PASS] test1() (gas: 4220)
> [PASS] test2() (gas: 31425)
> ```
> 
> ```
> $ tree .
> .
> ├── cache
> │   └── solidity-files-cache.json
> ├── lib
> │   └── ds-test
> │       ├── default.nix
> │       ├── demo
> │       │   └── demo.sol
> │       ├── LICENSE
> │       ├── Makefile
> │       └── src
> │           └── test.sol
> ├── out
> │   ├── Contract.t.sol
> │   │   └── ContractTest.json
> │   ├── HelloWorld.sol
> │   │   └── HelloWorld.json
> │   ├── HelloWorld.t.sol
> │   │   └── HelloWorldTest.json
> │   └── test.sol
> │       └── DSTest.json
> └── src
>     ├── HelloWorld.sol
>     └── test
>         └── HelloWorld.t.sol
> 
> 12 directories, 12 files
> ```
> 
> Could you run the `tree .` command for me? Put the output into quotes like so to keep the indentation:
> 
> ``` foo bar ```
> 
> FYI I'm on Linux too (not Ubuntu) so I'd be surprised if it's a platform issue

> chinmay@chinmay-x1carbon:~/forge$ tree .
.
├── lib
│   └── ds-test
│       ├── default.nix
│       ├── demo
│       │   └── demo.sol
│       ├── LICENSE
│       ├── Makefile
│       └── src
│           └── test.sol
└── src
    ├── Contract.sol
    ├── HelloWorld.sol
    └── test
        └── HelloWorld.t.sol

Also when I run sudo forge init I get this :`sudo: forge: command not found`

**Comment by onbjerg** [comment]
Yes, that's because `forge` is in `$HOME/.cargo/bin/forge` so that's expected - when you run commands with `sudo` then `$HOME` changes (usually to `/root` or `/home/root`) and it can't find `forge`.

**Comment by onbjerg** [comment]
Ok, that looks like it should. Is the source code inside of `Contract.sol` or `HelloWorld.sol`?

**Comment by ChinmayGopal931** [comment]
> Yes, that's because `forge` is in `$HOME/.cargo/bin/forge` so that's expected - when you run commands with `sudo` then `$HOME` changes (usually to `/root` or `/home/root`) and it can't find `forge`.

Got it. 
But Is it an error with foundry? Why am I not getting an out file

**Comment by ChinmayGopal931** [comment]
> Ok, that looks like it should. Is the source code inside of `Contract.sol` or `HelloWorld.sol`?

HelloWorld.sol

**Comment by onbjerg** [comment]
Can you try to run `RUST_LOG=trace forge test --force` for me and dump the output?

**Comment by ChinmayGopal931** [comment]
> RUST_LOG=trace forge test --force

`hinmay@chinmay-x1carbon:~/forge$ RUST_LOG=trace forge test --force
Jan 19 20:25:15.490 TRACE ethers_solc: clean up project
Jan 19 20:25:15.491 TRACE ethers_solc: removed cache file "/home/chinmay/cache/solidity-files-cache.json"
Jan 19 20:25:15.491 TRACE ethers_solc: removed artifacts dir "/home/chinmay/out"
compiling...
Jan 19 20:25:15.492 TRACE compile: ethers_solc: found 2 sources to compile: ["/home/chinmay/src/Contract.sol", "/home/chinmay/src/test/Contract.t.sol"]
Jan 19 20:25:15.492 TRACE compile: ethers_solc: using solc auto detection to compile sources
Jan 19 20:25:15.496 TRACE compile:svm_compile: ethers_solc::resolver: resolving input node versions
Jan 19 20:25:15.497 TRACE compile:svm_compile: mio::poll: registering event source with poller: token=Token(0), interests=READABLE | WRITABLE    
Jan 19 20:25:15.512 TRACE compile:svm_compile: hyper::client::pool: checkout waiting for idle connection: ("https", binaries.soliditylang.org)
Jan 19 20:25:15.512 DEBUG compile:svm_compile: reqwest::connect: starting new connection: https://binaries.soliditylang.org/    
Jan 19 20:25:15.512 TRACE compile:svm_compile: hyper::client::connect::http: Http::connect; scheme=Some("https"), host=Some("binaries.soliditylang.org"), port=None
Jan 19 20:25:15.513 DEBUG hyper::client::connect::dns: resolving host="binaries.soliditylang.org"
Jan 19 20:25:15.856 DEBUG compile:svm_compile: hyper::client::connect::http: connecting to [2600:9000:20bc:d800:1:943d:f600:93a1]:443
Jan 19 20:25:15.857 TRACE compile:svm_compile: mio::poll: registering event source with poller: token=Token(1), interests=READABLE | WRITABLE    
Jan 19 20:25:15.881 DEBUG compile:svm_compile: hyper::client::connect::http: connected to [2600:9000:20bc:d800:1:943d:f600:93a1]:443
Jan 19 20:25:15.922 TRACE compile:svm_compile: hyper::client::conn: client handshake Http1
Jan 19 20:25:15.922 TRACE compile:svm_compile: hyper::client::client: handshake complete, spawning background dispatcher task
Jan 19 20:25:15.922 TRACE want: signal: Want    
Jan 19 20:25:15.922 TRACE hyper::proto::h1::conn: flushed({role=client}): State { reading: Init, writing: Init, keep_alive: Busy }
Jan 19 20:25:15.922 TRACE compile:svm_compile: want: poll_want: taker wants!    
Jan 19 20:25:15.922 TRACE compile:svm_compile: hyper::client::pool: checkout dropped for ("https", binaries.soliditylang.org)
Jan 19 20:25:15.922 TRACE encode_headers: hyper::proto::h1::role: Client::encode method=GET, body=None
Jan 19 20:25:15.922 DEBUG hyper::proto::h1::io: flushed 85 bytes
Jan 19 20:25:15.922 TRACE hyper::proto::h1::conn: flushed({role=client}): State { reading: Init, writing: KeepAlive, keep_alive: Busy }
Jan 19 20:25:15.976 TRACE hyper::proto::h1::conn: Conn::read_head
Jan 19 20:25:15.976 TRACE hyper::proto::h1::io: received 8192 bytes
Jan 19 20:25:15.976 TRACE parse_headers: hyper::proto::h1::role: Response.parse bytes=8192
Jan 19 20:25:15.976 TRACE parse_headers: hyper::proto::h1::role: Response.parse Complete(618)
Jan 19 20:25:15.976 DEBUG hyper::proto::h1::io: parsed 17 headers
Jan 19 20:25:15.976 DEBUG hyper::proto::h1::conn: incoming body is content-length (39213 bytes)
Jan 19 20:25:15.976 TRACE hyper::proto::h1::decode: decode; state=Length(39213)
Jan 19 20:25:15.976 TRACE hyper::proto::h1::conn: flushed({role=client}): State { reading: Body(Length(31639)), writing: KeepAlive, keep_alive: Busy }
Jan 19 20:25:15.976 DEBUG compile:svm_compile: reqwest::async_impl::client: response '200 OK' for https://binaries.soliditylang.org/linux-amd64/list.json    
Jan 19 20:25:15.976 TRACE hyper::proto::h1::decode: decode; state=Length(31639)
Jan 19 20:25:15.976 TRACE hyper::proto::h1::io: received 8192 bytes
Jan 19 20:25:15.976 TRACE hyper::proto::h1::conn: flushed({role=client}): State { reading: Body(Length(23447)), writing: KeepAlive, keep_alive: Busy }
Jan 19 20:25:15.976 TRACE hyper::proto::h1::decode: decode; state=Length(23447)
Jan 19 20:25:15.976 TRACE hyper::proto::h1::io: received 16384 bytes
Jan 19 20:25:15.976 TRACE hyper::proto::h1::conn: flushed({role=client}): State { reading: Body(Length(7063)), writing: KeepAlive, keep_alive: Busy }
Jan 19 20:25:15.976 TRACE hyper::proto::h1::decode: decode; state=Length(7063)
Jan 19 20:25:15.976 TRACE hyper::proto::h1::conn: flushed({role=client}): State { reading: Body(Length(7063)), writing: KeepAlive, keep_alive: Busy }
Jan 19 20:25:15.998 TRACE hyper::proto::h1::decode: decode; state=Length(7063)
Jan 19 20:25:15.998 TRACE hyper::proto::h1::io: received 7063 bytes
Jan 19 20:25:15.998 DEBUG hyper::proto::h1::conn: incoming body completed
Jan 19 20:25:15.998 TRACE hyper::proto::h1::conn: maybe_notify; read_from_io blocked
Jan 19 20:25:15.998 TRACE want: signal: Want    
Jan 19 20:25:15.998 TRACE want: signal found waiting giver, notifying    
Jan 19 20:25:15.998 TRACE hyper::proto::h1::conn: flushed({role=client}): State { reading: Init, writing: Init, keep_alive: Idle }
Jan 19 20:25:15.998 TRACE want: signal: Want    
Jan 19 20:25:15.998 TRACE hyper::proto::h1::conn: flushed({role=client}): State { reading: Init, writing: Init, keep_alive: Idle }
Jan 19 20:25:15.998 TRACE want: poll_want: taker wants!    
Jan 19 20:25:15.998 TRACE hyper::client::pool: pool dropped, dropping pooled (("https", binaries.soliditylang.org))
Jan 19 20:25:15.998 TRACE hyper::proto::h1::dispatch: client tx closed
Jan 19 20:25:15.998 TRACE hyper::proto::h1::conn: State::close_read()
Jan 19 20:25:15.998 TRACE hyper::proto::h1::conn: State::close_write()
Jan 19 20:25:15.998 TRACE hyper::proto::h1::conn: flushed({role=client}): State { reading: Closed, writing: Closed, keep_alive: Disabled }
Jan 19 20:25:15.998 TRACE hyper::proto::h1::conn: shut down IO complete
Jan 19 20:25:15.999 TRACE mio::poll: deregistering event source from poller    
Jan 19 20:25:16.000 TRACE want: signal: Closed    
Jan 19 20:25:16.001 TRACE compile:svm_compile: ethers_solc::resolver: resolved 1 versions [Installed(Version { major: 0, minor: 8, patch: 10 })]
Jan 19 20:25:16.001 TRACE compile:svm_compile: ethers_solc::resolver: verifying solc checksum for /home/chinmay/.svm/0.8.10/solc-0.8.10
Jan 19 20:25:16.267 TRACE compile:svm_compile: ethers_solc: compiling sources using a single solc job
Jan 19 20:25:16.269 TRACE compile:svm_compile: ethers_solc: compiling 3 sources with solc "/home/chinmay/.svm/0.8.10/solc-0.8.10"
Jan 19 20:25:16.270 TRACE compile:svm_compile: ethers_solc: start preprocessing 3 sources files
Jan 19 20:25:16.270 TRACE compile:svm_compile: ethers_solc: start resolving libraries
Jan 19 20:25:16.272 TRACE compile:svm_compile: ethers_solc: resolved library import "ds-test/test.sol" at "/home/chinmay/lib/ds-test/src/test.sol"
Jan 19 20:25:16.273 TRACE compile:svm_compile: ethers_solc: resolved all libraries
Jan 19 20:25:16.282 TRACE compile:svm_compile: ethers_solc: compiling 3 files with 0.8.10+commit.fc410830.Linux.gcc. Using 0 cached files
Jan 19 20:25:16.283 TRACE compile:svm_compile: ethers_solc: cached artifacts: "[]"
Jan 19 20:25:16.283 TRACE compile:svm_compile: ethers_solc: compile sources: "["/home/chinmay/lib/ds-test/src/test.sol", "/home/chinmay/src/Contract.sol", "/home/chinmay/src/test/Contract.t.sol"]"
Jan 19 20:25:16.283 TRACE compile:svm_compile: ethers_solc: calling solc with 3 sources
Jan 19 20:25:16.702 TRACE compile:svm_compile: ethers_solc: compiled input, output has error: false
Jan 19 20:25:16.703 TRACE compile:svm_compile:Project::write_cache_file: ethers_solc: inserting 3 sources in file cache
Jan 19 20:25:16.704 TRACE compile:svm_compile:Project::write_cache_file: ethers_solc: source files inserted
Jan 19 20:25:16.704 TRACE compile:svm_compile:Project::write_cache_file: ethers_solc: creating cache file parent directory "/home/chinmay/cache"
Jan 19 20:25:16.705 TRACE compile:svm_compile:Project::write_cache_file: ethers_solc: writing cache file to "/home/chinmay/cache/solidity-files-cache.json"
Jan 19 20:25:16.705 TRACE compile:svm_compile:Project::write_cache_file: ethers_solc::cache: writing cache to json file: "/home/chinmay/cache/solidity-files-cache.json"
Jan 19 20:25:16.708 TRACE compile:svm_compile:Project::write_cache_file: ethers_solc::cache: cache file located: "/home/chinmay/cache/solidity-files-cache.json"
Jan 19 20:25:16.712 TRACE compile:svm_compile: ethers_solc: compiled all sources
success.
Jan 19 20:25:16.726  INFO contract{name=ContractTest.json:ContractTest}: forge::runner: starting tests
Jan 19 20:25:16.726 DEBUG contract{name=ContractTest.json:ContractTest}:test{name=testExample()}: forge::runner: unit-testing func="testExample()" should_fail=false
Jan 19 20:25:16.727 TRACE contract{name=ContractTest.json:ContractTest}:test{name=testExample()}: evm_adapters::sputnik::evm: success status=Succeed(Returned) address=0xb4c79dab8f259c7aee6e5b2aa729821864227e84 gas=171876
Jan 19 20:25:16.727 TRACE contract{name=ContractTest.json:ContractTest}:test{name=testExample()}: forge::runner: setting up
Jan 19 20:25:16.728 TRACE contract{name=ContractTest.json:ContractTest}:test{name=testExample()}:setup{address=0xb4c79dab8f259c7aee6e5b2aa729821864227e84}:call_unchecked{func=setUp}: evm_adapters::sputnik::evm: logs_before=[]
Jan 19 20:25:16.728 TRACE contract{name=ContractTest.json:ContractTest}:test{name=testExample()}:setup{address=0xb4c79dab8f259c7aee6e5b2aa729821864227e84}:call_unchecked{func=setUp}: evm_adapters::sputnik::evm: logs_after=[]
Jan 19 20:25:16.728 TRACE contract{name=ContractTest.json:ContractTest}:test{name=testExample()}:call_unchecked{func=testExample}: evm_adapters::sputnik::evm: logs_before=[]
Jan 19 20:25:16.729 TRACE contract{name=ContractTest.json:ContractTest}:test{name=testExample()}:call_unchecked{func=testExample}: evm_adapters::sputnik::evm: logs_after=[]
Jan 19 20:25:16.729 TRACE contract{name=ContractTest.json:ContractTest}:test{name=testExample()}:call_unchecked{func=failed}: evm_adapters::sputnik::evm: logs_before=[]
Jan 19 20:25:16.729 TRACE contract{name=ContractTest.json:ContractTest}:test{name=testExample()}:call_unchecked{func=failed}: evm_adapters::sputnik::evm: logs_after=[]
Jan 19 20:25:16.730 DEBUG contract{name=ContractTest.json:ContractTest}:test{name=testExample()}: forge::runner: duration=3.209132ms success=true gas_used=254
Jan 19 20:25:16.730  INFO contract{name=ContractTest.json:ContractTest}: forge::runner: done. 1/1 successful duration=3.671621ms
Running 1 test for ContractTest.jso`

**Comment by onbjerg** [comment]
Oh, that's weird. It looks like it's compiling contracts in your home folder (you have a `src` folder in your home directory) instead of the project itself. Try removing `$HOME/src` and `$HOME/lib`. Did you accidentally run `forge init` in your home directory? If so, also delete `$HOME/.git`

**Comment by ChinmayGopal931** [comment]
> Oh, that's weird. It looks like it's compiling contracts in your home folder (you have a `src` folder in your home directory) instead of the project itself. Try removing `$HOME/src` and `$HOME/lib`. Did you accidentally run `forge init` in your home directory? If so, also delete `$HOME/.git`

Ohhh i think I did. Here is what I am etting when I run forge test now
```
chinmay@chinmay-x1carbon:~/forge$ forge test
Error: 
   0: No such file or directory (os error 2)

Location:
   /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/core/src/result.rs:1911

Backtrace omitted.
Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

**Comment by onbjerg** [comment]
The directories `src` and `lib` still exist in `$HOME/forge` but do not exist in `$HOME` now? It's looking for a directory that is not there now (we are only looking for `src` and `lib`)

**Comment by ChinmayGopal931** [comment]
It works now! Thanks so much for your time. I really appreciate it.

**Comment by onbjerg** [comment]
Thank you for your patience and don't hesitate to report back with any issues you encounter, both bugs and things you think could be improved :smile:

**Comment by 0xrin1** [comment]
Whoever this helps, in my case the problem was that I committed the repository from one machine, then cloned down from another and could not understand why the lib assets were missing.

The folder `./lib/ds-test` is a git submodule, to get the content after cloning the existing repo execute:

```
git submodule init
git submodule update
```

After this running `forge test` should just work.

Source: https://stackoverflow.com/a/3796947

**Comment by onbjerg** [comment]
Two alternatives to that as well:

- `git clone --recursive <your repo>` (also clones submodules)
- `forge install` after cloning :)
