### ISSUE TITLE
Current nightly build failing to run on macOS amd64

### ISSUE THREAD

**Issue by devanonon** [gakonst/foundry#531]
I am constantly testing foundry on different machines (yay). Today, the usual installation process yielded a binary which says `zsh: exec format error: forge`. This is using the latest nightly @ `1bb6e0cfbda0a9fb069db8c854a6141ad1c0a08a`.

I then ran `foundryup -b dbbb2482a912e32b4bd7232e3e6f3d215edb456e` to install / build the latest from master and it works fine. Not sure if it's just me with this issue? But I think forcing a new nightly would fix it if others are affected.

**Comment by gakonst** [comment]
cc @wilsoncusack has also hit this

I cannot repro on arm. Triggered a new release, let's see.

**Comment by mattsse** [comment]
this might even be a rust issue on latest nightly

```console
error: internal compiler error: compiler/rustc_mir_transform/src/generator.rs:755:13: Broken MIR: generator contains type &mut tokio::process::ChildStdin in MIR, but typeck only knows about {ResumeTy, &compile::Solc, &T, Vec<u8>, tokio::process::Child, &[u8], &Vec<u8>, tokio::io::util::write_all::WriteAll<tokio::process::ChildStdin>, (), tokio::io::util::flush::Flush<tokio::process::ChildStdin>, impl futures_util::Future<Output = std::result::Result<std::process::Output, std::io::Error>>} and [&compile::Solc, &T]
   --> /Users/Matthias/.cargo/git/checkouts/ethers-rs-c3a7c0a0ae0fe6be/6d7875a/ethers-solc/src/compile.rs:503:90
    |
503 |       pub async fn async_compile_output<T: Serialize>(&self, input: &T) -> Result<Vec<u8>> {
    |  __________________________________________________________________________________________^
504 | |         use tokio::io::AsyncWriteExt;
505 | |         let content = serde_json::to_vec(input)?;
506 | |         let mut child = tokio::process::Command::new(&self.solc)
...   |
519 | |         )
520 | |     }
    | |_____^

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/17d29dcdce9b9e838635eb0adefd9b8b1588410b/compiler/rustc_errors/src/lib.rs:1115:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.60.0-nightly (17d29dcdc 2022-01-21) running on x86_64-apple-darwin

note: compiler flags: -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [optimized_mir] optimizing MIR for `compile::<impl at /Users/Matthias/.cargo/git/checkouts/ethers-rs-c3a7c0a0ae0fe6be/6d7875a/ethers-solc/src/compile.rs:477:1: 573:2>::async_compile_output::{closure#0}`
end of query stack
error: could not compile `ethers-solc`
```

**Comment by gakonst** [comment]
Why would we be hitting a nightly bug though? We compile with stable

**Comment by mattsse** [comment]
right,
unrelated nightly-2022-01-21 bug then.

**Comment by endophysics** [comment]
I also just ran into this problem while doing the install via foundryup from the README. Building the latest master produces a usable binary (using `rustc 1.58.1 (db9d1b20b 2022-01-20)`)

**Comment by onbjerg** [comment]
Can one of you guys run `rustup show` so I can get the target? We might be compiling to a wrong target or something? Also `file forge` so I can see what it says the binary is (for M1 it should say something along the lines of Mach-O arm64)

**Comment by ruvaag** [comment]
Here are the outputs from my system, also experiencing the same zsh exec format error.

`rustup show`:
```
Default host: x86_64-apple-darwin
rustup home:  /Users/ruvaag/.rustup

stable-x86_64-apple-darwin (default)
rustc 1.58.1 (db9d1b20b 2022-01-20)
```

`file forge: forge: cannot open 'forge' (No such file or directory)`

**Comment by endophysics** [comment]
@ruvaag make that ``file `which forge` ``

**Comment by ruvaag** [comment]
> @ruvaag make that `` file `which forge` ``

Thanks @endophysics, the output is `/Users/ruvaag/.foundry/bin/forge: data`
