### ISSUE TITLE
Feature Request "Rest Button"

### ISSUE THREAD

**Issue by carterblank40** [gakonst/foundry#551]
A button that restores expended spell slots

**Comment by gakonst** [comment]
What do you mean? Not sure I understand

**Comment by carterblank40** [comment]
Currently, expended spell slots must be restored individually by clicking each spells restore icon. I would like a button that restores spells and focus pools all at once.

**Comment by onbjerg** [comment]
I think you're in the wrong issue tracker, this is for Foundry, a smart contract development toolchain :smile: No icons or spells here!
