### ISSUE TITLE
Gas snapshots should include the name of the test

### ISSUE THREAD

**Issue by fubhy** [gakonst/foundry#555]
Currently, gas snapshots assume that test case names across the entire project are unique. If there's a duplicate test name, using `--check` or `--diff` doesn't work because it incorrectly points out a deviation in gas cost due to it struggling to properly match the corresponding test case.

Imho, we shouldn't assume that test cases are unique across the entire project. Naming things is already hard enough :-P

Let's include the name of the test file (possibly the entire root-relative path?) in the gas snapshot output?

**Comment by mattsse** [comment]
thanks for raising this.
this makes sense to me, given that we had a similar issue with duplicate test names, let's also make use `<file>:<test>` as identifier.
