### ISSUE TITLE
Fix integration tests and cross-platform test

### ISSUE THREAD

**Issue by onbjerg** [gakonst/foundry#561]
- Cross-platform tests are failing because of directory separators and line endings on Windows
- Integration tests are now passing

**Comment by gakonst** [comment]
For geb, the stop gap would be to use solc 0.6.7 and run it with --no-auto-detect

**Comment by gakonst** [comment]
Specifically for Geb this is what I had seen
![telegram-cloud-photo-size-2-5420255501171668713-y](https://user-images.githubusercontent.com/17802178/150825714-241601c5-bfc6-496e-a07e-7d929e99047c.jpg)

there’s actually 2 bugs

1) the contracts compiled with 0.8.11 outside of [delegate.sol](https://github.com/reflexer-labs/ds-token/blob/38e46ada1fc3136889af95665133ca932e38407a/src/delegate.sol) are actually all contracts with empty code in them so we should not be creating jobs where source has no code for compilation, wonder if we can check that somehow, they are full of comments
2) delegate.sol gets used in both jobs

**Comment by brockelmore** [comment]
we should likely add a hardhat repo as an integration test if at all possible. I know we dont expect 0 overhead for most cases but we should try to find one that "it just works" for and add it

**Comment by onbjerg** [comment]
Updated OP to reflect the latest state of integration tests

**Comment by onbjerg** [comment]
Update, we fixed what we could here and then I fixed geb tests upstream. Our integration tests are now passing!

**Comment by gakonst** [comment]
@onbjerg can we re-enable Geb but only have it run with solc 0.7.6? 

Maybe we should add a flag called "--solc-version" which loads solc from PATH or SOLC_PATH (if it matches the requested version) or from ~/.svm/ or tries to install it via svm?

That way anyone could do "forge test --solc-version x.y.z" and it'd auto select that / download it if not  present

**Comment by onbjerg** [comment]
Yes, let's do that

**Comment by onbjerg** [comment]
Going to keep this open until we re-enable geb
