### ISSUE TITLE
Different function gas usage when using forge and dapp.

### ISSUE THREAD

**Issue by xMasashi** [gakonst/foundry#565]
Does anyone know why there's a difference in the gas usage when using forge and dapp?

<img width="468" alt="Screen Shot 2022-01-24 at 1 54 59 PM" src="https://user-images.githubusercontent.com/66392240/150846110-9e0fdcbd-4f6f-4266-adf6-2aa8325931b6.png">

**Comment by gakonst** [comment]
Is this on the latest version? What does `forge --version` output?

**Comment by brockelmore** [comment]
This comes down to optimizer settings and compiler versioning. Dapp will use the installed version if its compatible with the current pragmas defined, forge will grab latest version that is compatible. having a dapprc that consists of:
```
export DAPP_BUILD_OPTIMIZE=1
export DAPP_SOLC_VERSION=0.8.11
export DAPP_BUILD_OPTIMIZE_RUNS=200
```

will make the tests match identically to the latest version of forge
