### ISSUE TITLE
bug: running --version reports fixed semver (0.1.0) regardless of debug or release target

### ISSUE THREAD

**Issue by sambacha** [gakonst/foundry#569]
the expanded output after 0.1.0 is added for clarity 
```sh
$ forge --version
foundry-cli 0.1.0
```

```sh
$ ./target/debug/forge --version
forge 0.1.0 (8c0fac7 2022-01-24T20:14:32.529120+00:00)
```

```sh
$ ./target/release/forge --version
forge 0.1.0 (8c0fac7 2022-01-24T20:31:45.164274+00:00)
```

**Comment by sambacha** [comment]
creating a debug version vs release should at least be reported something like 0.1.0-SNAPSHOT or 0.1.0-DEBUG imho

**Comment by gakonst** [comment]
I think we don't really need to differentiate between debug / release in the --version as there's no diff between them in features

**Comment by sambacha** [comment]
there actually is

**Comment by sambacha** [comment]
The output for version should be dependent upon input, no?
