### ISSUE TITLE
tarball not found at `nightly-${SHA}`

### ISSUE THREAD

**Issue by llllvvuu** [gakonst/foundry#571]
This does not exist: https://github.com/gakonst/foundry/releases/download/nightly-7d461216bb15dd963f57a25ccc53a1a74c5081a8/foundry_nightly_darwin_arm64.tar.gz
This exists: https://github.com/gakonst/foundry/releases/download/nightly/foundry_nightly_darwin_arm64.tar.gz
The SHA is correct according to: https://github.com/gakonst/foundry/releases

perhaps the release was not done properly: https://github.com/gakonst/foundry/blob/master/.github/workflows/release.yml so we did not get the `nightly-${SHA}` tag uploaded: https://github.com/gakonst/foundry/tags

in any case running `foundryup` with `s/FOUNDRYUP_TAG="nightly-${SHA}"/FOUNDRYUP_TAG="nightly"` is a workaround

**Comment by onbjerg** [comment]
Hey, we had some issues with the release workflow. It should work now. Let me know :slightly_smiling_face:

**Comment by llllvvuu** [comment]
very nice! confirmed all steps working with `bash -x`
