### ISSUE TITLE
Wrong `BIN_TARBALL_URL` and `MAN_TARBALL_URL` in installation script 

### ISSUE THREAD

**Issue by guoliu** [gakonst/foundry#575]
When installing on macOS (BigSur), `foundryup` gives:
```
tar: Error opening archive: Unrecognized archive format
```

It seems like `BIN_TARBALL_URL` and `MAN_TARBALL_URL` are wrong, they are pointing at `https://github.com/gakonst/foundry/releases/download/nightly-d1556069d6d42ae010dfa0a77cb99a0b020469ea/foundry_nightly_darwin_amd64.tar.gz` and `https://github.com/gakonst/foundry/releases/download/nightly-d1556069d6d42ae010dfa0a77cb99a0b020469ea/foundry_man_nightly.tar.gz` respectively.

After replacing the above two URL with `https://github.com/gakonst/foundry/releases/download/nightly/...` the script worked perfectly.

**Comment by onbjerg** [comment]
We're currently updating our release workflow and there have been some hiccups. Should be resolved on next nightly release (soon). The download URL you replaced it with is an older nightly version - the most up to date is `https://github.com/gakonst/foundry/releases/download/nightly-ecfbcabfdcee603bb46c54b910d3656b560606c6/foundry_nightly_darwin_amd64.tar.gz`

**Comment by onbjerg** [comment]
I manually changed the ref the tag was pointing to, so this should be fixed now. Apologies for the inconvenience :(

**Comment by guoliu** [comment]
Thank you for the quick response @onbjerg !
