### ISSUE TITLE
Cast seems to be missing support for legacy transactions on BSC

### ISSUE THREAD

**Issue by optionseskimo** [gakonst/foundry#579]
When trying to make a function call to a contract on BSC using `cast send`, it fails with `custom error: EIP-1559 not activated`.

I've been able to deploy contracts to BSC using `forge create --legacy`, but that legacy parameter seems to be missing from `cast`.

Is there another way to send legacy, non-EIP-1559 transactions when using `cast`?

If not, I think it's a feature worth adding, as right now, `cast` doesn't automatically detect that BSC is being used and that it doesn't support EIP-1559.

**Comment by mattsse** [comment]
we already have

https://github.com/gakonst/foundry/blob/ff46022b58f6653ef4fc77536b0f8f6a3bb71f7e/cli/src/cmd/create.rs#L121-L132

but this is only in use for `create` rn

In `send` we're currently limited to `Eip1559`

https://github.com/gakonst/foundry/blob/9de25d1928da362cd3b185ebaccc0e3d00aee2c8/cast/src/lib.rs#L234

adding a similar `is_legacy` check should do the trick here as well

this leaves us with two tasks

- [ ] add BSC id to `is_legacy`
- [ ] check `is_legacy` is in build_tx (should perhaps return `TypedTransaction`?)

**Comment by zed-wong** [comment]
--legacy worked for me
