### ISSUE TITLE
Fuzz runs are not configurable

### ISSUE THREAD

**Issue by onbjerg** [gakonst/foundry#590]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (9de25d1 2022-01-26T14:37:22.300499221+00:00)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

Even though the number of fuzz runs is configurable in `foundry.toml` and as an environment variable, it is not actually honored.

To reproduce:

- Clone any repository with a fuzz test (for example Rari-Capital/solmate)
- Run `FOUNDRY_FUZZ_RUNS=1 forge test`
- See that the fuzz tests are still run with 256 runs.

There is also no `--fuzz-runs` option for `forge test`

**Comment by ATV3320** [comment]
Same issue, even watching the new tutorial didn't help (https://youtu.be/ADyg61bcN_0), he simply ignored that it wasn't happening.

**Comment by mds1** [comment]
This is now supported, you can use the `FOUNDRY_FUZZ_RUNS ` env var or the `runs` key in the `[fuzz]` section of your `foundry.toml`, see https://book.getfoundry.sh/reference/config/testing#fuzz for more info
