### ISSUE TITLE
`cast interface` doesn't include events in the interface

### ISSUE THREAD

**Issue by mds1** [gakonst/foundry#594]
### Component

Cast

### Describe the feature you would like

Currently `cast interface <addr>` returns an interface containing a contract's functions, but not its events. Events are part of a contract's ABI so it would be nice to include them in the generated interface. One use case is for testing event emissions in forge tests, another is for modifying the output to serve as the inputs for e.g. an ethers.js human-readable ABI definition

**Comment by odyslam** [comment]
I read somewhere that it makes sense not to have events in an Interface, as it dictates how smart contracts should interact with one another. Events concern the off-chain world and thus should be omitted from interfaces. 

Curious on what others have to say, but it should be simple enough to add.

**Comment by Boda805** [comment]
![image](https://user-images.githubusercontent.com/46383749/151874372-3eb85723-c563-4bc7-a267-c938ad4c6e3d.png)

Hello, I'm trying to get some practice writing rust and got the basics of this scaffolded out. So based on @odyslam comment, is this behavior okay by default? Or flag to include/exclude?

**Comment by gakonst** [comment]
Yes, supportive of this feature for sure. Make sure you also get the `indexed` part!

**Comment by onbjerg** [comment]
Closed in #664
