### ISSUE TITLE
`forge` downloads amd64 `solc` binary for aarch64 Linux

### ISSUE THREAD

**Issue by nikitastupin** [gakonst/foundry#597]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (8ccfe49 2022-01-25T13:43:18.881673196+00:00)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

Hi 👋 

When I run `forge test` it automatically downloads the `$HOME/.svm/0.8.11/solc-0.8.11` binary for Linux to compile my contracts. However, it downloads amd64 version of the binary even though I'm running aarch64 version of Linux.

When I manually replace the binary with aarch64 version of the binary `forge test` puts amd64 version back.

What could I do in this case to use `forge test` on aarch64 Linux?

Thanks!

**Comment by onbjerg** [comment]
The bug is in svm-rs [here](https://github.com/roynalnaruto/svm-rs/blob/5518296f756458f878958a76b985b6fe423acad4/src/platform.rs#L12-L31).

Then we'd need to:

1. Update svm-rs in ethers-solc
2. Update ethers-solc here in Foundry

**Comment by onbjerg** [comment]
Ok, so it doesn't seem like there are any Solidity arm64 binaries available going by https://github.com/ethereum/solc-bin.

If you want to run with a custom version, try passing the `--no-auto-detect` flag - it should keep the binary intact :smile:

**Comment by mattsse** [comment]
nevertheless we should check for arm on svm-rs cc @roynalnaruto

**Comment by onbjerg** [comment]
True, the platform detection should be more robust by checking the arch in general

**Comment by roynalnaruto** [comment]
@onbjerg @mattsse I had noticed this some time ago, probably slipped out of my TODOs. The above PR looks good, although it would show an M1 macbook as `unsupported` (check my comment on the PR).

**Comment by onbjerg** [comment]
This should be fixed the next time we do an update of svm-rs in ethers-solc and update ethers-solc here
