### ISSUE TITLE
Ledger Nano S failure

### ISSUE THREAD

**Issue by kargakis** [gakonst/foundry#607]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (8a61027 2022-01-27T00:21:53.956016803+00:00)

### What command(s) is the bug in?

forge create

### Operating System

Linux

### Describe the bug

Getting the following error when trying to deploy with a Ledger Nano S:
```
Error: 
   0: hidapi error: hid_error is not implemented yet

Location:
   /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1911
```
My Ledger version info:
* Secure Element: 2.1.0
* Microcontroller: 1.12
* Bootloader: 0.11
* Ethereum app: 1.9.17

**Comment by gakonst** [comment]
I suspect this is unrelated to us: https://github.com/ruabmbua/hidapi-rs/issues/68#issuecomment-790823253

**Comment by joshieDo** [comment]
just to expand on the issue linked above:

> It looks like you are either using mac, or some platform with libusb. In that case, acquiring a meaningful error message is not implemented yet.
Since we use libusb as a backend for `ethers-rs`, we cannot take his suggestion.

However, this "only" limits us getting a valid USB error (from my understanding). Are you able to use your ledger otherwise? Is it possible that the device is locked or taken by another process when you try to call forge or cast with it ?

**Comment by gakonst** [comment]
> Are you able to use your ledger otherwise? Is it possible that the device is locked or taken by another process when you try to call forge or cast with it ?

Good q - that's what I thought as well

**Comment by kargakis** [comment]
Thanks folks, you are right, there was a bluetooth dongle that was messing with my ledger. After connection only the wallet I was able to proceed with the deployment.
