### ISSUE TITLE
Default chain ID should not be 1

### ISSUE THREAD

**Issue by mds1** [gakonst/foundry#608]
### Component

Forge

### Describe the feature you would like

In #603, the chain ID was set to default to 1 if not specified (this may have already been the default behavior, though the rest still applies). Defaulting to mainnet's chain ID is not great for a few reason:
- `permit`s and other signatures generated during tests are valid and can be replayed on mainnet
- When RPC support is added, frontend devs will change the network in metamask to the local forge node. Adding this network requires will require specifying a chain ID of 1, meaning any development transaction is now a valid mainnet transaction

We should default to 99 (like dapptools), 31337 (like hardhat), or really any arbitrary number [not in use](https://chainlist.org/)

**Comment by mattsse** [comment]
cc @onbjerg

**Comment by onbjerg** [comment]
Yeah, it was already the default behavior. https://github.com/gakonst/foundry/pull/609
