### ISSUE TITLE
forge test -vv not printing log events when function argument not used

### ISSUE THREAD

**Issue by milancermak** [gakonst/foundry#617]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (8a61027 2022-01-27T00:23:10.399592+00:00)

### What command(s) is the bug in?

forge test -vv

### Operating System

macOS (M1)

### Describe the bug

Steps to reproduce:

* Run `forge init`
* Add this function to `Contract.t.sol`
```solidity
    function testExample() public {
        emit log_bytes32(bytes32(abi.encodePacked(uint256(0))));
    }
```
* run `forge test -vv`, the output should contain the following:
```
Logs:
  0x0000000000000000000000000000000000000000000000000000000000000000
```
* update the `testExample` function from above to accept an unused parameter, e.g.
```solidity
    function testExample(uint256 nope) public {
        emit log_bytes32(bytes32(abi.encodePacked(uint256(0))));
    }
```
* run `forge test -vv` again; notice the output does not contain any log message 😢

**Comment by onbjerg** [comment]
Fuzzer tests do not collect logs because they are run more than once which (in most cases) would lead to `n` duplicate logs with different values (where `n` is the number of fuzz runs, default is 256).

**Comment by milancermak** [comment]
Fair enough, that makes sense. Was my first time using Foundry, so it got me really confused. Thank you for taking the time to explain it.
