### ISSUE TITLE
Forge-generated abi lacks "name" and "internalType" fields when structs are passed as function args

### ISSUE THREAD

**Issue by juniorbeef** [gakonst/foundry#618]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (4caf64f 2022-01-28T00:26:02.267938+00:00)

### What command(s) is the bug in?

forge build

### Operating System

macOS (M1)

### Describe the bug

I am using `forge build` to compile my contracts, and have noticed that the resulting ABI lacks `name` and `internalType` fields (under `inputs/components` in the json) when I pass struct arguments. These fields are present when I just run `solc` directly or when I compile the same contract using hardhat.

The forge-produced abi works, but I'm using it with the `ethers-rs` `abigen` macro, and `abigen` produces more ergonomic bindings when these fields are present (you can pass actual rust struct values as args rather than just a tuple), so it would be nice to have them.

I'd be happy to try fixing this if it would be helpful, but the flow of data from solc through to the forge output wasn't totally obvious to me from a really quick look, so I could use some pointers as to where to look in the source.

Here's a small example contract:

```
pragma solidity =0.8.6;

contract StructArg {
    struct Arg {
        address addressArg;
        bytes bytesArg;
    }
    function firstAddr(Arg[] calldata args) external pure returns (address){
        return args[0].addressArg;
    }
}

```

This is the ABI produced by forge:

```
[
    {
      "type": "function",
      "name": "firstAddr",
      "inputs": [
        {
          "internalType": "struct StructArg.Arg[]",
          "name": "args",
          "type": "tuple[]",
          "components": [
            {
              "type": "address"
            },
            {
              "type": "bytes"
            }
          ]
        }
      ],
      "outputs": [
        {
          "internalType": "address",
          "name": "",
          "type": "address"
        }
      ],
      "constant": null,
      "stateMutability": "nonpayable"
    }
  ]
```

And this is the ABI produced directly by solc (and hardhat):
```
[
  {
    "inputs": [
      {
        "components": [
          {
            "internalType": "address",
            "name": "addressArg",
            "type": "address"
          },
          {
            "internalType": "bytes",
            "name": "bytesArg",
            "type": "bytes"
          }
        ],
        "internalType": "struct StructArg.Arg[]",
        "name": "args",
        "type": "tuple[]"
      }
    ],
    "name": "firstAddr",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  }
]
```

**Comment by onbjerg** [comment]
This is most likely something missing in ethers-solc in the ethers-rs repo (https://github.com/gakonst/ethers-rs). Ping @mattsse as I am not suuuuper comfortable in that crate yet, so he probably has some better insights/pointers for you if you want to try and take this on :slightly_smiling_face:

**Comment by joshieDo** [comment]
Just as a side-note, but it would be great not to include `"constant": null,` as well, if null. Although valid abi, there are some services (eg. `graph-node`) that crash if passed that [which I have been removing manually...].

**Comment by brockelmore** [comment]
This is caused upstream in https://github.com/rust-ethereum/ethabi. I think @gakonst had asked them about including internal type information before, but I dont know if he made progress.

**Comment by gakonst** [comment]
Tried to find the issue where we were discussing this, maybe @mattsse remembers? It wasn't clear how we should approach it IIRC

**Comment by mattsse** [comment]
this is probably due some lossy conversion when we're going from `CompilerOutput` -> `Artifact`

will have at the nested components type, we're probably missing something when deserializing.

**Comment by mattsse** [comment]
I looked into this and this happens inside `ethabi::Param`,

a `Param` represents an input in the context of a function, a `Param` stores its `components` as a list of `ParamType` named `kind`

https://github.com/rust-ethereum/ethabi/blob/master/ethabi/src/param.rs#L32-L33

https://github.com/rust-ethereum/ethabi/blob/451d029c69a1fce7c4d57cc117e985a31dc53627/ethabi/src/param_type/param_type.rs#L17-L40

Unfortunately, a `ParamType` only knows about the `type`, the name and internaltype field is simply omitted when parsing json to `ethabi::Contract`

So this is lossy, the only way to mitigate this would be to roll our own `Contract` type

**Comment by juniorbeef** [comment]
Thanks all for taking a look at this. I now see what @mattsse is saying: looks like the actual type info I want gets dropped right on this line:

https://github.com/rust-ethereum/ethabi/blob/6f18e11621d29b6cd978ef39b48fa572b823bb80/ethabi/src/param.rs#L156

It seems like ParamType should perhaps have a Param instead of a ParamType here, though I have no idea what else that might end up breaking:

https://github.com/rust-ethereum/ethabi/blob/6f18e11621d29b6cd978ef39b48fa572b823bb80/ethabi/src/param_type/param_type.rs#L39

Is changing this upstream in ethabi an option? I don't suspect I'll get to it any time soon as I know very little about the eth ABI at the moment, though I'll keep it in mind.

**Comment by gakonst** [comment]
I'd give the upstream change a try, even if it causes some small downstream breakage.

If that's not possible, we have been toying with the idea of re-implementing ethabi in a way that we have more control over its performance and fix any of our issues without causing downstream breakages.

**Comment by mattsse** [comment]
we're emitting the complete abi now
