### ISSUE TITLE
Forge test obscures stack to deep errors

### ISSUE THREAD

**Issue by alcibiadeseth** [gakonst/foundry#619]
### Component

Forge

### Have you ensured that all of these are up to date?

- [x] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (4caf64f 2022-01-27T17:38:08.462704+00:00)

### What command(s) is the bug in?

forge test

### Operating System

macOS (M1)

### Describe the bug

I had a battery of tests for a contract I noticed were not running, I dug into this a bit, and it looks like the contract was compiling just fine, but via forge test, was silently failing to construct during `setUp`. I played around and removed a few functions with 10 arguments, look like something was causing the stack to be to deep, which may be other stuff going on in the test contract itself, however, `forge` doesn't produce an error message of any kind for this, it just skips the tests.

**Comment by gakonst** [comment]
cc @mattsse

**Comment by gakonst** [comment]
Should no longer be an issue since we now print the entire compiler error.
