### ISSUE TITLE
bug(forge): flatten includes unnecessary `;`

### ISSUE THREAD

**Issue by DeGatchi** [gakonst/foundry#641]
### Component

Forge

### Have you ensured that all of these are up to date?

- [x] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (708f48f 2022-01-30T00:25:30.497347+00:00)

### What command(s) is the bug in?

forge flatten

### Operating System

macOS (amd)

### Describe the bug

When flattening a contract that inherits multiple contracts, majority of the contracts' closing braces had semi colons at the end and just wondering around after comments.

![image](https://user-images.githubusercontent.com/72078332/151720407-ddfc0a69-07bf-4b17-b63c-b49a8412ceda.png) 

![image](https://user-images.githubusercontent.com/72078332/151720374-3db75dd3-c498-4954-abad-ccc522143c31.png)

![image](https://user-images.githubusercontent.com/72078332/151720880-0129169c-cdfd-4119-9e63-4542d36a420c.png)

**Comment by mattsse** [comment]
cc @rkrasiuk

**Comment by rkrasiuk** [comment]
@mattsse thanks for tagging, looking over it rn
