### ISSUE TITLE
Foundry custom project set up not working as expected

### ISSUE THREAD

**Issue by FredCoen** [gakonst/foundry#642]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

latest

### What command(s) is the bug in?

forge test

### Operating System

macOS (M1)

### Describe the bug

Using forge in withing hardhat project therefore don't want the default forge project set up. Trying to customize it. However config file doesn't seem to take effect. For now simply tried it out by adding foundry.toml file with:

`[default]
out='outTest'
`

when running forge test, still adds artifacts to out directory as opposed to outTest

**Comment by mattsse** [comment]
thanks,
could you try running `forge config` and check the `out` value?
perhaps we're not passing the out dir correctly in some circumstances

**Comment by FredCoen** [comment]
seems i had to forge binaries installed and therefore was using an old version. Have removed the binary of the older version and am now handling version with foundryup. Config values print as expected and now take effect. Think we can close this one. Thanks!

**Comment by mattsse** [comment]
awesome!
