### ISSUE TITLE
`forge run` and `forge remove` share alias

### ISSUE THREAD

**Issue by zk-tarts** [gakonst/foundry#651]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (8107afe 2022-01-31T10:46:25.871921953+00:00)

### What command(s) is the bug in?

forge run, forge remove

### Describe the bug

`forge run` and `forge remove` both have the alias of `forge r`.  
I suggest that one of them gets changed to something different.
see line 32 and line 50 of https://github.com/gakonst/foundry/blob/master/cli/src/opts/forge.rs

**Comment by mattsse** [comment]
nice catch,
proposing `forge rm` instead #653
