### ISSUE TITLE
yul optimizer config

### ISSUE THREAD

**Issue by fubhy** [gakonst/foundry#652]
### Component

Forge

### Describe the feature you would like

Would be cool if we could configure every aspect of the yul optimizer options: https://github.com/ethereum/solidity/blob/v0.8.11/libsolidity/interface/OptimiserSettings.h

Without knowing too much about the inner workings, especially with that pesky `Stack too deep when compiling inline assembly ...`  sometimes the only way to figure out what's going on is to play around with the optimizer steps.

**Comment by sambacha** [comment]
Just a note, that before version 0.8.6 omitting the 'enabled' key was not equivalent to setting
 it to false and would actually disable all the optimizations.
 https://docs.soliditylang.org/en/latest/using-the-compiler.html#compiler-input-and-output-json-description

**Comment by mattsse** [comment]
Opened https://github.com/gakonst/ethers-rs/pull/868 that adds the necessary types to configure the details
needs foundry config companion PR

**Comment by mattsse** [comment]
@fubhy, please have a look at this https://github.com/gakonst/foundry/pull/678?
