### ISSUE TITLE
Flaky test on CI

### ISSUE THREAD

**Issue by gakonst** [gakonst/foundry#658]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

 forge 0.1.0 (8d84701 2022-02-01T00:34:27.479773+00:00)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

There's a flaky test on CI
![telegram-cloud-photo-size-2-5463169594622591722-y](https://user-images.githubusercontent.com/17802178/152182492-07c2470c-cfbd-466f-bc76-aa31998d4592.jpg)

The println makes me believe the issue is during the svm installation step [here](https://github.com/gakonst/ethers-rs/blob/8b9a18ce017d40f99ee5f74da5c4fbb8a47538f9/ethers-solc/src/compile.rs#L411-L413), which proceeds to call `svm::install`.

I think the offending code is either the [`std::io::copy`](https://github.com/roynalnaruto/svm-rs/blob/71b47750044d4f2a0e4917c707c8b4423ba41b36/src/lib.rs#L110-L149) or the `std::fs::File::create` above it

@mattse mentioned that if https://github.com/gakonst/ethers-rs/pull/802 doesn't address this, we should consider using a lockfile, given that our existing mutexes in ethers-solc seem to not be getting hit

**Comment by onbjerg** [comment]
Dupe of #442?

**Comment by gakonst** [comment]
Oops - yes.
