### ISSUE TITLE
Add aarch64 Linux to the nightly build

### ISSUE THREAD

**Issue by nikitastupin** [gakonst/foundry#684]
### Component

Foundryup

### Describe the feature you would like

Hey 👋 

Can we add the aarch64 Linux target to the nightly build? It would be nice so that me and other aarch64 Linux users won't need to rebuild from sources each time.

It should be just adding a few lines to [`release.yml`](https://github.com/gakonst/foundry/blob/63644de7dccb05a42f04f2829fd4007049607788/.github/workflows/release.yml).

Thanks!

**Comment by onbjerg** [comment]
The Solidity compiler does not have ARM builds, so I'm not sure it would make much sense - can you elaborate a little?

**Comment by nikitastupin** [comment]
That's true, Solidity compiler doesn't provide pre-compiled ARM builds. However, (1) it's still possible to use `cast` without a Solidity compiler and (2) Solidity compiler updates not so frequently so I can compile it manually and use with `forge`; at the same time both `forge` and `cast` gets bug fixes and new features almost every day and it's good to just download a binary (instead of compiling every day) to test out new features 😄

**Comment by gakonst** [comment]
@nikitastupin Do you think you could manually compile and create a repo with ARM builds for Solc, and host it on Github? Then we could use that as source of truth instead

**Comment by nikitastupin** [comment]
I think I could invest a couple of hours trying to automate ARM build 😃 It would help myself in the future and others.

Also, the https://github.com/ethereum/solidity/issues/11351 issue tracks Solidity's progress on the same issue. They consider it low-priority though.

**Comment by gakonst** [comment]
That's be awesome. Appreciate it. Let us know when you have it, so we integrate it in svm-rs.

 I think we cannot depend on it getting solved at core Solidity soon, we've asked them directly very recently and got the same answer

**Comment by nikitastupin** [comment]
It seems that it's not that hard to automate build aarch64-linux builds. I started working on it at https://github.com/nikitastupin/solc. The core is GitHub Actions workflow that I manually trigger to run a build process for a specified version of Solidity compiler and then uploads binary back to the repo via Releases.

**Comment by nikitastupin** [comment]
A quick update on https://github.com/nikitastupin/solc. I decided to keep it simple and store binaries in the repo instead of Releases and uploaded `v0.8.*`, `v0.7.*`, `v0.6.*`, and some of `v0.5.*` binaries. I have experienced issues building `v0.4.*` and some of `v0.5.*` binaries. I'm gonna dig into it later.

Does the repo structure looks good for you? Any other comments?

**Comment by gakonst** [comment]
This looks great. Flagged it to @roynalnaruto, he'll incorporate this in svm-rs.

**Comment by roynalnaruto** [comment]
@nikitastupin Hi, that's great work! I wish to make an addition to your `solc` repository to add a `list.json` of all the binaries (for Linux Aarch64) and the tags that were used and an SHA256 checksum of the binary. Something similar to this:
https://binaries.soliditylang.org/macosx-amd64/list.json

I cannot see the `tag` value you used to build and publish the existing binaries, could you help me out with that?

I'll wrap up the rest of the changes required and file a PR to your repo by tmrw :)
