### ISSUE TITLE
Forge Test run as address

### ISSUE THREAD

**Issue by Mrostgaard** [gakonst/foundry#686]
Hey

I've looked through the Forge documentation and the foundry book https://onbjerg.github.io/foundry-book/ and haven't been able to find a convenient way for me to control which address is making a call to my smart contract. 

An example: 
I have a smart contract which implements a onlyOwner modifier and wants to check if the current caller have access to execute the function. 

```solidity
contract MyContract is OnlyOwner {

    construct () {
        //setup...
    }

    function myProctedFunction() external onlyOwner {
         // Execute some code
    }
}
```

In hardhat you would do something like:
```javascript
describe("A test", function(){

    ... Initial setup for the contract ....

    it("Fails because it is not owner", function(){
        await expect(
            myContract.connection(notOwner.address).myProctedFunction()
        ).to.throw()
    }
}
```
How do i do this in forge? I can see that the interface with HEVM_ADDRESS has a 'prank' interface and that is pretty close to what i want to do, but my contract is not a interface, I don't want to mock the functionality I want to test the functionality from different addresses. Is it even possible?

**Comment by gakonst** [comment]
Yeah `prank` is what you're looking for. See [here](https://github.com/gakonst/foundry/blob/master/evm-adapters/testdata/CheatCodes.sol#L200-L201) for how it's used in a test.
