### ISSUE TITLE
Report in tests if contract exceeds max code size

### ISSUE THREAD

**Issue by wilsoncusack** [gakonst/foundry#687]
### Component

Forge

### Describe the feature you would like

It would be nice if tests would warn/fail if contract exceeds the max code size. Maybe this is too network specific, but I was recently frustrated trying to deploy something I had been testing and discovering the contract had gotten too large to deploy. I am used to HH tests failing if contract is too large.

**Comment by onbjerg** [comment]
We were previously asked to ignore the contract code size limit for tests by default for tests as they are not usually deployed anyway, so the warning wouldn't make sense. I'm curious if you're deploying the tests? Normal contracts should still generate the warning

**Comment by wilsoncusack** [comment]
Sorry, I am not referring to a test contract. I am referring to the contract I am testing. The contract I am using/deploying was too large. 

Of course don't worry about monitoring size of the test contract 😁

**Comment by onbjerg** [comment]
Oh that's strange, it should already do that when compiling. Do you have some example code?
