### ISSUE TITLE
Using OpenZeppelin upgradable smart contracts with forge

### ISSUE THREAD

**Issue by Ignacio-Freire** [gakonst/foundry#693]
### Discussed in https://github.com/gakonst/foundry/discussions/692

<div type='discussions-op-text'>

<sup>Originally posted by **Ignacio-Freire** February  7, 2022</sup>
Hello everyone,

I've been searching on the docs, issues and discussions for the last 2 days but I haven't been able to find anything related to this. So I decided to start a discussion and check if anyone was able to overcome this issue.

The project I'm working at has a central "controller" smart contract that is upgradable, so far we have 3 versions. While using hardhat in addition to the OpenZeppelin `test-helpers`, it's really easy to deploy the version 1 with all the parameters and then upgrade to version 3 while keeping all the data.                           

This is done by using `deployProxy `and then `upgradeProxy`. 

I'm guessing the way to do this on Foundry could also be deploying the ProxyAdmin, the Proxy and the SC manually to later upgrade it.

I was wondering if there's anything similar to the `test-helpers` implemented with Foundry or if anyone has an example on how to do it.

Thanks a lot!

</div>

**Comment by gakonst** [comment]
Could you add a strawman proposal of your ideal UX for this feature in Foundry?

**Comment by Ignacio-Freire** [comment]
Hello!

Thanks for the response. 

So in the end not many lines were needed to implement the upgradable contracts with Foundry. It might not be worthy to add as an extra feature.

Nonetheless, here's the code I'm using to deploy a ControllerV1 contract and then upgrade straight to a V4. You can check if it's worth it to look into it a little bit more.


**Test File**

```
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.0;

import "@openzeppelin/contracts/proxy/transparent/ProxyAdmin.sol";
import "@openzeppelin/contracts/proxy/transparent/TransparentUpgradeableProxy.sol";
import "./ControllerV1.sol";
import "./ControllerV4.sol";
import "ds-test/test.sol";

contract OZUpgradeTest is DSTest {
    ControllerV1 controllerV1;
    ControllerV4 controllerV4;
    TransparentUpgradeableProxy transparentProxy;
    ProxyAdmin proxyAdmin;

    ControllerV4 latestController;

    function setUp() public {
      
      controllerV1 = new ControllerV1();

      controllerV4 = new ControllerV4();

      transparentProxy = new TransparentUpgradeableProxy(address(controllerV1), address(this), "");

      proxyAdmin = new ProxyAdmin();
      
      transparentProxy.changeAdmin(address(proxyAdmin));

      ControllerV1(address(transparentProxy)).initialize(
        address(this), 
        address(this), 
        address(this));

      proxyAdmin.upgrade(transparentProxy, address(controllerV4));

      latestController = ControllerV4(address(transparentProxy));
     }

    function testControllerDeploy() public {
      address admin = latestController.admin(); 
      uint version = latestController.getVersion();
      assertEq(version , 4);
      assertEq(admin, address(this));
    }
}
```

**ControllerV1** 

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "@openzeppelin/contracts-upgradeable/utils/ContextUpgradeable.sol";
import "@openzeppelin/contracts-upgradeable/security/PausableUpgradeable.sol";
import "@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol";

interface IController {
    function admin() external view returns (address);
}

contract ControllerV1 is IController, Initializable, ContextUpgradeable, PausableUpgradeable {
    
    // IMPORTANT!: For future reference, when adding new variables for following versions of the controller. 
    // All the previous ones should be kept in place and not change locations, types or names.
    // If thye're modified this would cause issues with the memory slots.

    address override public pauseAdmin;
    address override public admin;
    address override public recoveryAdmin;

    function getVersion() external pure returns (uint256) {
        return 1;
    }
}
```

**ControllerV4** 

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "@openzeppelin/contracts-upgradeable/utils/ContextUpgradeable.sol";
import "@openzeppelin/contracts-upgradeable/security/PausableUpgradeable.sol";
import "@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol";

interface IController {
    function admin() external view returns (address);
}

contract ControllerV4 is IController, Initializable, ContextUpgradeable, PausableUpgradeable {
    
    // IMPORTANT!: For future reference, when adding new variables for following versions of the controller. 
    // All the previous ones should be kept in place and not change locations, types or names.
    // If thye're modified this would cause issues with the memory slots.

    address override public pauseAdmin;
    address override public admin;
    address override public recoveryAdmin;

    function getVersion() external pure returns (uint256) {
        return 4;
    }
}
```

**Comment by wdv4758h** [comment]
I have a sort of related question.

I got OpenZeppelin upgradable smart contracts, and I used to deploy/upgrade via their `upgrades.deployProxy` and `upgrades.upgradeProxy` in with Hardhat.

I know that I can use my existing JavaScript to keep deploying the contract. But I'm wondering if there is a convenient way to do it with `forge create`? When I use `forge create`, the `initialize` function in the contract seems not be executed. I guess that was handled in the [upgrades](https://github.com/OpenZeppelin/openzeppelin-upgrades) tool.

Something like a `--openzeppelin-upgrades` flag will be great. But I'm not sure if it's feasible.

**Comment by tonisives** [comment]
I used a simple script to deploy UUPS impementation, and then the proxy with this implementation address and initialize call:

### the deploy script
```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.17;

import "forge-std/Script.sol";
import {ERC1967Proxy} from "../../src/lib/proxy/ERC1967Proxy.sol";
import {AuditPurchase} from "../../src/AuditPurchase.sol";

contract AuditPurchaseScript is Script {
  function setUp() public {}

  function run() public {
    // read private from env variable
    uint256 privateKey = vm.envUint("TEST_DEPLOYMENT_KEY");
    vm.startBroadcast(privateKey);

    AuditPurchase auditPurchaseImp = new AuditPurchase();

    ERC1967Proxy auditPurchaseProxy = new ERC1967Proxy(
      address(auditPurchaseImp),
      abi.encodeWithSignature("initialize(uint256)", 0.001 ether)
    );

    vm.stopBroadcast();
  }
}
```

### the implementation
```solidity
contract AuditPurchase is OwnableUpgradeable, UUPSUpgradeable, AuditPurchaseStorageV1 {
  function initialize(uint256 price_) public initializer {
    __Ownable_init();
    __UUPSUpgradeable_init();
    price = price_;
  }
}
```

### the proxy contract
```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;

import {ERC1967UpgradeUpgradeable} from "@openzeppelin-upgradeable/proxy/ERC1967/ERC1967UpgradeUpgradeable.sol";
import {Proxy} from "@openzeppelin/proxy/Proxy.sol";

contract ERC1967Proxy is Proxy, ERC1967UpgradeUpgradeable {
    constructor(address _logic, bytes memory _data) payable {
        _upgradeToAndCall(_logic, _data, false);
    }

    /// @dev The address of the current implementation
    function _implementation() internal view override returns (address) {
        return ERC1967UpgradeUpgradeable._getImplementation();
    }
}
```

**Comment by itsabinashb** [comment]
> I used a simple script to deploy UUPS impementation, and then the proxy with this implementation address and initialize call:
> 
> ### the deploy script
> ```solidity
> // SPDX-License-Identifier: UNLICENSED
> pragma solidity ^0.8.17;
> 
> import "forge-std/Script.sol";
> import {ERC1967Proxy} from "../../src/lib/proxy/ERC1967Proxy.sol";
> import {AuditPurchase} from "../../src/AuditPurchase.sol";
> 
> contract AuditPurchaseScript is Script {
>   function setUp() public {}
> 
>   function run() public {
>     // read private from env variable
>     uint256 privateKey = vm.envUint("TEST_DEPLOYMENT_KEY");
>     vm.startBroadcast(privateKey);
> 
>     AuditPurchase auditPurchaseImp = new AuditPurchase();
> 
>     ERC1967Proxy auditPurchaseProxy = new ERC1967Proxy(
>       address(auditPurchaseImp),
>       abi.encodeWithSignature("initialize(uint256)", 0.001 ether)
>     );
> 
>     vm.stopBroadcast();
>   }
> }
> ```
> 
> ### the implementation
> ```solidity
> contract AuditPurchase is OwnableUpgradeable, UUPSUpgradeable, AuditPurchaseStorageV1 {
>   function initialize(uint256 price_) public initializer {
>     __Ownable_init();
>     __UUPSUpgradeable_init();
>     price = price_;
>   }
> }
> ```
> 
> ### the proxy contract
> ```solidity
> // SPDX-License-Identifier: MIT
> pragma solidity ^0.8.4;
> 
> import {ERC1967UpgradeUpgradeable} from "@openzeppelin-upgradeable/proxy/ERC1967/ERC1967UpgradeUpgradeable.sol";
> import {Proxy} from "@openzeppelin/proxy/Proxy.sol";
> 
> contract ERC1967Proxy is Proxy, ERC1967UpgradeUpgradeable {
>     constructor(address _logic, bytes memory _data) payable {
>         _upgradeToAndCall(_logic, _data, false);
>     }
> 
>     /// @dev The address of the current implementation
>     function _implementation() internal view override returns (address) {
>         return ERC1967UpgradeUpgradeable._getImplementation();
>     }
> }
> ```

**Comment by itsabinashb** [comment]
Can i do something like this:
There should be 2 contract,1. implementation and 2. proxy contract. implementation contract will hold all the main logic of my dapp where proxy contract will hold just function of changing implementation contract's address. First i will have to deploy the implementation contract.Now, proxy contract, should be inherited from UUPSUpgradeable, must have _authorizeUpgrade(address implementation). Then i will have to deploy the proxy contract. Now whenever i will have to change the code i change it and redeploy it with new code, then pass the implementation contract address to the authorizeUpgrade() to update the contract. After upgrading only the contract code will change, the state and record for every user will remain unchanged.

**Comment by itsabinashb** [comment]
My proxy contract looks like this: 
```
pragma solidity ^0.8.10;

import "openzeppelin-contracts-upgradeable/contracts/proxy/utils/UUPSUpgradeable.sol";
import "openzeppelin-contracts-upgradeable/contracts/proxy/utils/Initializable.sol";
import "openzeppelin-contracts-upgradeable/contracts/access/OwnableUpgradeable.sol";

contract Proxy is Initializable, UUPSUpgradeable, OwnableUpgradeable {
    address implemented;

    function initialize(address _newImplementation) public initializer {
        __UUPSUpgradeable_init();
        __Ownable_init();
        implemented = _newImplementation;
    }

    function upgradeTo(
        address newImplementation
    ) external virtual override onlyProxy {
        _authorizeUpgrade(newImplementation);
        _upgradeToAndCallUUPS(newImplementation, new bytes(0), false);
    }

    function _authorizeUpgrade(
        address newImplementation
    ) internal virtual override {}

    function getImplementedAddress() public view returns (address) {
        return implemented;
    }
}
```
