### ISSUE TITLE
Failure to run installation script on MacOS

### ISSUE THREAD

**Issue by thomas-waite** [gakonst/foundry#699]
### Component

Foundryup

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

NA

### What command(s) is the bug in?

foundryup

### Operating System

macOS (amd)

### Describe the bug

When attempting to install locally on MacOS Monterey, using `foundryup` (after having run `curl -L https://foundry.paradigm.xyz | bash`) I get the error:

```
tar: Error opening archive: Unrecognized archive format
```

Seperately, I also get a somewhat similar error in a Ubuntu CI environment when running `foundryup`:

```
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

Unsure what the cause is, thanks for the help!

**Comment by ditchfieldcaleb** [comment]
Also getting this error on Linux (Ubuntu 20.04 via WSL Win10)

**Comment by onbjerg** [comment]
Some artifacts are missing because Windows currently runs out of memory building the release which fails the entire release workflow. I'm investigating

**Comment by 0xNotes** [comment]
Installing on Manjaro and getting this issue as well. 
![image](https://user-images.githubusercontent.com/87887033/152918945-9f8c8556-f79f-43f5-8181-49ae4caf022a.png)

**Comment by jrhe** [comment]
This should be fixed now. The Windows release has been disabled to allow the other releases to build correctly, and the latest nightly release has builds for both MacOS and Linux.

**Comment by thomas-waite** [comment]
Awesome, works for me for both MacOS and Ubuntu. Thanks for fixing quickly!
