### ISSUE TITLE
Installation error on MacOs

### ISSUE THREAD

**Issue by realdiganta** [gakonst/foundry#702]
### Component

Foundryup

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What command(s) is the bug in?

foundryup

### Operating System

macOS (M1)

### Describe the bug

Getting error when running "foundryup" 

diganta.eth@Digantas-MacBook-Air ~ % foundryup
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0     55      0 --:--:-- --:--:-- --:--:--    57
tar: Error opening archive: Unrecognized archive format

**Comment by onbjerg** [comment]
Duplicate of #699
