### ISSUE TITLE
Forge install hangs when installing non existing repositories

### ISSUE THREAD

**Issue by sambacha** [gakonst/foundry#712]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### Describe the bug

running `forge install solmate` causes forge to hang instead of producing an exception, as forge is trying to install ` https://github.com/solmate`. - forge  install Rari-Capital/solmate correctly resolves to the git repo.

**Comment by gakonst** [comment]
I cannot reproduce this locally, just ran `forge install asdf` and it completed, although it did say "Installed asdf" instead of producing an error.

**Comment by onbjerg** [comment]
Was this fixed in #719?
