### ISSUE TITLE
Recompiling on every `forge test` run

### ISSUE THREAD

**Issue by odd-amphora** [gakonst/foundry#713]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (fcc0fe5 2022-02-10T00:02:11.333815+00:00)

### What command(s) is the bug in?

forge test

### Operating System

macOS (M1)

### Describe the bug

Subsequent calls to `forge test` cause contracts to be recompiled, even though no files have been changed.

**Comment by mattsse** [comment]
sounds like a cache bug, could you link me to the repo that's causing this or provide me with a minimal repro?

**Comment by mattsse** [comment]
thanks, will get that fixed!
