### ISSUE TITLE
Forge build broken when passing structs or contracts to lib functions

### ISSUE THREAD

**Issue by wilsoncusack** [gakonst/foundry#723]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (cfc4ff0 2022-02-12T00:25:18.343881+00:00)

### What command(s) is the bug in?

forge build

### Operating System

macOS (M1)

### Describe the bug

Pull [this](https://github.com/wilsoncusack/forge-broken-compiler-demo) repo and try to `forge build`. I get
<img width="693" alt="Screen Shot 2022-02-11 at 8 32 08 PM" src="https://user-images.githubusercontent.com/6678357/153690991-c6580ad4-7ef7-4845-aa0c-a52d2f098c05.png">

Note that I do not see this if I put all the contract / lib all in the test file.

**Comment by gakonst** [comment]
Does this still happen with `--no-auto-detect`? Seems like a multi version bug maybe? @mattsse

**Comment by mattsse** [comment]
thanks for raising this, will debug this manually @wilsoncusack

**Comment by mattsse** [comment]
@wilsoncusack 

forge does not resolve direct import paths.

```solidity
import {Foo, Bar} from "src/Foo.sol";
```

should rather be 

```solidity
import {Foo, Bar} from "./Foo.sol";
```

However, the solidity docs say that these imports

```solidity
import "./math/math.sol";
import "contracts/tokens/token.sol";
```

in `contracts/contract.sol` are resolved to

```
contracts/tokens/token.sol
contracts/math/math.sol
```

so we should consider this a bug and also basically add the equivalent of this "src/=src/" remapping when resolving direct imports.
