### ISSUE TITLE
Forge test does not properly handle contract tests with same contract name

### ISSUE THREAD

**Issue by joshieDo** [gakonst/foundry#724]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (cfc4ff0 2022-02-12T00:24:48.935714530+00:00)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

![image](https://user-images.githubusercontent.com/93316087/153701675-9d56b4bc-c3a0-48b4-b6bb-4b53393654be.png)

Test contracts with the same contract name and different filename do not throw error and only one of them is run. Ideally it either throws error, or runs them both under `Filename:Contract_Name`

**Comment by mattsse** [comment]
thanks,
This will be mitigated once this lands https://github.com/gakonst/ethers-rs/pull/882 so we real unique ids.

**Comment by onbjerg** [comment]
Is this a dupe of https://github.com/gakonst/foundry/issues/392?

**Comment by joshieDo** [comment]
you're right, mb. closing
