### ISSUE TITLE
Pretty view into calldata

### ISSUE THREAD

**Issue by meetmangukiya** [gakonst/foundry#732]
### Component

Cast

### Describe the feature you would like

Given calldata, pretty print the calldata split by method id, and there on split at every word / 32 byte like etherscan does
![Screenshot 2022-02-13 at 8 57 06 AM](https://user-images.githubusercontent.com/7620533/153737032-e1b0ae1f-2972-4eee-8150-54c06bc770de.png) with or without 4byte decoded method signature

**Comment by SusheendharVijay** [comment]
Anyone working on this? I can quickly add it

**Comment by onbjerg** [comment]
I don't think so, unless @meetmangukiya is :) Feel free to open up a PR

**Comment by meetmangukiya** [comment]
I am not working on this, you can go ahead @SusheendharVijay

**Comment by SusheendharVijay** [comment]
@onbjerg we can close this issue

**Comment by onbjerg** [comment]
Good work!
