### ISSUE TITLE
CLI alias for onchain operations

### ISSUE THREAD

**Issue by ayushm2003** [gakonst/foundry#738]
### Component

Cast

### Describe the feature you would like

@gakonst talked about this a bit [here](https://twitter.com/gakonst/status/1480226545675509774). The use case is clear, it can make it easier and help save time for a lot of common on-chain operations.

The challenge is to make it a plugin-like system, such that users can easily add new commands.

### Additional context

Have started looking into this, specifically at the method described [here](https://twitter.com/ceccon_me/status/1480246020063780864). I will try to learn more about clap, and see if this approach makes sense.

Suggestions for alternative methods are welcome!

**Comment by ayushm2003** [comment]
oh yeah, the plugin system should probably be able to resolve that. Though the tasks described there seem much more complicated than what is described here, think this can very well act as a starting ground.

**Comment by gakonst** [comment]
Let's consolidate maybe the discussion in the plugins issue?
