### ISSUE TITLE
Have a different cache directory than the default cache directory

### ISSUE THREAD

**Issue by Linsayv** [gakonst/foundry#750]
### Component

Forge

### Describe the feature you would like

The default cache directory could be named differently than the default one named `cache` that can clash with other toolings such as hardhat for example.

Currently we can only set wether or not we want to use cache as per the documentation https://onbjerg.github.io/foundry-book/reference/config.html#cache

### Additional context

https://github.com/nomiclabs/hardhat/issues/2306#issuecomment-1039471741

**Comment by onbjerg** [comment]
We could put it in `.forge`/`.foundry` instead, but I'm not sure what the trade-offs are. What is the primary clashing you see in the current implementation? Is it that `hardhat clean`/`forge clean` wipes the cache of each other?

**Comment by mds1** [comment]
Just linking to a related comment around cache location from https://github.com/gakonst/foundry/pull/698#issuecomment-1033121150

> I'll also mention I prefer hardhat's approach of having the cache folder local in the project directory, because it's more visible and easier to delete if there's issues. Whereas caching in `~./foundry` is more hidden, and you're a bit more likely to accidentally delete the wrong cache. Though `forge clean` should remove the current project's cache regardless, but still 🤷

**Comment by mds1** [comment]
Oops, yes and I should have noticed the lack of `~/`. Please ignore my comment then 🙃

**Comment by Linsayv** [comment]
If another tooling is already using the `cache` directory by watching the files inside it's really bothering, right now it seems that clashes come from hardhat but there might be new tooling in the future that require that, also it seems more consistent with the rest of the configuration to be able to specify whether I should locate my cache files (on faster or network drive for example)

**Comment by onbjerg** [comment]
Ah, so you would be fine with `cache` as default but having it be configurable?

**Comment by Linsayv** [comment]
Yes!

**Comment by onbjerg** [comment]
AFAIK `ethers-solc` already supports configuring this so it would be as simple as adding a flag `--cache-path` (or similar) to the CLI and a `cache_path` field on the config struct in the `config` crate, so I'm marking this is a good first issue :slightly_smiling_face:

**Comment by mattsse** [comment]
closed with #866
