### ISSUE TITLE
Tracing inspector

### ISSUE THREAD

**Issue by onbjerg** [gakonst/foundry#753]
This task is about re-adding tracing capabilities to the new REVM testing backend

**Comment by onbjerg** [comment]
So ideally we'd move anything pertaining to trace decoding from the runner to the CLI, as it is UI specific? Does this also go for logs?

**Comment by gakonst** [comment]
Yes re: logs. I think yeah let's defer the decoding step as much as possible, open minded to whether it's in the runner or in the CLI
