### ISSUE TITLE
Port cheatcodes

### ISSUE THREAD

**Issue by onbjerg** [gakonst/foundry#756]
The task is to port all existing cheatcodes:

- [x] `warp`
- [ ] `roll`
- [x] `fee`
- [x] `load`
- [x] `store`
- [x] `sign`
- [x] `addr`
- [x] `ffi`
- [x] `prank`
- [x] `startPrank`
- [x] `stopPrank`
- [x] `deal`
- [x] `etch`
- [x] `expectRevert`
- [x] `record`
- [x] `accesses`
- [x] `expectEmit`
- [x] `mockCall`
- [x] `clearMockedCalls`
- [x] `expectCall`
- [x] `getCode`
- [x] `label`
- [x] `assume`

**Comment by mds1** [comment]
Linking this issue to https://github.com/gakonst/foundry/issues/432, since IIUC the port to revm will enable the `mockCall`, `expectCall`, and `expectRevert` cheatcodes to work both for CALLs and JUMPs
