### ISSUE TITLE
The json format of compiled contract is not correct

### ISSUE THREAD

**Issue by laizy** [gakonst/foundry#765]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (e3bae77 2022-02-17T00:22:45.909541871+00:00)

### What command(s) is the bug in?

forge build

### Operating System

Linux

### Describe the bug

The json format of compiled contract is not correct. `deployed_bytecode` should be `deployedBytecode`.
https://docs.soliditylang.org/en/v0.7.4/using-the-compiler.html#output-description
```json
  "deployed_bytecode": {
    "object": "0x7xxx3",
    "sourceMap": "xxx",
    "linkReferences": {}
  }
```

**Comment by mattsse** [comment]
Fixed here https://github.com/gakonst/ethers-rs/pull/907 
should land shortly
