### ISSUE TITLE
Support Verify contract on Fantom

### ISSUE THREAD

**Issue by AlexandreBazeaud** [gakonst/foundry#777]
### Component

Forge

### Describe the feature you would like

Trying to verify contract on Fantom (chain-id 250) doesn't work

### Additional context

![image](https://user-images.githubusercontent.com/63203499/154856301-75c0e00a-5189-4106-9c77-42054f4f1fc8.png)

**Comment by AlexandreBazeaud** [comment]
Should be fixed with the commit i made into ethers-rs

**Comment by onbjerg** [comment]
Would like some confirmation and then we can close, we might not have updated ethers in Foundry yet :smile:

**Comment by gakonst** [comment]
Yep fixed now
