### ISSUE TITLE
Foundry `solc_version` specification does not work

### ISSUE THREAD

**Issue by deckardkrug** [gakonst/foundry#783]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.1.0

### What command(s) is the bug in?

forge build

### Operating System

Linux

### Describe the bug

Specifying `FOUNDRY_SOLC_VERSION` as an env variable or `solc_version` in `foundry.toml` should tell the compiler what solidity version it should use to compile the contracts.

Currently this is not the case as forge uses the latest solidity version instead of the specified one.

**Comment by mattsse** [comment]
thanks for raising this
could you make sure that the output of `forge config` contains the version you set?

**Comment by deckardkrug** [comment]
I just checked the output of `forge config` and can confirm that `solc_version` is set to the version I set.

Running `forge build` still logs `Compiling {number} files with 0.8.12`.
This also happens if I run `forge clean` first.
