### ISSUE TITLE
0x prefix inconsistent in object

### ISSUE THREAD

**Issue by r1cs** [gakonst/foundry#787]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (ff4ec0f 2022-02-15T00:28:49.003614+00:00)

### What command(s) is the bug in?

forge build

### Operating System

macOS (M1)

### Describe the bug

when I build contract, some `object` filed in `bytecode`&`deployed_bytecode` missing 0x prefix.making strict check for hex string failed.
Here is different object filed prefix with same command:
A contract:
```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

//import "../console.sol";
import "./MachineState.sol";
contract MemoryTest {
\\\
\\\
\\\
}
```
and out in bytecode filed:
```text
"bytecode": {
 "object": "6080604052..."
  "sourceMap": "114:1488:18:-:0;;;;;;;;;;;;;;;;;;;",
"linkReferences": {
      "/Users/w/w/r/r/cs/r/Register.sol": {
        "Register": [
          {
            "start": 3692,
            "length": 20
          },
          {
            "start": 3885,
            "length": 20
          }
        ]
      }


}
```

but in contract B:
```solidity
// SPDX-License-Identifier: GPL-v3
pragma solidity ^0.8.0;

import "../interfaces/IMemory.sol";
library MemoryLayout {
///
///
}
```
the output in bytecode fild is:
```text
"bytecode": {
"object": "0x610196..."
"sourceMap": "97:1376:1..."
"linkReferences": {}
}
```
It seems that compiler treat library and contract differently, making object output format not consistent.

**Comment by mattsse** [comment]
thanks for the repro!
will take a look if that's due some serde settings in ethers-rs

**Comment by mattsse** [comment]
this happens because the `MemoryTest` has links and serialized as `Bytecode::Unlinked`
and string serialisation does not add 0x prefix, 
I wonder what the consistent format should we, always 0x prefixed or never, like hardhat @gakonst?
