### ISSUE TITLE
yul optimizer doesn't seem to disable even with `yul = false` set under `optimizer_details` in `foundry.toml`

### ISSUE THREAD

**Issue by tdudz** [gakonst/foundry#793]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (6547691 2022-02-21T00:27:15.958524+00:00)

### What command(s) is the bug in?

forge build

### Operating System

macOS (M1)

### Describe the bug

am trying to build a foundry project that uses the [solidity-BigNumber](https://github.com/firoorg/solidity-BigNumber) library, which uses a lot of asm under the hood, specifically the `msize` instruction. when i run `forge build` i get the following error

```
SyntaxError: The msize instruction cannot be used when the Yul optimizer is activated because it can change its semantics. Either disable the Yul optimizer or do not use the instruction.
```

my `foundry.toml` looks like the following:
```
[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['ds-test/=lib/ds-test/src']
optimizer = true

[optimizer_details]
yul = false
```

it seems as if forge is not respecting the `yul = false` option?

**Comment by mattsse** [comment]
Thanks for raising this, this is indeed a bug due to improper toml for the `optimizer_details` table.
fixed in https://github.com/gakonst/foundry/pull/795

to make this work, you'd need to change it to

```toml
[default.optimizer_details]
yul = false
```
