### ISSUE TITLE
Testing on ERC20 token which has no return data (ex, USDT) fail and reverted.

### ISSUE THREAD

**Issue by dalgarim** [gakonst/foundry#804]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (67f9ed1 2022-02-23T00:32:01.483845067+00:00)

### What command(s) is the bug in?

forge test --rpc-url {...}

### Operating System

Linux

### Describe the bug

Hi,

When I called transfer function of USDT, It reverts an return to fallback().

I guess it is due to USDT's implemetation of transfer function which has no return value.

I tested other ERC20 tokens LINK and Dai which have not reverted.

And also, when I use OZ's SafeERC20 library, USDT doesn't reverted.

```
// SPDX-License-Identifier: MIT

pragma solidity ^0.7.6;

import "ds-test/test.sol";
import "./utils/Console.sol";
import "src/interface/IERC20.sol";

interface CheatCodes {
  function prank(address) external;
  function startPrank(address) external;
  function stopPrank() external;
}

contract Test2 is DSTest {
    address constant FAUCET = 0xF977814e90dA44bFA03b6295A0616a897441aceC;
    address constant TESTER = 0x00a329c0648769A73afAc7F9381E08FB43dBEA72;

    CheatCodes cheats = CheatCodes(HEVM_ADDRESS);
    IERC20 usdt = IERC20(0xdAC17F958D2ee523a2206206994597C13D831ec7);

    function faucet() public {
        cheats.startPrank(FAUCET);
        usdt.transfer(TESTER, 1*1e6);
        cheats.stopPrank();
    }

    function setUp() public {
        faucet();
    }
    function testTest() public {
        console.log(usdt.balanceOf(TESTER));
    }
}
```

```
root# forge test --fork-url http://localhost:8545/ --fork-block-number 14261277 -vvvv --debug --match-contract Test2
compiling...
Compiling 1 files with 0.7.6
Compilation finished successfully
success.
Running 1 test for Test2.json:Test2
[FAIL. Reason: Setup failed: Execution reverted: Revert(Reverted), (gas: 9079256848778621134)] testTest() (gas: 0)
Traces:

  [9079256848778621134] Test2::setUp()
    ├─ [0] VM::startPrank(0xf977814e90da44bfa03b6295a0616a897441acec)
    │   └─ ← ()
    ├─ [9079256848778614990] 0xdac1…1ec7::transfer(0x00a329c0648769a73afac7f9381e08fb43dbea72, 1000000)
    │   └─ ← ()
    └─ ← ()
  [0] 0x0000…0000::fallback()
    └─ ← ()


Failed tests:
[FAIL. Reason: Setup failed: Execution reverted: Revert(Reverted), (gas: 9079256848778621134)] testTest() (gas: 0)

Encountered a total of 1 failing tests, 0 tests succeeded
```

**Comment by gakonst** [comment]
ACK - I've reproduced and investigating

**Comment by gakonst** [comment]
OK so this is intended behavior.

Trying to integrate with USDT (or any of the tokens that were deployed with that bug) from a newer Solidity version without safe-transfer is expected to fail when using the "standard" ERC20 interface. This is because newer Solidity versions will try to decode the boolean return data, which in USDT case's there is none.

There's 3 ways to solve this:
1. Use Solidity 0.4.20 (not ideal)
2. Define `interface ERC20 { function transfer(address,uint256) external; }` (without the `returns (bool)` part so that Solidity doesn't try to decode the return data)
3. Use Safe Transfer
