### ISSUE TITLE
forge test displays incorrect gas for function call, but displays correct gas in `forge test -vvvv`

### ISSUE THREAD

**Issue by anticlimactic** [gakonst/foundry#812]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (98f0771 2022-02-25T00:42:54.200449+00:00)

### What command(s) is the bug in?

forge test -vvvv

### Operating System

macOS (amd)

### Describe the bug

`forge test` claims zero gas is used on transfer, but if you rerun the command with verbosity level 4, it shows that there is a non-zero gas amount that was used. 

<img width="1000" alt="foundry-issue" src="https://user-images.githubusercontent.com/9568756/155702131-951a3f4e-d7dd-46f4-900c-52fc1176a6fb.png">

test repo here:

https://github.com/anticlimactic/foundry-issue

install openzeppelin: `forge install openzeppelin/openzeppelin-contracts`

then run `forge test -vvvv`

**Comment by gakonst** [comment]
ACK - have repro'd. Investigating

**Comment by mds1** [comment]
This is very likely related to refunds. The numbers in the trace (bottom red circle) are raw gas values, and the top red circle includes refunds. The top red circle does not include the 21k + calldata gas, and it seems neither does the trace.

There is a chance refunds are not being applied correctly, see [EIP-3529](https://eips.ethereum.org/EIPS/eip-3529) for details on how it should now work. So I can imagine a situation where we are (1) applying too many refunds, and (2) subtracting away the intrinsic gas cost, resulting in a zero value being shown

**Comment by gakonst** [comment]
Given we'll be reimplementing tracing / evm as we transition to REVM, marking this for fixing when we get there: https://github.com/users/gakonst/projects/1

**Comment by onbjerg** [comment]
This is not an issue in the REVM port

![image](https://user-images.githubusercontent.com/8862627/158034127-98ca614b-38b8-40cb-ae32-4fb59b271784.png)

(Note that gas numbers are off since calldata + initial gas stipend is included)

**Comment by onbjerg** [comment]
So these are the final numbers accounting for refunds. Note the small discrepancy between the trace and the test result (described in #960) that is unaccounted for.

![image](https://user-images.githubusercontent.com/8862627/158794609-9dfc51d8-fd2c-44c5-8bb3-746a7087c596.png)

Is this more in line with what you expect?

**Comment by gakonst** [comment]
@anticlimactic are you OK with us closing this ticket once we merge Revm, and we track the 42 gas discrepancy in the new issue?

**Comment by anticlimactic** [comment]
that is fine. 👍
