### ISSUE TITLE
Changing ds-test submodule import so that cargo lets me use forge as a library

### ISSUE THREAD

**Issue by laudiacay** [gakonst/foundry#823]
### Component

Other (please describe)

### Describe the feature you would like

hi im working w the foundry codebase as a dependency in another codebase (yeah probably unstable internal apis risk accepted ✅)

anyway importing forge as a cargo dependency like so (`forge = { git = "https://github.com/gakonst/foundry"}`) *almost* works except i have to delete `/lib/ds-test` because cargo gets annoyed about the submodule not being properly in a .gitmodules. I just forked your repo and deleted the submodule for now. but idk if you want to fix this it's a total nitpick that'd make my life a little easier

### Additional context

minimal example: make a cargo project. put the dependency line above in a cargo.toml. import something from forge into a main.rs. 

witness:
```
    Updating git repository `https://github.com/gakonst/foundry`
error: failed to get `foundry` as a dependency of package `hedgebot v0.1.0 (/Users/laudiacay/hedgebot)`

Caused by:
  failed to load source for dependency `foundry`

Caused by:
  Unable to update https://github.com/gakonst/foundry?tag=nightly-d08a59ec16e07329c70f9a5ccf5dbb92baf367f3

Caused by:
  failed to update submodule `lib/ds-test`

Caused by:
  no URL configured for submodule 'lib/ds-test'; class=Submodule (17)
  ```
  
  :////

**Comment by gakonst** [comment]
I have no idea how this made it through, just pushed https://github.com/gakonst/foundry/commit/41f00a06860555b24db52a6ab6e8461191e77adc which should solve this. Please re-open if still an issue
