### ISSUE TITLE
GLIBC_2.29 not available in Debian 10

### ISSUE THREAD

**Issue by ind-igo** [gakonst/foundry#825]
### Component

Foundryup

### Operating System

Linux

### Describe the bug

have this error on Debian 10 when trying to run forge after installing via foundryup:

`forge: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.29' not found (required by forge)`

Googling the error shows that this is caused by Debian 10 having an older GLIBC.

There are 2 workarounds:

1. Suggested by @gakonst, refer to this article: https://kobzol.github.io/rust/ci/2021/05/07/building-rust-binaries-in-ci-that-work-with-older-glibc.html
2. You can build forge from scratch using the command `foundryup -b master`.

**Comment by onbjerg** [comment]
Fixed-ish in #826

**Comment by gakonst** [comment]
pls `rustup update`

**Comment by mudgen** [comment]
@gakonst Thanks for your help.  forge is working for me now.
