### ISSUE TITLE
Setting gas price during create

### ISSUE THREAD

**Issue by Peter-Flynn** [gakonst/foundry#836]
### Component

Forge

### Describe the feature you would like

When deploying contracts to certain EVM-compatible chains, gas price can be poorly estimated. If one is using a device, such as a Ledger, which does not allow for fee customization, this can lead to `forge create` being unusable. Ideally `create` should accept the `--gas-price` flag, and `ETH_GAS_PRICE` environment variable, like `cast` does.

**Comment by Peter-Flynn** [comment]
Crazy fast turnaround. Thanks for the hard work, folks.

**Comment by gakonst** [comment]
of course :) thank @meetmangukiya for shipping
