### ISSUE TITLE
Have same behaviour as on EVM for blockhash(blockNumber)

### ISSUE THREAD

**Issue by eboadom** [gakonst/foundry#837]
### Component

Forge

### Describe the feature you would like

At the moment, when running Forge tests against a fork of a running network (e.g. Ethereum mainnet), when doing `blockhash(someBlockNumber)`, the result is 0.
The desired behavior would be as in the Ethereum mainnet EVM environment, having access to the last 256 blocks.
This is especially important for use cases involving the verification of storage proofs against historic block hashes.

**Comment by onbjerg** [comment]
I think this is the case after REVM port, pinging @gakonst to get confirmation
