### ISSUE TITLE
DAPP_LIBRARIES env var has stopped working correctly

### ISSUE THREAD

**Issue by hexonaut** [gakonst/foundry#842]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (3a5347d 2022-01-22T17:34:26.261660+00:00)

### What command(s) is the bug in?

forge test

### Operating System

macOS (M1)

### Describe the bug

Running forge against https://github.com/makerdao/spells-mainnet produces this error:

```
[office] spells-mainnet (PE-876) $ export DAPP_LIBRARIES="src/DssSpell.sol:DssExecLib:0x8De6DDbCd5053d32292AAA0D2105A32d108484a6"
[office] spells-mainnet (PE-876) $ forge test --fork-url "$ETH_RPC_URL" --force
The application panicked (crashed).
Message:  failed to extract from provider: Error { tag: Tag(Global, 3), profile: Some(Profile(Uncased { string: "global" })), metadata: Some(Metadata { name: "`DAPP_` environment variable(s)", source: None, provide_location: Some(Location { file: "config/src/lib.rs", line: 544, col: 14 }), interpolater:  }), path: ["libraries"], kind: InvalidType(Str("src/DssSpell.sol:DssExecLib:0x8De6DDbCd5053d32292AAA0D2105A32d108484a6"), "a sequence"), prev: None }
Location: config/src/lib.rs:225
```

Previously it was working. Seems to be that the `DAPP_LIBRARIES` env var is not parsing correctly or something? Has this changed?

**Comment by mattsse** [comment]
Could not reproduce in #845 

But then I noticed that your version is outdated: 2022-01-22T17 

See also
https://github.com/gakonst/foundry#installation

**Comment by hexonaut** [comment]
Bleh yeah the transition to foundryup messed this up and was still using the old version by mistake. Latest forge appears to be working. Going to close this.
