### ISSUE TITLE
Add `--use` flag to the build args

### ISSUE THREAD

**Issue by tynes** [gakonst/foundry#846]
### Component

Forge

### Describe the feature you would like

I'd like to be able to pass a path to a `solc` binary on my machine and have that be used to build the project.
A new flag `--use` could be added to the `BuildArgs` to enable this.

`dapp` supports this feature, see: https://github.com/dapphub/dapptools/tree/master/src/dapp#solc-version

The usecase is to use a locally modified `solc` to build a project

### Additional context

Note that this can be achieved now with `SOLC_PATH`, see:
https://github.com/gakonst/ethers-rs/blob/46d7afd65bdcde4171d778523a0eab1ed2ad27e7/ethers-solc/src/compile/mod.rs#L123

**Comment by mattsse** [comment]
thanks for this, rn we're limited to `Version`, we should rather do `enum Solc {Local(), Version}` and make it compatible with dapp, even though I don't think we need the `solc:` prefix.

**Comment by tynes** [comment]
If `forge` is expanded to work with vyper and starkware maybe the prefix could be useful?
