### ISSUE TITLE
Configure tx call args in forge create

### ISSUE THREAD

**Issue by Inphi** [gakonst/foundry#863]
### Component

Forge

### Describe the feature you would like

I'd like to be able to configure the value, nonce, etc when deploying contracts using `forge create`. Some contracts require a specific amount at construction before they can be deployed.

**Comment by meetmangukiya** [comment]
Constructor args are already supported, so is value, gas price. Nonce is not really something you can configure, you'd need to track the EOA nonce yourself?

**Comment by Inphi** [comment]
I see that you just added that in on nightly. Thanks!
