### ISSUE TITLE
`ethers_solc::compile` decode error

### ISSUE THREAD

**Issue by cruzdanilo** [gakonst/foundry#874]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

0.1.0 (339ff41 2022-03-09T00:17:01.677842+00:00)

### What command(s) is the bug in?

forge build

### Operating System

macOS (M1)

### Describe the bug

this error is happening since the nightly version [`0.1.0 (339ff41 2022-03-09T00:17:01.677842+00:00)`](https://github.com/gakonst/foundry/actions/runs/1954499430)
```log
% forge build
Compiling...
Mar 08 22:12:14.030 ERROR ethers_solc::compile: ReqwestError(reqwest::Error { kind: Decode, source: Error("expected value", line: 1, column: 1) })
Compiling 3 files with 0.8.11
Compiler run successful
```

**Comment by onbjerg** [comment]
Seems like `blocking_all_releases` in `svm-rs` does not short circuit for M1 as `all_releases` does. I've put up a PR in `svm-rs` but the fix is going to take a while since we need to bump in `ethers-solc` and then here.

PR: https://github.com/roynalnaruto/svm-rs/pull/26

**Comment by maoueh** [comment]
What's the best way to revert to an earlier nightly version?

**Comment by gakonst** [comment]
Should be fixed in latest master, and on tonight's nightly.

**Comment by gakonst** [comment]
Interestingly enough, doing `--offline` still triggers the request. `--no-auto-detect` silences it successfully. @mattsse should we consolidate the 2 commands in some way?

**Comment by mattsse** [comment]
Fixed here https://github.com/gakonst/ethers-rs/pull/1002
