### ISSUE TITLE
forge installs prerelease instead of release versions of required solidity compiler

### ISSUE THREAD

**Issue by Pczek** [gakonst/foundry#892]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (7ed07e7 2022-03-10T00:04:06.029112+00:00)

### What command(s) is the bug in?

forge build

### Operating System

macOS (M1)

### Describe the bug

Even after an empty `.svm` directory forge always installs a prerelease version of the requested compiler `0.8.11-develop` instead of `0.8.11`.

`Ayush` on telegram suggested the error might be related to the fact, that ethers-rs installs the compiler via the following repo:
[`https://github.com/roynalnaruto/solc-builds/tree/master/macosx/aarch6](https://github.com/roynalnaruto/solc-builds/tree/master/macosx/aarch64)

Could be only arm mac related, afaik.

```
~/git/contracts-fresh main*
❯ forge build
Compiling...
installing solc version "0.8.11"
Successfully installed solc 0.8.11
Compiling 82 files with 0.8.11
Error:
   0: Compiler run failed
      Warning: This is a pre-release compiler version, please do not use it in production.



      ParserError: Source file requires different compiler version (current compiler is 0.8.11-develop.2022.2.16+commit.d7f03943.Darwin.appleclang) - note that nightly builds are considered to be strictly less than the released version
       --> /Users/peet/git/contracts-fresh/contracts/compound/strategies/AlpacaERC4626.sol:2:1:
        |
      2 | pragma solidity 0.8.11;
        | ^^^^^^^^^^^^^^^^^^^^^^^


```

**Comment by mattsse** [comment]
thanks for raising this.
solc-builds need to updated as mentioned in https://github.com/roynalnaruto/solc-builds/issues/1

**Comment by roynalnaruto** [comment]
https://github.com/roynalnaruto/solc-builds/issues/1 has been closed with the following updates:
- https://github.com/roynalnaruto/solc-builds/commit/d1388e554684c5a10954d0c80182e671c4fc2ade
- https://github.com/roynalnaruto/svm-rs/commit/76a9779c1985ca39192f8254494d72f5802602df

**Comment by WyseNynja** [comment]
So with that solc-builds PR closed, what are the next steps? I'd like to try out foundry, but am blocked by this.

**Comment by transmissions11** [comment]
also seeing this

**Comment by transmissions11** [comment]
kings

**Comment by cruzdanilo** [comment]
since the latest nightly (1d31ecb 2022-03-12), i'm having this error when using solc 0.8.12, macos m1. it works fine for 0.8.11.
```log
% forge test -m Operations 
[⠊] Compiling...
Error: 
   0: Solc Error: 

Location:
   cli/src/cmd/mod.rs:96
```

**Comment by gakonst** [comment]
Can you guys provide some more debug info? `RUST_LOG=ethers=trace forge t`, plus try running it again, nuking your ~/.svm directory etc

**Comment by transmissions11** [comment]
nuking .svm fixed 👍

**Comment by gakonst** [comment]
great :)
