### ISSUE TITLE
Fix: Forge build extra-output options breaking

### ISSUE THREAD

**Issue by abigger87** [gakonst/foundry#897]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (7ed07e7 2022-03-10T00:10:52.317533069+00:00)

### What command(s) is the bug in?

forge build

### Operating System

Linux

## Overview

`forge build` breaks when specifying the following `--extra-outputs`:
- [ ] `ewasm`
- [ ] `metadata`
- [ ] `userdoc`

##### Ewasm Extra Output
![forge_build_ewasm](https://user-images.githubusercontent.com/21288394/157697035-4ab9a077-fe83-45fe-8f89-d8f9c8dd3382.jpg)

##### Metadata Extra Output
![forge_build_metadata](https://user-images.githubusercontent.com/21288394/157697159-cf7ba555-b9f7-43b1-b62c-e11fb4611a40.jpg)

##### Userdoc Extra Output
![forge_build_userdoc](https://user-images.githubusercontent.com/21288394/157697281-6ebe187e-4fb3-4c9a-9415-1a96454d80c3.jpg)

**Comment by mattsse** [comment]
Fixed here https://github.com/gakonst/ethers-rs/pull/1004
