### ISSUE TITLE
 bug: `forge update` includes --remote flag

### ISSUE THREAD

**Issue by lucas-manuel** [gakonst/foundry#898]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (7ed07e7 2022-03-10T00:04:06.029112+00:00)

### What command(s) is the bug in?

forge update

### Operating System

macOS (M1)

### Describe the bug

`forge update` does `git submodule update --init --recursive --remote`
`dapp update` does `git submodule update --init --recursive`

We use `forge update` in GH actions but it breaks when we want to intentionally point to a specific submodule commit.

**Comment by onbjerg** [comment]
If the intention is to install the current submodules you should use `forge install` (no args). `forge update` with no args pulls the latest commit for all submodules
