### ISSUE TITLE
Grey zero values in debugger memory

### ISSUE THREAD

**Issue by DanielVF** [gakonst/foundry#902]
### Component

Forge

### Describe the feature you would like

Solidity memory is often zero. Sometimes overwhelmingly so it. It's hard to see the actual data in the memory view because it's mostly zeros. By making zeros bytes in the memory view dim grey, the real data stands out, and the structure and length of the real data is much more visible.

### Additional context

Mockup:

<img width="989" alt="image" src="https://user-images.githubusercontent.com/837/157788737-f378638f-0953-4903-a3b7-2f51c2ca184a.png">

**Comment by onbjerg** [comment]
I will address this in #920
