### ISSUE TITLE
feat: make default deploying address an "EOA" type account

### ISSUE THREAD

**Issue by cookieplug** [gakonst/foundry#906]
### Component

Foundryup

### Describe the feature you would like

When the default address (`0xb4c79dab8f259c7aee6e5b2aa729821864227e84`) is used to deploy token contracts such as an ERC721 or an ERC1155, the `onERC1155/721Received` methods for this address are not implemented by default. Attempting to mint tokens to this address simply results in an "ERC1155/721: transfer to non ERC1155/721Receiver implementer" error. If possible, I would like to request that this default address has these functions implemented to allow for easier testing. Thanks!

**Comment by gakonst** [comment]
It's not the default address doing the deployment, it's the test contract itself, so it's unavoidable! I'd recommend using "vm.prank" and vm.startPrank to imitate EOAs
