### ISSUE TITLE
forge check-snapshot

### ISSUE THREAD

**Issue by transmissions11** [gakonst/foundry#910]
### Component

Forge

### Describe the feature you would like

Would like a command to run in CI that checks that the `.gas-snapshots` file does not change if `forge run --snapshot` is run again (aka ensuring its up to date)

### Additional context

This will only be viable to implement once fuzz tests are not included in the snapshot output, as otherwise the command would almost never pass for repos with fuzz tests

**Comment by mattsse** [comment]
the current behavior of 

`forge snapshot --check` is

```console
        --check [<CHECK>]
            Run snapshot in 'check' mode and compares against an existing snapshot file, [default: .gas-snapshot]. Exits with 0 if snapshots match. Exits with 1 and prints a diff otherwise
```

this is what you had in mind?

on fuzz tests, we could easily remove in snapshot output,
But perhaps we continue to include them in the snapshot but simply skip them when comparing?

**Comment by transmissions11** [comment]
oh i didn't even realize we had that!
