### ISSUE TITLE
forge snapshot --watch

### ISSUE THREAD

**Issue by transmissions11** [gakonst/foundry#911]
### Component

Forge

### Describe the feature you would like

When I'm optimizing I find myself running snapshot over and over again, would be nice to automate all that

**Comment by transmissions11** [comment]
should default to `--run-all`

**Comment by virtualjpeg** [comment]
this could be useful:

https://github.com/watchexec/watchexec

**Comment by transmissions11** [comment]
We already have infra for running commands n such when files change for forge test/build —snapshot :p

**Comment by virtualjpeg** [comment]
hahah didn't realize! I'll have a look at working on this
