### ISSUE TITLE
forge snapshot --check doesn't distinguish test names

### ISSUE THREAD

**Issue by transmissions11** [gakonst/foundry#912]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (f01d2f7 2022-03-11T00:05:09.559922+00:00)

### What command(s) is the bug in?

forge snapshot --check

### Operating System

macOS (M1)

### Describe the bug

`forge snapshot --check` doesn't account for the fact that there can be multiple tests across different test files with the same name, this leads to it thinking the snapshots don't match for certain tests when they do

**Comment by mattsse** [comment]
oh right, we only use the sig 

https://github.com/gakonst/foundry/blob/3057f6aeb09c1dc7d6913775774851b815dc4244/cli/src/cmd/snapshot.rs#L259

should use filename + sig
