### ISSUE TITLE
Target native CPU on `foundryup -b`

### ISSUE THREAD

**Issue by onbjerg** [gakonst/foundry#974]
We should compile Foundry with `RUSTFLAGS="-C target-cpu=native" cargo build --release --bin forge` if you use `foundryup -b`.

https://github.com/gakonst/foundry/pull/918#issuecomment-1071732702

**Comment by dmfxyz** [comment]
should we also do this on `-r` as well (assuming the value is not set to the main repository)?

**Comment by onbjerg** [comment]
Yes

**Comment by onbjerg** [comment]
Fixed
