### ISSUE TITLE
Deserialization Error during forge create

### ISSUE THREAD

**Issue by EzraWeller** [gakonst/foundry#982]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (db909f2 2022-03-18T04:18:37.785422+00:00)

### What command(s) is the bug in?

forge create

### Operating System

macOS (amd)

### Describe the bug

The bug is happening with this codebase: https://github.com/R-Group-Devs/squadz-contracts

`forge build` succeeds (`Compiler run successful (with warnings)`)

`forge test` passes all tests.

I am using a `.env` file that matches the pattern in `.env-example` and running:
`% export $(cat .env | xargs) && forge create --chain $CHAIN --private-key $PRIVATE_KEY --etherscan-api-key $ETHERSCAN_API_KEY src/SquadzEngine.sol:SquadzEngine`

Have tried deploying to both polygon and polygon testnet mumbai, both getting this result from the `create`:
```
Error: 
   0: Deserialization Error: invalid type: null, expected u64 at line 1 column 26. Response: {"jsonrpc":"2.0","id":null,"result":"0x89"}

Location:
   cli/src/cmd/create.rs:104
   ```

I also noticed that `foundryup` did not seem to get me up to this version, even with `foundryup --version nightly`. I installed this version using `cargo install --git https://github.com/gakonst/foundry --locked` instead.

LMK if I can provide additional context.

**Comment by mattsse** [comment]
this is certainly weird, this happened when it was attempted to fetch the polygon chain id: "result":"0x89" is 137.

I couldn't reproduce this on polygon when I executed .get_chainid manually. 

I also tried https://rpc-mumbai.matic.today (https://docs.polygon.technology/docs/develop/network-details/network/) wich returns 80001 correctly

But the error is `"id":null,` which makes this an invalid json response object, because the "id" field is required according to the spec.

So perhaps this was just a temporary issue on polygon's end?

**Comment by EzraWeller** [comment]
I did just get a successful deploy to Mumbai. Verifying there is failing, though: 
```
Contract verification failed:
Response: `NOTOK`
Details: `Fail - Unable to verify`
```
For Polygon, I'm getting the same result from that RPC endpoint but a different result from `https://matic-mainnet.chainstacklabs.com`: tx stalled and now when I try to re-run it I get `code: -32000, message: replacement transaction underpriced, data: None)`. 

Not sure how to resolve either of these new problems, but it does seem like the original issue is just a specific problem with that RPC endpoint.

**Comment by mattsse** [comment]
I noticed some deps are missing on that repo, could you add them and ensure forge test. I'd like to debug verify on that because that has been a bit flaky and I'd like to make sure flattening etc works correctly.

**Comment by mattsse** [comment]
oh looking at the submodules I know what's up, perhaps that another issue with `forge install`, but you should consider updating the submodule paths

**Comment by mattsse** [comment]
Oh I think I found the issue, working on a fix shortly.

**Comment by EzraWeller** [comment]
Aha, so verifying requires flattening where compiling to test and deploy doesn't, is that right?

Sounds like maybe if I change the name of one of the IERC721 interfaces it might fix things for now.

**Comment by mattsse** [comment]
great!
