### ISSUE TITLE
Consider making forge test --match-path <regex> not absolute

### ISSUE THREAD

**Issue by mattsse** [gakonst/foundry#986]
### Component

Forge

### Describe the feature you would like

currently this argument "Requires absolute path" which makes it a bit cumbersome to use.
it should also wor like `--match-path "src/Proxy*"` instead of requiring the absolute path to `src`

**Comment by onbjerg** [comment]
Fixed somewhere along the way 😄

**Comment by mattsse** [comment]
closed by #1229
