### ISSUE TITLE
foundry.toml configuration not being added 

### ISSUE THREAD

**Issue by PatrickAlphaC** [gakonst/foundry#996]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

foundry-cli 0.1.0

### What command(s) is the bug in?

forge test

### Operating System

macOS (amd)

### Describe the bug

I have a `foundry.toml` file that looks as such:

```
[default]
fuzz_runs = 1000 
```

However, when I run `forge test` with a fuzzing test I still get 256 tests:

```
compiling...
no files changed, compilation skippped.
Running 1 test for "StakeContractTest.json":StakeContractTest
[PASS] test_staking_tokens_fuzz(uint16) (runs: 256, μ: 81664, ~: 81665)
```

Test file:

```javascript
// SPDX-License-Identifier: Unlicense
pragma solidity 0.8.10;

import "ds-test/test.sol";
import "../StakeContract.sol";
import "./mocks/MockERC20.sol";


contract StakeContractTest is DSTest {
    StakeContract public stakeContract;
    MockERC20 public mockToken; 

    function setUp() public {
        stakeContract = new StakeContract();
        mockToken = new MockERC20();
    }

    function test_staking_tokens_fuzz(uint16 amount) public {
        mockToken.approve(address(stakeContract), amount);
        bool stakePassed = stakeContract.stake(amount, address(mockToken));
        assertTrue(stakePassed);
    }

}
```

I don't have any environment variables that would override fuzz runs.

With this, I'm also not able to put `remappings` or anything into my `foundry.toml` and get the variables pulled in.

Is there some flag I need to set to tell forge to look for `foundry.toml`?

### How to reproduce:

```
mkdir forge-test-example
cd forge-test-example
forge init
echo $'[default]\nfuzz_runs = 1000' > foundry.toml
```

Then, update your `Contract.t.sol` to:

```javascript
// SPDX-License-Identifier: Unlicense
pragma solidity 0.8.10;

import "ds-test/test.sol";

contract ContractTest is DSTest {
    function setUp() public {}

    function testExample(uint256 amount) public {
        assertTrue(true);
    }
}
```

Run;
```
forge test
```

We _should_ see 1000 runs, but we still only see 256.

**Comment by gakonst** [comment]
Would you try `fuzz-runs = 1000 ` (no underscore)

**Comment by PatrickAlphaC** [comment]
Still only got 256 runs

Try this:

```
mkdir forge-test-example
cd forge-test-example
forge init
touch foundry.toml
echo $'[default]\nfuzz_runs = 1000' > foundry.toml
```

Then, update your `Contract.t.sol` to:

```javascript
// SPDX-License-Identifier: Unlicense
pragma solidity 0.8.10;

import "ds-test/test.sol";

contract ContractTest is DSTest {
    function setUp() public {}

    function testExample(uint256 amount) public {
        assertTrue(true);
    }
}
```

Run;
```
forge test
```

Do you still only get 256 runs?

**Comment by mattsse** [comment]
does ` forge config | grep fuzz_runs` show you the adjusted fuzz runs?

**Comment by mattsse** [comment]
can't reproduce,

try appending only `fuzz_runs = 1000` without `[default]`

you can also set `FOUNDRY_FUZZ_RUNS=1000`. all config values have an uppercase env var with `FOUNDRY_` prefix

**Comment by mds1** [comment]
Where does `which forge` point? Guessing you still have an old cargo installation and should run `rm -rf ~/.cargo/bin/cast && rm -rf ~/.cargo/bin/forge`

**Comment by PatrickAlphaC** [comment]
Looks like that was it. I deleted them and it's all good now!

So.. for upgrading we have to first delete the old ones then run`foundryup` ?

**Comment by mds1** [comment]
Not anymore—going forward you can just use `foundryup` which installs to `~/.foundry`, instead of `~/.cargo`

Prior to `foundryup` you had to build foundry yourself using cargo. In your case you still had an old version in your `~/.cargo` directory which was taking precedence over `~/.foundry` in your PATH

**Comment by PatrickAlphaC** [comment]
aahhh ok ok. Thanks!
